### ISSUE TITLE
`ckeditor5-dev-env#upload` may end with an error due to passing a number in a cell to `cli-table`

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#10861]
## 📝 Provide detailed reproduction steps (if any)

When executing `translations:upload`, at the end of the task we display a summary with changes. Unfortunately, passing a number as an argument in `table.push`, ends with an error when calling `table.toString()`.

```js
const Table = require( 'cli-table' );

const table = new Table( {
			head: [ 'Package name', 'Added', 'Updated', 'Removed' ],
			style: { compact: true }
		} );

{
	changedItems: [
		[
			'ckeditor5-foo',
			{
				strings_added: 0,
				strings_updated: 1,
				strings_skipped: 0,
				strings_delete: 1,
				redirect: '/ckeditor-5-package-generator/ckeditor-5-package-generator/ckeditor5-foo/'
			}
		]
	]
}

table.push( [ packageName, response.strings_added, response.strings_updated, response.strings_delete ] );
```

### ✔️ Expected result

No error, just a table.

![image](https://user-images.githubusercontent.com/2270764/142408403-d1f12ed8-aad0-468a-ace7-6fcd35225452.png)

### ❌ Actual result

```
(node:61679) UnhandledPromiseRejectionWarning: TypeError: stripped.split is not a function
    at Object.exports.strlen (/Users/pomek/Projects/tmp/ckeditor5-foo/node_modules/cli-table/lib/utils.js:86:24)
    at get_width (/Users/pomek/Projects/tmp/ckeditor5-foo/node_modules/cli-table/lib/index.js:138:70)
    at /Users/pomek/Projects/tmp/ckeditor5-foo/node_modules/cli-table/lib/index.js:131:68
    at Array.forEach (<anonymous>)
    at extractColumnWidths (/Users/pomek/Projects/tmp/ckeditor5-foo/node_modules/cli-table/lib/index.js:130:9)
    at /Users/pomek/Projects/tmp/ckeditor5-foo/node_modules/cli-table/lib/index.js:104:11
    at Array.forEach (<anonymous>)
    at Table.toString (/Users/pomek/Projects/tmp/ckeditor5-foo/node_modules/cli-table/lib/index.js:101:16)
    at printSummary (/Users/pomek/Projects/tmp/ckeditor5-foo/node_modules/@ckeditor/ckeditor5-dev-env/lib/translations/upload.js:146:22)
    at /Users/pomek/Projects/tmp/ckeditor5-foo/node_modules/@ckeditor/ckeditor5-dev-env/lib/translations/upload.js:49:4
```

### ❓ Possible solution

Cast all data to string when adding new rows when using the `cli-table` package.

**Comment by pomek** [comment]
Yhm. See: https://github.com/Automattic/cli-table/issues/152.
