### ISSUE TITLE
Cannot build ckeditor5 as descriped in documentation

### ISSUE THREAD

**Issue by topse** [ckeditor/ckeditor5#11216]
Hi,
I am following the instructions  to build the ckeditor5 found here:

https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html

```
git clone -b stable https://github.com/ckeditor/ckeditor5

cd ckeditor5/packages/ckeditor5-build-classic
npm install
```

Without adding or changing anything:

```
yarn run build
or:
npm run build
```

Does not matter if used with yarn or npm, I get the following error:

```
PS C:\Users\topse\home\projects\test\ckeditor5\packages\ckeditor5-build-classic> npm run build   

> @ckeditor/ckeditor5-build-classic@32.0.0 build
> webpack --mode production

[webpack-cli] ReferenceError: Cannot access 'uniqueMessages' before initialization
    at emitError (u:\Users\...\home\projects\test\ckeditor5\packages\ckeditor5-build-classic\node_modules\@ckeditor\ckeditor5-dev-webpack-plugin\lib\servetranslations.js:149:3)
    at serveTranslations (u:\Users\...\home\projects\test\ckeditor5\packages\ckeditor5-build-cl    at createCompiler (u:\Users\...\home\projects\test\ckeditor5\packages\ckeditor5-build-classic\node_modules\webpack\lib\webpack.js:73:12)
    at create (u:\Users\...\home\projects\test\ckeditor5\packages\ckeditor5-build-classic\node_modules\webpack\lib\webpack.js:134:16)
    at webpack (u:\Users\...\home\projects\test\ckeditor5\packages\ckeditor5-build-classic\node_modules\webpack\lib\webpack.js:142:47)
    at WebpackCLI.f [as webpack] (u:\Users\...\home\projects\test\ckeditor5\packages\ckeditor5-build-classic\node_modules\webpack\lib\index.js:58:16)
    at WebpackCLI.createCompiler (u:\Users\...\home\projects\test\ckeditor5\packages\ckeditor5-build-classic\node_modules\webpack-cli\lib\webpack-cli.js:2193:23)
    at async WebpackCLI.runWebpack (u:\Users\...\home\projects\test\ckeditor5\packages\ckeditor5-build-classic\node_modules\webpack-cli\lib\webpack-cli.js:2323:16)
    at async Command.<anonymous> (u:\Users\...\home\projects\test\ckeditor5\packages\ckeditor5-build-classic\node_modules\webpack-cli\lib\webpack-cli.js:1060:13)
```

Versions:
```
npm 8.4.1
ckeditor5 32.0.0
Building on Windows x64
```

Do I make a mistake??

Best Regards,
Tobias

**Comment by Mgsy** [comment]
Hi @topse!

Thanks for the report. I've followed your steps and, unfortunately, I was not able to reproduce your issue. The editor builds properly with no errors. 

My environment info:

*   Windows 10
*   Node.js@16.13.2
*   npm@8.1.2

Maybe there are some additional steps I should perform to reproduce the problem?

**Comment by topse** [comment]
I am really sorry -- you are right. When I try to run the build with the integrated terminal of VSCODE, I get the error. But when using the Git-Bash, it works... So I guess there is something with the environment in VSCode.

Thanks and sorry for bothering.

Tobias
