### ISSUE TITLE
Mention execute with range does not work

### ISSUE THREAD

**Issue by bartlomiejwendt** [ckeditor/ckeditor5#11299]
## 📝 Provide detailed reproduction steps (if any)

1. Open CKEditor 5 docs and head to: https://ckeditor.com/docs/ckeditor5/latest/api/module_mention_mentioncommand-MentionCommand.html
2. Copy example:
```
const focus = editor.model.document.selection.focus;

// It will replace one character before the selection focus with the '#1234' text
// with the mention attribute filled with passed attributes.
editor.execute( 'mention', {
	marker: '#',
	mention: {
		id: '#1234',
		name: 'Foo',
		title: 'Big Foo'
	},
	range: model.createRange( focus, focus.getShiftedBy( -1 ) )
} );
```
3. Try to execute this in your editor

### ✔️ Expected result

Mention should be inserted into the editor at a specific range without any problems

### ❌ Actual result

Mention is not being inserted and the console returns an error:

```
CKEditorError: insert-operation-position-invalid
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-insert-operation-position-invalid
    at Tc._validate (insertoperation.js:111:1)
    at ml.on.priority (model.js:89:1)
    at ml.fire (emittermixin.js:198:1)
    at ml.<computed> [as applyOperation] (observablemixin.js:262:1)
    at Ic.insert (writer.js:222:1)
    at nl._insertPartialFragment (insertcontent.js:367:1)
    at nl.handleNodes (insertcontent.js:226:1)
    at insertcontent.js:71:1
    at ml.change (model.js:182:1)
    at insertcontent.js:51:1 {phase: 'runtime', willEditorRestart: true}
```

## 📃 Other details

* Browser: Chrome 97, Firefox 96.2
* OS: macOS
* First affected CKEditor version: 5
* Installed CKEditor plugins: Mention

---

**Comment by FilipTokarski** [comment]
Hi, if you want to insert mention in the cursor position, you can use this snippet but without using `getShiftedBy` method:

```js
const focus = editor.model.document.selection.focus;
const model = editor.model;

editor.execute( 'mention', {
	marker: '#',
	mention: {
		id: '#1234',
		name: 'Foo',
		title: 'Big Foo'
	},
	range: model.createRange( focus, focus )
} );
```


https://user-images.githubusercontent.com/34380544/154490797-62f64eea-a798-4fc6-9b11-7418f980f9db.mp4


But I understand that the description of this snippet might be confusing. I guess it should be updated to something more clear and straightforward.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report, the snippet should be like this:

```js
const selection = editor.model.document.selection;
const model = editor.model;

editor.execute( 'mention', {
	marker: '#',
	mention: {
		id: '#1234',
		name: 'Foo',
		title: 'Big Foo'
	},
	range: model.createRange( selection.getFirstPosition() )
} );
```

**Comment by bartlomiejwendt** [comment]
Hello, thanks for response I've figured this out this way and it works perfectly fine now:

```
 const end = editor.model.document.selection.getFirstPosition().getShiftedBy(-(hashtag.length + 1)) // we add 1 here because hashtagSearchTerm does not contain '#' marker
      const start = editor.model.document.selection.getFirstPosition()
      const range = model.createRange(end, start)

      editor.execute('mention', {
        marker: '#',
        mention: {
          id: `#${hashtag}`,
          text: `#${hashtag}`,
          hashtag,
        },
        range,
      })
```
