### ISSUE TITLE
Error when removing formatting on text

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#11348]
## 📝 Provide detailed reproduction steps (if any)

1. Switch to `ck/10812-document-list-editing`
3. Add bold to text (or any other formatting)
4. Select the text
5. Click `Remove formatting`

Alternatively, you can just select the text and click `bold` twice.

### ✔️ Expected result

Formatting is removed, no errors.

### ❌ Actual result
Error in the console. Cannot reproduce on `master`.

```js
Uncaught TypeError: Cannot read properties of null (reading 'hasAttribute')
    at Document.<anonymous> (converters.js:152:1)
    at Document.fire (emittermixin.js:200:1)
    at Document._handleChangeBlock (document.js:309:1)
    at Model._runPendingChanges (model.js:868:1)
    at Model.change (model.js:201:1)
    at RemoveFormatCommand.execute (removeformatcommand.js:40:1)
    at RemoveFormatCommand.<anonymous> (observablemixin.js:258:1)
    at RemoveFormatCommand.fire (emittermixin.js:200:1)
    at RemoveFormatCommand.<computed> [as execute] (observablemixin.js:262:1)
    at CommandCollection.execute (commandcollection.js:69:1)
```

### Screencast

https://user-images.githubusercontent.com/34380544/155961943-3e0d1c8b-2f15-4786-8b31-b3a4b723aa26.mp4

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
The same happens after unlinking text:
```js
Uncaught TypeError: Cannot read properties of null (reading 'hasAttribute')
    at Document.<anonymous> (converters.js:152:1)
    at Document.fire (emittermixin.js:200:1)
    at Document._handleChangeBlock (document.js:309:1)
    at Model._runPendingChanges (model.js:868:1)
    at Model.change (model.js:201:1)
    at UnlinkCommand.execute (unlinkcommand.js:57:1)
    at UnlinkCommand.<anonymous> (observablemixin.js:258:1)
    at UnlinkCommand.fire (emittermixin.js:200:1)
    at UnlinkCommand.<computed> [as execute] (observablemixin.js:262:1)
    at CommandCollection.execute (commandcollection.js:69:1)
```

**Comment by Reinmar** [comment]
Not reproducible anymore.
