### ISSUE TITLE
Error after getting data with html comment in list item

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#11350]
## 📝 Provide detailed reproduction steps (if any)

1. Switch to `ck/10812-document-list-editing`
2. Create a list item with html comment inside it
3. Call `getData()` or try to open source view

### ✔️ Expected result

No errors.

### ❌ Actual result

```js
Uncaught CKEditorError: mapping-model-position-view-parent-not-found {"modelPosition":{"root":"main","path":[0,4],"stickiness":"toNone"}}
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-mapping-model-position-view-parent-not-found
    at Mapper.on.priority (mapper.js:126:1)
    at Mapper.fire (emittermixin.js:200:1)
    at Mapper.toViewPosition (mapper.js:380:1)
    at DowncastDispatcher.<anonymous> (downcasthelpers.js:1165:1)
    at DowncastDispatcher.fire (emittermixin.js:200:1)
    at DowncastDispatcher._convertMarkerAdd (downcastdispatcher.js:393:1)
    at DowncastDispatcher.convert (downcastdispatcher.js:206:1)
    at DataController.toView (datacontroller.js:256:1)
    at DataController.stringify (datacontroller.js:216:1)
    at DataController.get (datacontroller.js:201:1)
```

### Screencast

https://user-images.githubusercontent.com/34380544/155964476-126a571b-f12d-4da4-bb18-8761f316a961.mp4

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Same as in #11354, this is fixed already on some next feature branches. I'll keep it open too to check it later.

**Comment by arkflpc** [comment]
Checked. Seems to be solved on `master` branch already.
