### ISSUE TITLE
Error after getting data with code block in list

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor5#11354]
## 📝 Provide detailed reproduction steps (if any)

1. Switch to ck/10812-document-list-editing.
2. Open documentlist manual test.
3. Select "Second" word and turn it into code block.
4. Call `editor.getData()`

or 

3. Select a single line list item.
5. Change it to code block.
6. Add something after the code block in the same bullet point.
7. Call `editor.getData()`.

### ✔️ Expected result

Editor data is returned.

### ❌ Actual result

Error on `editor.getData()` in the console:

```
emittermixin.js:233 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at Mapper.getModelLength (mapper.js:531:1)
    at Mapper.findPositionIn (mapper.js:595:1)
    at Mapper.on.priority (mapper.js:129:1)
    at Mapper.fire (emittermixin.js:200:1)
    at Mapper.toViewPosition (mapper.js:380:1)
    at DowncastDispatcher.<anonymous> (converters.js:403:1)
    at DowncastDispatcher.fire (emittermixin.js:200:1)
    at DowncastDispatcher._testAndFire (downcastdispatcher.js:549:1)
    at DowncastDispatcher._convertInsert (downcastdispatcher.js:295:1)
    at DowncastDispatcher.convert (downcastdispatcher.js:203:1)
```

**Comment by Reinmar** [comment]
On our newest branches (the one for list props) it works fine. I'll keep the ticket open for some time to verify later that we didn't break it again.

**Comment by Reinmar** [comment]
It's still fixed on latest `master`.
