### ISSUE TITLE
Uncaught TypeError with nested GHS syntax

### ISSUE THREAD

**Issue by lauriii** [ckeditor/ckeditor5#11450]
## 📝 Provide detailed reproduction steps (if any)

On `/ckeditor5-html-support/tests/manual/ghs-all-features.html` wrap `<p style="color:blue;">...</p>` with `<div>` and 💥

### ✔️ Expected result

... This should work 😇

### ❌ Actual result

Following exception is thrown which renders CKEditor 5 fully unusable:

```
conversionutils.js:48 Uncaught TypeError: target[key] is not iterable
    at mergeViewElementAttributes (conversionutils.js:48:1)
    at UpcastDispatcher.dispatcher.on.priority (converters.js:106:1)
    at UpcastDispatcher.fire (emittermixin.js:199:1)
    at UpcastDispatcher._convertItem (upcastdispatcher.js:246:1)
    at UpcastDispatcher._convertChildren (upcastdispatcher.js:279:1)
    at UpcastDispatcher.<anonymous> (upcasthelpers.js:785:1)
    at UpcastDispatcher.fire (emittermixin.js:199:1)
    at UpcastDispatcher._convertItem (upcastdispatcher.js:246:1)
    at UpcastDispatcher._convertChildren (upcastdispatcher.js:279:1)
    at UpcastDispatcher.<anonymous> (upcasthelpers.js:441:1)
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by lauriii** [comment]
Drupal.org issue for this: https://www.drupal.org/project/drupal/issues/3268311

**Comment by lauriii** [comment]
This could be triggered by #11447

```
<a href="..." class="ghs-class">
	<drupal-media>
		<caption>
			...
		</caption>
	</drupal-media>
</a>
```

As it could generate:

```
<a href="..." class="ghs-class">
	<drupal-media>
		<caption>
			<a href="..." class="ghs-class">...</a>
		</caption>
	</drupal-media>
</a>
```

**Comment by lauriii** [comment]
Our `<drupal-media>` GHS integration can be found here: https://git.drupalcode.org/project/drupal/-/blob/9.4.x/core/modules/ckeditor5/js/ckeditor5_plugins/drupalMedia/src/drupalmediageneralhtmlsupport.js

**Comment by Reinmar** [comment]
Probably related issues:

*   #10657 (there's a solution proposed there)
*   #11477
