### ISSUE TITLE
Editor crashes after starting composition on a widget inside a table cell

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#11778]
## 📝 Provide detailed reproduction steps (if any)

1.  Switch to Japanese.
2.  Select a widget inside a table cell.
3.  Start composing.

### ✔️ Expected result

The composition works properly.

### ❌ Actual result

The editor crashes.

## 📃 Other details

Tested on Chrome.

Branch: `ck/11438-beforeinput-ime-research-vol1.1`

Error:

```
Uncaught TypeError: Cannot read properties of null (reading 'replaceChild')
    at Object.listenTo.context (widget.js:256:1)
    at Object.fire (emittermixin.js:200:1)
    at fireListenerFor (bubblingemittermixin.js:162:1)
    at Document.fire (bubblingemittermixin.js:43:1)
    at CompositionObserver.fire (domeventobserver.js:96:1)
    at CompositionObserver.onDomEvent (compositionobserver.js:38:1)
    at ProxyEmitter.listenTo.useCapture (domeventobserver.js:79:1)
    at ProxyEmitter.fire (emittermixin.js:200:1)
    at HTMLDivElement.domListener (emittermixin.js:293:1)
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Can you still reproduce this? I tested this on the Android branch and it worked for me.
