### ISSUE TITLE
Cannot use custom build CKEditor 5 with Angular v13 project: TypeError: this.editor.create is not a function

### ISSUE THREAD

**Issue by martinmolema** [ckeditor/ckeditor5#11843]
## 📝 Provide detailed reproduction steps (if any)

1. Angular version 13.0.3.
2. Custom build CKEditor 5 using Decoupled Editor
3. installed CKEditor5 using npm i: `npm install @ckeditor/ckeditor5-angular`
4. package.json says: `"@ckeditor/ckeditor5-angular": "^4.0.0",`
5. custom build package from CKEditor5 is in the folderstructure.
6. using angular material and formbuilder to link data to the form

I tried both the unzipped version of the CKEditor custom build (see link). 
[ckeditor5-34.0.0-skzs81il96jc.zip](https://github.com/ckeditor/ckeditor5/files/8794277/ckeditor5-34.0.0-skzs81il96jc.zip)

and tried to do 
```
npm install
npm run build
```
from the CKEditor `build`-folder to create the ckeditor.js file. 

My code: 
 ```typescript
import {CKEditor5} from "@ckeditor/ckeditor5-angular";
import * as Editor from '../../../../CKEditor/ckeditor';
dialog.component.ts:
  public ckEditorClassic = Editor;
  public ckconfig = CKEditorGlobalsService.config;
 ```
html:
 ```html
<ckeditor [config]="ckconfig" [editor]="ckEditorClassic" formControlName="interventionInfo"></ckeditor>
```

A "service" (more like a singleton) to provide all my instances with a CKEditor config: (ckeditor-globals.service.ts)

```typescript
import { Injectable } from '@angular/core';
import {TheUploadAdapterPlugin} from '../lib/the-upload-adapter-plugin';

@Injectable({
  providedIn: 'root'
})
export class CKEditorGlobalsService {

  public static config = { extraPlugins: [ TheUploadAdapterPlugin ] , toolbar: {
      items: [
        'heading',
        '|',
        'fontSize',
        'fontFamily',
        '|',
        'bold',
        'italic',
        'underline',
        'strikethrough',
        'subscript',
        'superscript',
        'removeFormat',
        '|',
        'fontBackgroundColor',
        'fontColor',
        '|',
        'alignment',
        '|',
        'numberedList',
        'bulletedList',
        '|',
        'indent',
        'outdent',
        '|',
        'todoList',
        'link',
        'blockQuote',
        'imageUpload',
        '|',
        'insertTable',
        'mediaEmbed',
        'pageBreak',
        '|',
        'undo',
        'redo',
        '|',
        'codeBlock',
        'specialCharacters'
      ]
    },
    language: 'nl',
    image: {
      resizeUnit: 'px',
      // Configure the available styles.
      styles: [
        'alignLeft', 'alignCenter', 'alignRight'
      ],

      // Configure the available image resize options.
      resizeOptions: [
        {
          name: 'imageResize:original',
          label: 'Original',
          value: null
        },
        {
          name: 'imageResize:200',
          label: '200px',
          value: '200'
        },
        {
          name: 'imageResize:300',
          label: '300px',
          value: '300'
        }
      ],

      // You need to configure the image toolbar, too, so it shows the new style
      // buttons as well as the resize buttons.
      toolbar: [
        'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight',
        '|',
        'imageResize',
        '|',
        'imageTextAlternative'
      ]
    },
    table: {
      contentToolbar: [
        'tableColumn',
        'tableRow',
        'mergeTableCells',
        'tableCellProperties',
        'tableProperties'
      ]
    }
  };
  constructor() { }

}

```

EDIT: just remembered: in ANgular v13 there is a `.angular` cache folder. Apparently this might cause trouble when tinkering with node_modules etc. So I had to clear that folder once otherwise I would get weird errors stating `... does not have 'ɵmod' property ` .

So note to self: when installing other versions and/or `git reset` or `rm -rf node_modules` also clear this folder! Just restarting `npm run start` (to ng-serve) is not enough anymore. Thanks google for speeding up things with a broken improvement.....

### ✔️ Expected result

The editor is shown. 

### ❌ Actual result
I get an error in the Javascript COnsole of Chrome and there is no CKEditor at all

```
core.mjs:6500 ERROR Error: Uncaught (in promise): TypeError: this.editor.create is not a function
TypeError: this.editor.create is not a function
    at CKEditorComponent.<anonymous> (ckeditor-ckeditor5-angular.js:254:1)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76:1
    at new ZoneAwarePromise (zone.js:1427:1)
    at __awaiter (tslib.es6.js:72:1)
    at ckeditor-ckeditor5-angular.js:252:65
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Zone.run (zone.js:134:1)
    at NgZone.runOutsideAngular (core.mjs:25517:28)
    at CKEditorComponent.<anonymous> (ckeditor-ckeditor5-angular.js:252:1)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76:1
    at new ZoneAwarePromise (zone.js:1427:1)
    at __awaiter (tslib.es6.js:72:1)
    at EditorWatchdog.creator [as _creator] (ckeditor-ckeditor5-angular.js:251:55)
```

Furthermore my HTML linter says: `Type {DecoupledDocumentEditor?: any} is not assignable to type CKEditor5.EditorConstructor ` 
when hovering above the `[editor]="ckEditorClassic"

### ❓ Possible solution

This used to work perfectly in my Angular v11 project (using CKEditor 5 , npm package version `"@ckeditor/ckeditor5-angular": "^2.0.1",` ).

However, I have no idea how to instruct NPM to install this specific version. 

## 📃 Other details

* Browser: Chrome version Version 102.0.5005.61 (Officia build) (64-bits) (DUTCH)
* OS: Linux, Ubuntu
* First affected CKEditor version: seems like version 2.0.1 worked well 
* Installed CKEditor plugins: a lot, please see config
* created my own ImageUploader plugin
* 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by martinmolema** [comment]
Ok. So a clean setup of Angular works. I created a sample project using the given custom build and put it on GitHub.
https://github.com/martinmolema/CKEditor5Angular13

I will keep looking for the differences....

**Comment by martinmolema** [comment]
So, finally found the solution. In my project there is a sub-folder with a small typescript project to help me compile ANTLR stuff and documentation. For some reason the file `tsconfig.app.json` in my Angular project said `"extends": "./otherfolder/tsconfig.json". That tsconfig.json holds some very basic config but apparently not enough. 

By the way: this probably happened when I setup this small project and MOVED the tsconfig-file instead of copying it. I noticed the tsconfig file in the root of the Angular project wasn't there anymore. Copying it from my freshly created Angular13 project (please see previous comment) solved the problem. 

Notable differences:
- problematic tsconfig file:
```json
    "target": "es2020",
    "types": [
      "node"
    ],
    "module": "commonjs",
    "lib": [
      "es2020",
      "dom",
    ]
```
(notice that the complete `angularCompilerOptions` section is missing)

- right tsconfig file
```json
"target": "es2017",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
```
and
```json
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }

```
So `angularCompilerOptions` was missing and targets are different.
