### ISSUE TITLE
[TS MVP] Enable 'translations:collect' for typescript

### ISSUE THREAD

**Issue by arkflpc** [ckeditor/ckeditor5#12029]
We're not supposed to add new translations during rewrite to TypeScript, but someday we will. Let's prepare for that and enable `yarn run translations:collect` to scan `*.ts` files as well.

**Comment by pomek** [comment]
### Story

* **Given**: I am a developer who creates plugins for CKEditor 5.
* **And**: I use TypeScript.
* **And**: I want to mark a label in the toolbar to be translated. 
* **When**: I use the `t( 'An example label' )` function in source code.
* **Then**: The tool for collecting translation strings loads the `*.ts` files.
* **And**: The tool finds the `An example label` string.

### Hints

* CKEditor 5 has an npm script (`translations:collect`) for collecting translations.
	* It executes the [`https://github.com/ckeditor/ckeditor5-dev/blob/7d97224eea25a1e153159516ddcd60ae78632014/packages/ckeditor5-dev-env/lib/index.js#L33-L35()`](https://github.com/ckeditor/ckeditor5-dev/blob/7d97224eea25a1e153159516ddcd60ae78632014/packages/ckeditor5-dev-env/lib/index.js#L33-L35) function.
* Perhaps we need to align the glob used for collecting source files. https://github.com/ckeditor/ckeditor5/blob/55d923d6d3ab01f183271c81b17495a2b59f5081/scripts/translations/utils.js#L71-L85

**Comment by pomek** [comment]
### Input:

**packages/ckeditor5-alignment/src/alignment.js**

```js
export default class Alignment extends Plugin {
	/**
	 * @inheritDoc
	 */
	static get requires() {
		return [ AlignmentEditing, AlignmentUI ];
	}

	/**
	 * @inheritDoc
	 */
	static get pluginName() {
		return 'Alignment';
	}

	init() {
		const t = editor.locale.t;

		t( 'Whatever. I am a JS file.' );
	}
}
```

**packages/ckeditor5-alignment/src/alignmentui.ts**

```ts
// Somewhere in the class.

dropdownView.buttonView.set( {
	label: t( 'Text alignment An Example' ),
	tooltip: true
} );
```

### Results:

```
Context for the message id is missing ('Whatever. I am a JS file.' from /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-alignment/src/alignment.js).
Context for the message id is missing ('Text alignment An Example' from /Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-alignment/src/alignmentui.ts).
```

After adding missing contexts as the tool suggests.

```json
{
	"Whatever. I am a JS file.": "Description for 'Whatever. I am a JS file.'",
	"Text alignment An Example": "Description for 'Text alignment An Example'",
	"Align left": "Toolbar button tooltip for aligning the text to the left.",
	"Align right": "Toolbar button tooltip for aligning the text to the right.",
	"Align center": "Toolbar button tooltip for aligning the text to center.",
	"Justify": "Toolbar button tooltip for making the text justified.",
	"Text alignment": "Dropdown button tooltip for the text alignment feature.",
	"Text alignment toolbar": "Label used by assistive technologies describing the text alignment feature toolbar."
}
```

And the generated `po` file.

```po
# Copyright (c) 2003-2022, CKSource Holding sp. z o.o. All rights reserved.

msgctxt "Description for 'Whatever. I am a JS file.'"
msgid "Whatever. I am a JS file."
msgstr "Whatever. I am a JS file."

msgctxt "Description for 'Text alignment An Example'"
msgid "Text alignment An Example"
msgstr "Text alignment An Example"

msgctxt "Toolbar button tooltip for aligning the text to the left."
msgid "Align left"
msgstr "Align left"

msgctxt "Toolbar button tooltip for aligning the text to the right."
msgid "Align right"
msgstr "Align right"

msgctxt "Toolbar button tooltip for aligning the text to center."
msgid "Align center"
msgstr "Align center"

msgctxt "Toolbar button tooltip for making the text justified."
msgid "Justify"
msgstr "Justify"

msgctxt "Dropdown button tooltip for the text alignment feature."
msgid "Text alignment"
msgstr "Text alignment"

msgctxt "Label used by assistive technologies describing the text alignment feature toolbar."
msgid "Text alignment toolbar"
msgstr "Text alignment toolbar"
```

**Comment by pomek** [comment]
Unfortunately, I must re-open the issue as it was not resolved properly. While I was testing it, I just replaced the `js` extension with `ts`, meaning that a TypeScript file exports a JavaScript code. Hence, everything worked as we expected because we were processing the JS instead of TS.

When it comes to processing a TypeScript code, it fails. `acorn` does not understand typings and throws an error.

```
$ node ./scripts/translations/collect.js
/Users/pomek/Projects/ckeditor/ckeditor5-dev/node_modules/acorn/dist/acorn.js:3464
    throw err
    ^

SyntaxError: Unexpected token (19:59)
    at Parser.pp$4.raise (/Users/pomek/Projects/ckeditor/ckeditor5-dev/node_modules/acorn/dist/acorn.js:3462:15)
    at Parser.pp$9.unexpected (/Users/pomek/Projects/ckeditor/ckeditor5-dev/node_modules/acorn/dist/acorn.js:756:10)
    at Parser.pp$9.expect (/Users/pomek/Projects/ckeditor/ckeditor5-dev/node_modules/acorn/dist/acorn.js:750:28)
    at Parser.pp$7.parseBindingList (/Users/pomek/Projects/ckeditor/ckeditor5-dev/node_modules/acorn/dist/acorn.js:2021:19)
    at Parser.pp$8.parseFunctionParams (/Users/pomek/Projects/ckeditor/ckeditor5-dev/node_modules/acorn/dist/acorn.js:1364:24)
    at Parser.pp$8.parseFunction (/Users/pomek/Projects/ckeditor/ckeditor5-dev/node_modules/acorn/dist/acorn.js:1353:10)
    at Parser.pp$8.parseExport (/Users/pomek/Projects/ckeditor/ckeditor5-dev/node_modules/acorn/dist/acorn.js:1665:33)
    at Parser.pp$8.parseStatement (/Users/pomek/Projects/ckeditor/ckeditor5-dev/node_modules/acorn/dist/acorn.js:932:76)
    at Parser.pp$8.parseTopLevel (/Users/pomek/Projects/ckeditor/ckeditor5-dev/node_modules/acorn/dist/acorn.js:813:23)
    at Parser.parse (/Users/pomek/Projects/ckeditor/ckeditor5-dev/node_modules/acorn/dist/acorn.js:585:17) {
  pos: 524,
  loc: Position { line: 19, column: 59 },
  raisedAt: 525
}
```

The mentioned line: https://github.com/ckeditor/ckeditor5/blob/f5526f9a95a45b9403ec56f766cbb974a807e7a4/packages/ckeditor5-utils/src/areconnectedthroughproperties.ts#L19

**Comment by psmyrek** [comment]
The good news is that I've improved the script for collecting translation entries to understand TypeScript files. See https://github.com/ckeditor/ckeditor5-dev/pull/780 for more details.
