### ISSUE TITLE
Uncaught CKEditorError: cannot-change-view-tree

### ISSUE THREAD

**Issue by indraraj26** [ckeditor/ckeditor5#12026]
## 📝 Provide detailed reproduction steps (if any)

1. ...
2. ... 
3. …

I am using this package with Oracle Jet. `self.connected` and `self.disconnected` these are life cycles. It is throwing below error sometime and after that editor becomes unresponsiveness and all the toolbar like bold, Italic will not work.

error:
```
Uncaught CKEditorError: cannot-change-view-tree
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-cannot-change-view-tree
    at Ra.change (ckeditor.js:6:455694)
    at Fc.listenTo.priority (ckeditor.js:6:521464)
    at $l.fire (ckeditor.js:6:318135)
    at $l._handleChangeBlock (ckeditor.js:6:587063)
    at vd._runPendingChanges (ckeditor.js:6:610822)
    at vd.change (ckeditor.js:6:607472)
    at Sp.execute (ckeditor.js:6:783299)
    at Sp.<anonymous> (ckeditor.js:6:327829)
    at Sp.fire (ckeditor.js:6:318135)
    at <computed> [as execute] (ckeditor.js:6:327881)
```

### ✔️ Expected result

It should not throw an error.

### ❌ Actual result

```
function MinHeightPlugin(editor) {
        this.editor = editor;
      }
      
MinHeightPlugin.prototype.init = function() {
const minHeight = this.editor.config.get('minHeight');
   this.editor.ui.view.editable.extendTemplate({
      attributes: {
            style: {
              minHeight
            }
     }
 });
};

const candidateEditorDataChanged = () => {
        const data = candidateEditor.getData();
        self.properties.noteToCandidate = data;
      }

// This is lifecycle which will emit when viewModel/Dom is ready
self.connected = () => {
        ClassicEditor.builtinPlugins.push(MinHeightPlugin);
        ClassicEditor
          .create( document.querySelector( '#editor1' ), {
            toolbar: [ 'heading', '|', 'bold', 'italic', '|', 'bulletedList', 
            'numberedList',  'blockQuote', '|', 'undo', 'redo',
            ],
            minHeight: '300px'
          }
             )
          .then((editor) => {
            candidateEditor = editor;
            editor.setData(self.properties.noteToCandidate)
            editor.model.document.on( 'change:data',  candidateEditorDataChanged);
          })
          .catch( error => { 
              console.error( error );
          } );
}

 self.disconnected = () => {
        candidateEditor.model.document.off('change:data', candidateEditorDataChanged);
 }
```

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: Chrome Latest One
* OS: Windows 11
* First affected CKEditor version:  "@ckeditor/ckeditor5-build-classic": "^34.2.0"
* Installed CKEditor plugins: 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by indraraj26** [comment]
This is also possible in sample. 

Step 1: type something very fast in editor 
Step 2: toggle from bold to italic
Step 3: repeat step 1 and 2.

![image](https://user-images.githubusercontent.com/23274631/177720377-5521b90f-f1a7-40c9-bba8-1bd7247d4f98.png)

**Comment by FilipTokarski** [comment]
Hi, I'm not able to reproduce this. Could you add a screencast showing exactly what you do and when the error occurs?

**Comment by indraraj26** [comment]
Hi @FilipTokarski , 

Let me know if you still have any doubts, We can jump on a Zoom call. 

Reproduce Steps:

Step 1: type something very fast and remove half word in the editor and instantly apply bold or switch to italic
Step 2: repeat step 1



Thank you

**Comment by FilipTokarski** [comment]
Can you reproduce this also on [docs demo](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html) or only in your customised editor?

**Comment by indraraj26** [comment]
Hi @FilipTokarski ,

The cast or reproducible you see, It was of sample which comes with ckeditor package . Also it is reproducible on docs demo too.

Reproduce Steps:

Step 1: type something very fast and remove half word in the editor and instantly apply bold or switch to italic
Step 2: repeat step 1

![image](https://user-images.githubusercontent.com/23274631/178496196-6003f7bf-c1c6-4f72-a91e-09030bdab075.png)

**Comment by dufipl** [comment]
Hello @indraraj26,
We were able to create simplified reproduction steps and reproduce the issue.

## Steps
1. Open this demo: https://ckeditor.com/docs/ckeditor5/34.2.0/examples/builds/document-editor.html
2. Delete all contents and create a paragraph with e.g. "AAA" inside of it
3. Put the cursor after the text
4. Change the font
5. Try to select the text

![selection error](https://user-images.githubusercontent.com/32898551/178709867-22387dac-a8d7-4fb5-9299-59cb0c63410b.gif)

Therefore, we can confirm the issue.
**Also, it is a regression introduced by version 34.2.0`.**
cc @Reinmar

**Comment by FilipTokarski** [comment]
Bisection shows this commit: https://github.com/ckeditor/ckeditor5/commit/22b97e9ad3067a74cbad21130f39b2fc911e82c5

**Comment by Reinmar** [comment]
> Bisection shows this commit: [22b97e9](https://github.com/ckeditor/ckeditor5/commit/22b97e9ad3067a74cbad21130f39b2fc911e82c5)

It was a fix for https://github.com/ckeditor/ckeditor5/issues/11472.
