### ISSUE TITLE
[Android/IME] Enter after the word in the middle of the heading paragraph causes an error in the console and the word disappears in GBoard

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor5#12391]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to the all features manual test.
2.  Try to enter a new line using the English GBoard keyboard after the end of some Heading 1 paragraph

### ✔️ Expected result

Enter possible

### ❌ Actual result

Enter works but deletes text and causes an error:

![enter disapper ime](https://user-images.githubusercontent.com/32898551/187881926-56b2ee3c-041a-42e7-b504-7a5bafb966fc.gif)

```
Uncaught DOMException: Failed to execute 'collapse' on 'Selection': The offset 6 is larger than the node's length (5).
    at Renderer._updateDomSelection (http://192.168.0.137:8125/ckeditor5/tests/manual/all-features.js:22407:22)
    at Renderer._updateSelection (http://192.168.0.137:8125/ckeditor5/tests/manual/all-features.js:22353:18)
    at Renderer.render (http://192.168.0.137:8125/ckeditor5/tests/manual/all-features.js:21900:14)
    at Renderer.<anonymous> (http://192.168.0.137:8125/ckeditor5/tests/manual/all-features.js:21737:22)
    at Renderer.fire (http://192.168.0.137:8125/ckeditor5/tests/manual/all-features.js:1526:47)
    at Renderer.set [as isComposing] (http://192.168.0.137:8125/ckeditor5/tests/manual/all-features.js:827:30)
    at updateBoundObservableProperty (http://192.168.0.137:8125/ckeditor5/tests/manual/all-features.js:1320:34)
    at http://192.168.0.137:8125/ckeditor5/tests/manual/all-features.js:1346:25
    at Set.forEach (<anonymous>)
    at Mixin.<anonymous> (http://192.168.0.137:8125/ckeditor5/tests/manual/all-features.js:1345:30)
```

## 📃 Other details

Branch: `ck/11438-beforeinput-ime-research-vol1.1-android`  
Language: English
Keyboards: Tested on  GBoard
Device: Pixel C emulator@Android v13 (API 33)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by dufipl** [comment]
When enter is pressed in the middle of the word after some words have already disappeared, they show up again as nothing happened: 
![enter mid word ime](https://user-images.githubusercontent.com/32898551/187884459-1dbf1d21-8cce-4fbe-910d-eece1a35d571.gif)

**Comment by Reinmar** [comment]
This issue may be related to ckeditor/ckeditor5#12368 (and the rest of the Enter problems).

**Comment by Acrophost** [comment]
Doesn't persist after fixes on `ck/11438-beforeinput-ime-research-vol1.1-android`
