### ISSUE TITLE
DLL: An import of module using debug flags may finish with unexpected error

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#12791]
## 📝 Provide detailed reproduction steps (if any)

The issue it's a follow-up of https://github.com/ckeditor/ckeditor5/issues/12479.

* The `TableWalker` class requires `CKEditorError` via debug flags.
	https://github.com/ckeditor/ckeditor5/blob/5603fd512e360daf46312fd09d9e6c4edec80a02/packages/ckeditor5-table/src/tablewalker.js#L10
* For the `ckeditor5-table` package, rebuild DLL in development mode:
	* `cd packages/ckeditor5-table/ && yarn run dll:build --mode=development && cd ../../`
	* When building in production mode, all inline comments are removed.
* Start the manual test server: `yarn run manual -f ckeditor5/all-features-dll --no-dll`.

### ✔️ Expected result

* No errors. Everything should work fine.

### ❌ Actual result

* The duplicated modules error occurs.

### ❓ Possible solution

* In the debug mode, additional imports might be enabled.
* Webpack resolves these imports using a file system.
	* It's fine for _normal_ tests.
* DLL imports should be resolved via `CKEditor5.dll()` function.
	* Otherwise, webpack imports `ckeditor5-utils` twice: from the core DLL and the "dynamic" import.
* We need to include the `webpack.DllReferencePlugin` plugin when processing DLLs.

**Comment by pomek** [comment]
Invalid:

```
Uncaught CKEditorError: ckeditor-duplicated-modules
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-ckeditor-duplicated-modules
    at Array.<anonymous> (version.ts:156:1)
    at __webpack_require__ (bootstrap:19:1)
    at Array.<anonymous> (mix.ts:56:1)
    at __webpack_require__ (bootstrap:19:1)
    at Array.<anonymous> (utils.ts:12:1)
    at __webpack_require__ (bootstrap:19:1)
    at Array.<anonymous> (table.js:19186:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/tablewalker.js (table.js:15294:1)
    at __nested_webpack_require_736652__ (table.js:19041:1)
```

![Uploading image.png…]()
