### ISSUE TITLE
The `serveTranslations()` function throws when using the linked package

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#12887]
## 📝 Provide detailed reproduction steps (if any)

* Clone [CKEditor 5 Dev](https://github.com/ckeditor/ckeditor5-dev).
* Create a link to the `ckeditor5-dev-webpack-plugin` package.
* Link the package in CKEditor 5.
* Execute a command that uses webpack, e.g., build the documentation (`yarn run docs`) or rebuild the core DLL build (`yarn webpack --config=scripts/dll/webpack.config.dll.js`).

### ✔️ Expected result

No error.

### ❌ Actual result

```
[webpack-cli] TypeError: The 'compilation' argument must be an instance of Compilation
    at NormalModule.getCompilationHooks (/Users/pomek/Projects/ckeditor/ckeditor5-dev/node_modules/webpack/lib/NormalModule.js:227:10)
    at getCompilationHooks (/Users/pomek/Projects/ckeditor/ckeditor5-dev/packages/ckeditor5-dev-webpack-plugin/lib/servetranslations.js:209:22)
    at /Users/pomek/Projects/ckeditor/ckeditor5-dev/packages/ckeditor5-dev-webpack-plugin/lib/servetranslations.js:97:3
    at Hook.eval [as call] (eval at create (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/webpack/lib/Compiler.js:1122:26)
    at /Users/pomek/Projects/ckeditor/ckeditor5/node_modules/webpack/lib/Compiler.js:1166:29
    at Hook.eval [as callAsync] (eval at create (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/webpack/lib/Compiler.js:1161:28)
```

### ❓ Possible solution

Try to get an instance of compilation hooks from webpack instead of creating it manually.

https://github.com/ckeditor/ckeditor5-dev/blob/3a3a58f4f0dbdcef9e6c16b6370c72c93e9c426e/packages/ckeditor5-dev-webpack-plugin/lib/servetranslations.js#L209

**Comment by jotapardo** [comment]
So, what is the solution? I got this error:

```
2:11:46 AM:  ERROR  TypeError: Cannot read properties of undefined (reading 'version')
2:11:46 AM: TypeError: Cannot read properties of undefined (reading 'version')
2:11:46 AM:     at getCompilationHooks (/opt/build/repo/node_modules/@ckeditor/ckeditor5-dev-webpack-plugin/lib/servetranslations.js:206:29)
2:11:46 AM:     at /opt/build/repo/node_modules/@ckeditor/ckeditor5-dev-webpack-plugin/lib/servetranslations.js:95:3
2:11:46 AM:     at SyncHook.eval [as call] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:21:1)
2:11:46 AM:     at SyncHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
2:11:46 AM:     at Compiler.newCompilation (/opt/build/repo/node_modules/webpack/lib/Compiler.js:631:26)
2:11:46 AM:     at /opt/build/repo/node_modules/webpack/lib/Compiler.js:667:29
2:11:46 AM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
2:11:46 AM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
2:11:46 AM:     at Compiler.compile (/opt/build/repo/node_modules/webpack/lib/Compiler.js:662:28)
2:11:46 AM:     at /opt/build/repo/node_modules/webpack/lib/Compiler.js:321:11
2:11:46 AM:     at Compiler.readRecords (/opt/build/repo/node_modules/webpack/lib/Compiler.js:529:11)
2:11:46 AM:     at /opt/build/repo/node_modules/webpack/lib/Compiler.js:318:10
2:11:46 AM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
2:11:46 AM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
2:11:46 AM:     at /opt/build/repo/node_modules/webpack/lib/Compiler.js:315:19
2:11:46 AM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
2:11:46 AM: ​
2:11:46 AM: ────────────────────────────────────────────────────────────────
2:11:46 AM:   "build.command" failed                                        
2:11:46 AM: ────────────────────────────────────────────────────────────────
```

**Comment by jotapardo** [comment]
I installed the last version 31.1.11, then I run npm i and npm run serve... Now I got the error but in local 

```
INFO  Starting development server...
0% compiling ERROR  TypeError: Cannot read property 'version' of undefined
TypeError: Cannot read property 'version' of undefined
    at getCompilationHooks (...\node_modules\@ckeditor\ckeditor5-dev-webpack-plugin\lib\servetranslations.js:206:29)
    at ...\node_modules\@ckeditor\ckeditor5-dev-webpack-plugin\lib\servetranslations.js:95:3
    at SyncHook.eval [as call] (eval at create (...\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:21:1)
    at SyncHook.lazyCompileHook (...\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (...\node_modules\webpack\lib\Compiler.js:631:26)
    at ...\node_modules\webpack\lib\Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (...\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (...\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.compile (...\node_modules\webpack\lib\Compiler.js:662:28)
    at ...\node_modules\webpack\lib\Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (...\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook ...\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._go (...\node_modules\webpack\lib\Watching.js:41:32)
    at ...\node_modules\webpack\lib\Watching.js:33:9
    at Compiler.readRecords (...\node_modules\webpack\lib\Compiler.js:529:11)
    at new Watching (...\node_modules\webpack\lib\Watching.js:30:17)
```

**Comment by jotapardo** [comment]
> @jotapardo, do you use webpack 4 in your project?

"webpack": "^4.46.0"

**Comment by pomek** [comment]
Thanks. I will push a fix for the problem tomorrow. So far, I recommend using the [`v31.1.9`](https://github.com/ckeditor/ckeditor5-dev/releases/tag/v31.1.9) version.

**Comment by jotapardo** [comment]
In local is working, deploying is not. Should I use webpack 5?

4:06:18 PM: ────────────────────────────────────────────────────────────────
4:06:18 PM:   1. Build command from Netlify app                             
4:06:18 PM: ────────────────────────────────────────────────────────────────
4:06:18 PM: ​
4:06:18 PM: $ npm run build
4:06:18 PM: > XXX
4:06:18 PM: > vue-cli-service build
4:06:19 PM: Browserslist: caniuse-lite is outdated. Please run:
4:06:19 PM:   npx browserslist@latest --update-db
4:06:19 PM:   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
4:06:19 PM: -  Building for production...
4:06:21 PM:  ERROR  TypeError: Cannot read properties of undefined (reading 'version')
4:06:21 PM: TypeError: Cannot read properties of undefined (reading 'version')
4:06:21 PM:     at getCompilationHooks (/opt/build/repo/node_modules/@ckeditor/ckeditor5-dev-webpack-plugin/lib/servetranslations.js:206:29)
4:06:21 PM:     at /opt/build/repo/node_modules/@ckeditor/ckeditor5-dev-webpack-plugin/lib/servetranslations.js:95:3
4:06:21 PM:     at SyncHook.eval [as call] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:21:1)
4:06:21 PM:     at SyncHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
4:06:21 PM:     at Compiler.newCompilation (/opt/build/repo/node_modules/webpack/lib/Compiler.js:631:26)
4:06:21 PM:     at /opt/build/repo/node_modules/webpack/lib/Compiler.js:667:29
4:06:21 PM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
4:06:21 PM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
4:06:21 PM:     at Compiler.compile (/opt/build/repo/node_modules/webpack/lib/Compiler.js:662:28)
4:06:21 PM:     at /opt/build/repo/node_modules/webpack/lib/Compiler.js:321:11
4:06:21 PM:     at Compiler.readRecords (/opt/build/repo/node_modules/webpack/lib/Compiler.js:529:11)
4:06:21 PM:     at /opt/build/repo/node_modules/webpack/lib/Compiler.js:318:10
4:06:21 PM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
4:06:21 PM:     at AsyncSeriesHook.lazyCompileHook (/opt/build/repo/node_modules/tapable/lib/Hook.js:154:20)
4:06:21 PM:     at /opt/build/repo/node_modules/webpack/lib/Compiler.js:315:19
4:06:21 PM:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
4:06:21 PM: ​
4:06:21 PM: ────────────────────────────────────────────────────────────────
4:06:21 PM:   "build.command" failed                                        
4:06:21 PM: ────────────────────────────────────────────────────────────────

**Comment by pomek** [comment]
The fix is ready – https://github.com/ckeditor/ckeditor5-dev/pull/817 – but it needs to be confirmed by someone else. Hence, I suggest using the latest working version. We will review the PR tomorrow and then release it.

**Comment by jotapardo** [comment]
Perfect, Got it! I'll be waiting for that

**Comment by pomek** [comment]
=> https://github.com/ckeditor/ckeditor5-dev/releases/tag/v31.1.12.

**Comment by jotapardo** [comment]
@pomek last version was successful with version v31.1.12. Thank you a lot!

However I just want you share with you this warning alert:

```
7:31:26 PM: warning "@ckeditor/ckeditor5-dev-utils > ts-loader@9.4.1" has unmet peer dependency "typescript@*".
7:31:26 PM: warning "@ckeditor/ckeditor5-dev-utils > ts-loader@9.4.1" has incorrect peer dependency "webpack@^5.0.0".
```

As I shared with you I'm using `"webpack": "^4.46.0".` **It has incorrect peer dependency "webpack@^5.0.0".**


```
 "devDependencies": {
    "@ckeditor/ckeditor5-dev-utils": "^31.1.12",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^31.1.12",
    "@vue/cli-plugin-babel": "^4.5.10",
    "@vue/cli-plugin-eslint": "^4.5.10",
    "@vue/cli-service": "^4.5.10",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "copy-webpack-plugin": "^6.4.1",
    "eslint": "^7.32.0",
    "eslint-plugin-vue": "^6.2.2",
    "node-sass": "^6.0.0",
    "postcss": "^8.4.18",
    "sass-loader": "^10.1.1",
    "vue-loader": "^15.9.6",
    "vue-template-compiler": "^2.6.12",
    "webpack": "^4.46.0"
  },

```
Log of last deployment:

```
7:31:11 PM: [1/4] Resolving packages...
7:31:23 PM: [2/4] Fetching packages...
7:31:26 PM: [3/4] Linking dependencies...
7:31:26 PM: warning " > bootstrap@4.6.1" has unmet peer dependency "popper.js@^1.16.1".
7:31:26 PM: warning " > v-calendar@2.4.1" has unmet peer dependency "@popperjs/core@^2.4.0".
7:31:26 PM: warning " > vue-cropperjs@5.0.0" has incorrect peer dependency "vue@>=3.0.0".
7:31:26 PM: warning " > vue-instantsearch@4.3.3" has unmet peer dependency "algoliasearch@>= 3.32.0 < 5".
7:31:26 PM: warning "vue-instantsearch > instantsearch.js@4.40.4" has unmet peer dependency "algoliasearch@>= 3.1 < 5".
7:31:26 PM: warning "vue-instantsearch > instantsearch.js > algoliasearch-helper@3.8.2" has unmet peer dependency "algoliasearch@>= 3.1 < 5".
7:31:26 PM: warning "@ckeditor/ckeditor5-dev-utils > ts-loader@9.4.1" has unmet peer dependency "typescript@*".
7:31:26 PM: warning "@ckeditor/ckeditor5-dev-utils > ts-loader@9.4.1" has incorrect peer dependency "webpack@^5.0.0".
7:31:26 PM: warning " > @vue/cli-plugin-eslint@4.5.17" has incorrect peer dependency "eslint@>= 1.6.0 < 7.0.0".
7:31:26 PM: warning "@vue/cli-plugin-eslint > eslint-loader@2.2.1" has incorrect peer dependency "eslint@>=1.6.0 <7.0.0".
7:31:26 PM: warning " > vue-loader@15.9.8" has unmet peer dependency "css-loader@*".
7:31:26 PM: warning " > @vue/eslint-config-prettier@6.0.0" has unmet peer dependency "eslint-plugin-prettier@^3.1.0".
7:31:26 PM: warning " > @vue/eslint-config-prettier@6.0.0" has unmet peer dependency "prettier@>= 1.13.0".
7:31:26 PM: warning " > eslint-plugin-vue@6.2.2" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
7:31:30 PM: [4/4] Building fresh packages...
7:31:30 PM: success Saved lockfile.
7:31:30 PM: Done in 18.88s.
7:31:30 PM: NPM modules installed using Yarn
7:31:30 PM: Started restoring cached go cache
7:31:30 PM: Finished restoring cached go cache
7:31:30 PM: Installing Go version 1.17 (requested 1.17)
7:31:34 PM: unset GOOS;
7:31:34 PM: unset GOARCH;
7:31:34 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.17.linux.amd64';
7:31:34 PM: export PATH="/opt/buildhome/.gimme/versions/go1.17.linux.amd64/bin:${PATH}";
7:31:34 PM: go version >&2;
7:31:34 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.17.linux.amd64.env"
7:31:34 PM: go version go1.17 linux/amd64
7:31:34 PM: Detected 1 framework(s)
7:31:34 PM: "vue" at version "4.5.17"
7:31:34 PM: Installing missing commands
7:31:34 PM: Verify run directory
```
