### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'getAttribute') in React

### ISSUE THREAD

**Issue by MohammadAbdorrahmani** [ckeditor/ckeditor5#13309]
## 📝 Provide detailed reproduction steps (if any)
This is my code:(This code is in CKEditor Documentation) CKEditor 5
```
import React, { Component } from 'react';
import { CKEditor, CKEditorContext } from '@ckeditor/ckeditor5-react';
import Context from '@ckeditor/ckeditor5-core/src/context';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';
import {Autoformat} from "@ckeditor/ckeditor5-autoformat";
import AutoImage from '@ckeditor/ckeditor5-image/src/autoimage';
import AutoLink from '@ckeditor/ckeditor5-link/src/autolink';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import Code from '@ckeditor/ckeditor5-basic-styles/src/code';
import CodeBlock from '@ckeditor/ckeditor5-code-block/src/codeblock';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import FindAndReplace from '@ckeditor/ckeditor5-find-and-replace/src/findandreplace';
import Font from '@ckeditor/ckeditor5-font/src/font';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Highlight from '@ckeditor/ckeditor5-highlight/src/highlight';
import HorizontalLine from '@ckeditor/ckeditor5-horizontal-line/src/horizontalline';
import HtmlEmbed from '@ckeditor/ckeditor5-html-embed/src/htmlembed';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageInsert from '@ckeditor/ckeditor5-image/src/imageinsert';
import ImageResize from '@ckeditor/ckeditor5-image/src/imageresize';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Link from '@ckeditor/ckeditor5-link/src/link';
import LinkImage from '@ckeditor/ckeditor5-link/src/linkimage';
import List from '@ckeditor/ckeditor5-list/src/list';
import ListProperties from '@ckeditor/ckeditor5-list/src/listproperties';
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed';
import PageBreak from '@ckeditor/ckeditor5-page-break/src/pagebreak';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import PictureEditing from '@ckeditor/ckeditor5-image/src/pictureediting';
import RemoveFormat from '@ckeditor/ckeditor5-remove-format/src/removeformat';
import SourceEditing from '@ckeditor/ckeditor5-source-editing/src/sourceediting';
import SpecialCharacters from '@ckeditor/ckeditor5-special-characters/src/specialcharacters';
import SpecialCharactersEssentials from '@ckeditor/ckeditor5-special-characters/src/specialcharactersessentials';
import Strikethrough from '@ckeditor/ckeditor5-basic-styles/src/strikethrough';
import Subscript from '@ckeditor/ckeditor5-basic-styles/src/subscript';
import Superscript from '@ckeditor/ckeditor5-basic-styles/src/superscript';
import Table from '@ckeditor/ckeditor5-table/src/table';
import TableCaption from '@ckeditor/ckeditor5-table/src/tablecaption';
import TableCellProperties from '@ckeditor/ckeditor5-table/src/tablecellproperties';
import TableColumnResize from '@ckeditor/ckeditor5-table/src/tablecolumnresize';
import TableProperties from '@ckeditor/ckeditor5-table/src/tableproperties';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar';
import TextPartLanguage from '@ckeditor/ckeditor5-language/src/textpartlanguage';
import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation';
import TodoList from '@ckeditor/ckeditor5-list/src/todolist';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
export default class Editor extends Component {
    render() {
        return (
            <div className="App">
                <CKEditorContext context={ Context }>
                    <CKEditor
                        editor={ ClassicEditor }
                        config={{
                            plugins: [Autoformat, BlockQuote, Bold, Heading, Image, ImageCaption,
                                ImageStyle, ImageToolbar, Indent, Italic, Link, List, MediaEmbed,
                                Paragraph, Table, TableToolbar, Alignment, AutoImage, AutoLink, Code, CodeBlock, Essentials, FindAndReplace, Font, Highlight, HorizontalLine,
                                HtmlEmbed, ImageInsert, ImageResize, ImageUpload, IndentBlock,
                                LinkImage, ListProperties, PageBreak,
                                PictureEditing, RemoveFormat, SourceEditing, SpecialCharacters,
                                SpecialCharactersEssentials, Strikethrough, Subscript, Superscript,
                                TableCaption, TableCellProperties, TableColumnResize, TableProperties,
                                TextPartLanguage, TextTransformation, TodoList, Underline
                            ],
                            toolbar: {
                            items: [
                            'undo', 'redo',
                            '|',
                             'findAndReplace', 'selectAll',
                            '|',
                            'heading',
                            '|',
                            'removeFormat', 'bold', 'italic', 'strikethrough', 'underline', 'code', 'subscript', 'superscript',
                            '|',
                            'specialCharacters', 'horizontalLine', 'pageBreak',
                            '|',
                            '-',
                            'highlight', 'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor',
                            '|',
                            'link', 'blockQuote', 'insertTable', 'uploadImage', 'mediaEmbed', 'codeBlock', 'htmlEmbed',
                            '|',
                            'bulletedList', 'numberedList', 'todoList',
                            '|',
                            'outdent', 'indent', 'alignment',
                            '|',
                            'textPartLanguage',
                            '|',
                            'sourceEditing'
                            ],
                            shouldNotGroupWhenFull: true
                            },
                            fontFamily: {
                                supportAllValues: true
                            },
                            fontSize: {
                                options: [ 10, 12, 14, 'default', 18, 20, 22 ],
                                supportAllValues: true
                            },
                            htmlEmbed: {
                                showPreviews: true
                            },
                            image: {
                                styles: [
                                    'alignCenter',
                                    'alignLeft',
                                    'alignRight'
                                ],
                                resizeOptions: [
                                    {
                                        name: 'resizeImage:original',
                                        label: 'Original',
                                        value: null
                                    },
                                    {
                                        name: 'resizeImage:50',
                                        label: '50%',
                                        value: '50'
                                    },
                                    {
                                        name: 'resizeImage:75',
                                        label: '75%',
                                        value: '75'
                                    }],
                                toolbar: [
                                    'imageTextAlternative', 'toggleImageCaption', '|',
                                    'imageStyle:inline', 'imageStyle:wrapText', 'imageStyle:breakText', 'imageStyle:side', '|',
                                    'resizeImage'
                                ],
                                insert: {
                                    integrations: [
                                        'insertImageViaUrl'
                                    ]
                                }},
                            list: {
                                properties: {
                                    styles: true,
                                    startIndex: true,
                                    reversed: true
                                }
                            },
                            link: {
                                decorators: {
                                    addTargetToExternalLinks: true,
                                    defaultProtocol: 'https://',
                                    toggleDownloadable: {
                                        mode: 'manual',
                                        label: 'Downloadable',
                                        attributes: {
                                            download: 'file'
                                        }
                                    }
                                }
                            },
                            placeholder: 'Type or paste your content here!',
                            table: {
                                contentToolbar: [
                                    'tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties', 'toggleTableCaption'
                                ]
                            },


                    }}
                        onReady={ editor => {
                            // You can store the "editor" and use when it is needed.
                            console.log( 'Editor1 is ready to use!', editor );
                        } }
                        data="<p>Hello from the first editor working with the context!</p>"

                    />
                </CKEditorContext>
            </div>
        );
    }
}

```
###❌ Actual result
and Error:
```
TypeError: Cannot read properties of null (reading 'getAttribute')
    at IconView._updateXMLContent (iconview.js:112:33)
    at IconView.render (iconview.js:91:14)
    at IconView.<anonymous> (observablemixin.js:181:45)
    at IconView.fire (emittermixin.js:146:47)
    at <computed> [as render] (observablemixin.js:184:29)
    at ViewCollection._renderViewIntoCollectionParent (viewcollection.js:186:18)
    at ViewCollection.<anonymous> (viewcollection.js:60:18)
    at ViewCollection.fire (emittermixin.js:146:47)
    at ViewCollection.addMany (collection.js:106:18)
    at ViewCollection.add (collection.js:75:21)
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mabryl** [comment]
Hi @MohammadAbdorrahmani,

Thank you for reaching out.

The error that you observe is most commonly linked to an incorrect webpack configuration in your project.

Please make sure that you're following [this section](https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/react.html#modifying-the-webpack-configuration) of our React integration guide closely.

Also, I'm attaching a `.txt` file containing a proper webpack configuration prepared in accordance with the article above. Compare it to your `webpack.config.js` file and see if you can spot any differences.

[webpack.config.txt](https://github.com/ckeditor/ckeditor5/files/10569143/webpack.config.txt)

**Comment by MohammadAbdorrahmani** [comment]
Hello, thank you for your help and for answering my question. I fixed it. Thanks again
