### ISSUE TITLE
Typedoc - the `tag-event` can't get the event parameters and throws an error

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5#13376]
## 📝 Provide detailed reproduction steps (if any)

After https://github.com/ckeditor/ckeditor5/pull/13274 has been merged, building the API docs for TypeScript throws an error:

```
TypeError: Cannot read properties of undefined (reading 'children')
    at getArgsTuple (D:\Projekty\ckeditor5\node_modules\@ckeditor\typedoc-plugins\lib\tag-event\index.js:165:35)
    at Converter.onEventEnd (D:\Projekty\ckeditor5\node_modules\@ckeditor\typedoc-plugins\lib\tag-event\index.js:102:26)
    at triggerEvents (D:\Projekty\ckeditor5\node_modules\typedoc\dist\lib\utils\events.js:191:43)
    at triggerApi (D:\Projekty\ckeditor5\node_modules\typedoc\dist\lib\utils\events.js:167:13)
    at eventsApi (D:\Projekty\ckeditor5\node_modules\typedoc\dist\lib\utils\events.js:60:18)
    at Converter.trigger (D:\Projekty\ckeditor5\node_modules\typedoc\dist\lib\utils\events.js:389:13)
    at Converter.convert (D:\Projekty\ckeditor5\node_modules\typedoc\dist\lib\converter\converter.js:74:14)
    at Application.convert (D:\Projekty\ckeditor5\node_modules\typedoc\dist\lib\application.js:155:40)
    at build (D:\Projekty\ckeditor5\node_modules\@ckeditor\ckeditor5-dev-docs\lib\buildtypedoc.js:70:35)
```

The event that triggers this error:
https://github.com/ckeditor/ckeditor5/blob/9496e5e7b66f5043ae4aded4748e12c1e6ad15c3/packages/ckeditor5-engine/src/view/observer/arrowkeysobserver.ts#L49-L64

### ✔️ Expected result

Building the API docs works fine without errors.

### ❌ Actual result

Building the API docs throws an error.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
https://github.com/ckeditor/ckeditor5/blob/9496e5e7b66f5043ae4aded4748e12c1e6ad15c3/packages/ckeditor5-ckbox/src/ckboxcommand.ts#L416-L424

This line also ends with an error when it is exported (and it should be to detect the `@eventName` annotation).
