### ISSUE TITLE
Checking coverage does not work

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#13529]
## 📝 Provide detailed reproduction steps (if any)

In the CKEditor 5 root directory, execute tests with the coverage flag.

```
yarn test -b ChromeHeadless -f autoformat -c
```

### ✔️ Expected result

No errors in the generated report.

### ❌ Actual result

```
Unable to lookup source: /Users/pomek/Projects/ckeditor/ckeditor5/external/ckeditor5-dev/packages/ckeditor5-dev-tests/lib/utils/ck-debug-loader.js??ruleSet[1].rules[5].use[1]!/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-autoformat/src/autoformat.ts (ENOENT: no such file or directory, open '/Users/pomek/Projects/ckeditor/ckeditor5/external/ckeditor5-dev/packages/ckeditor5-dev-tests/lib/utils/ck-debug-loader.js??ruleSet[1].rules[5].use[1]!/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-autoformat/src/autoformat.ts')
Error: Unable to lookup source: /Users/pomek/Projects/ckeditor/ckeditor5/external/ckeditor5-dev/packages/ckeditor5-dev-tests/lib/utils/ck-debug-loader.js??ruleSet[1].rules[5].use[1]!/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-autoformat/src/autoformat.ts (ENOENT: no such file or directory, open '/Users/pomek/Projects/ckeditor/ckeditor5/external/ckeditor5-dev/packages/ckeditor5-dev-tests/lib/utils/ck-debug-loader.js??ruleSet[1].rules[5].use[1]!/Users/pomek/Projects/ckeditor/ckeditor5/packages/ckeditor5-autoformat/src/autoformat.ts')
    at Context.defaultSourceLookup [as sourceFinder] (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/istanbul-lib-report/lib/context.js:17:15)
    at Context.getSource (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/istanbul-lib-report/lib/context.js:71:21)
    at annotateSourceCode (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/istanbul-reports/lib/html/annotator.js:249:40)
```

![image](https://user-images.githubusercontent.com/2270764/220883382-08d3eb8b-82ce-473c-a2fb-201736659b58.png)

### ❓ Possible solution

Perhaps a regression was introduced in #13381.

**Comment by pomek** [comment]
I am reopening the issue as the proposed fix (https://github.com/ckeditor/ckeditor5-dev/pull/843) is not valid. It breaks the CI (#13569).

**Comment by pomek** [comment]
Decision: We plan to remove the `ck-debug-loader` from automated tests. Unfortunately, it impacts the CKEditor 5 tests, so we must fix them first.
