### ISSUE TITLE
build-dlls.js should check if package.json exists in folders

### ISSUE THREAD

**Issue by przemyslaw-zan** [ckeditor/ckeditor5#13692]
`build-dlls.js` should check if package.json exists in folders as without this, when empty folders are left by git, the build errors will occur as shown below (the `ckeditor5-format-painter` dir existed and was empty).

## Reproduction steps

1. Create a branch and add new package to that branch
2. Create `package.json` with dependencies
3. Commit
4. `yarn install`
  _There should be `node_modules` inside the new package_
5. Checkout `master`.
6. `yarn run manual --dll`

### ✔️ Expected result

Script works properly

### ❌ Actual result

```
pzan2@DESKTOP-TR1P40Q  /d/Repo/ckeditor5 (master)
$ yarn run manual --dll
yarn run v1.22.19
$ node --max_old_space_size=8192 node_modules/@ckeditor/ckeditor5-dev-tests/bin/testmanual.js --tsconfig ./tsconfig.test.json --dll

📍 Building DLLs in ckeditor5...

$ npm run build

> ckeditor5@36.0.1 build
> tsc -p ./tsconfig.release-ckeditor5.json

$ node ./scripts/dll/build-dlls.js --base-dll-config ./scripts/dll/webpack.config.dll.js
Creating the base DLL build...
Creating DLL-compatible package builds...
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'D:\Repo\ckeditor5\packages\ckeditor5-bbb\package.json'
Require stack:
- D:\Repo\ckeditor5\scripts\dll\build-dlls.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at hasDLLBuildScript (D:\Repo\ckeditor5\scripts\dll\build-dlls.js:99:18)
    at Array.filter (<anonymous>)
    at Object.<anonymous> (D:\Repo\ckeditor5\scripts\dll\build-dlls.js:50:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\Repo\\ckeditor5\\scripts\\dll\\build-dlls.js' ]
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Building DLLs in ckeditor5 finished with an error.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### ❓ Possible solution

This function should check whether `package.json` exists:
https://github.com/ckeditor/ckeditor5/blob/a78651cd9e413aef2748ea86a6dc5687a963924e/scripts/dll/build-dlls.js#L91-L96

**Comment by przemyslaw-zan** [comment]
Bonus point: create a post-checkout husky hook that removes a package if it does not contain any content.
