### ISSUE TITLE
Editor crashes if the attribute name is a number

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#13841]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to https://ckeditor.com/docs/ckeditor5/37.0.1/features/html/general-html-support.html.
2.  Execute `editor.setData('<p><foo 200="test">test</foo></p>')`.

### ❌ Actual result

_The editor crashes._

```
snippet.js:4 Uncaught Error: Failed to execute 'setAttribute' on 'Element': '200' is not a valid attribute name.
    at na.setDomElementAttribute (snippet.js:4:121865)
    at na.viewToDom (snippet.js:4:121421)
    at na.viewChildrenToDom (snippet.js:4:122402)
    at viewChildrenToDom.next (<anonymous>)
    at na.viewToDom (snippet.js:4:121502)
    at Pc.toData (snippet.js:4:234200)
    at model (snippet.js:4:568008)
    at snippet.js:4:214567
    at Tc.<anonymous> (snippet.js:4:214600)
    at Tc.fire (snippet.js:4:5713)
```

## 📃 Other details

*   It crashes also after pasting the content.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by arkflpc** [comment]
Actually, it can fail whenever the attribute name starts with non-letter. In example (in Firefox and Chrome):

```
// Both fail:
element.setAttribute('2x', 'abc')
element.setAttribute('-x', 'abc')

// Both seem to be accepted by browsers:
element.setAttribute('x2', 'abc')
element.setAttribute('x-', 'abc')
```
