### ISSUE TITLE
Undoing pasting the same content with list multiple times throws error

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1385]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

latest master @ Chrome

## 📋 Steps to reproduce

1. Select some content that contains a list
1. Paste it <kbd>ctrl</kbd> + <kbd>v</kbd>
1. Select all content <kbd>ctrl</kbd> + <kbd>a</kbd> and paste the content again <kbd>ctrl</kbd> + <kbd>v</kbd>
1. Place caret somewhere in the content and paste again  <kbd>ctrl</kbd> + <kbd>v</kbd>
1. Undo
1. Undo

## ✅ Expected result

The undo is applied.

## ❎ Actual result

Error in the console.

## 📃 Other details that might be useful

![peek 2018-11-30 10-51](https://user-images.githubusercontent.com/247363/49281895-0e76cc00-f48e-11e8-9a95-d77ab0b7274b.gif)

Stack trace:
```
ckeditorerror.js:46 Uncaught CKEditorError: move-operation-nodes-do-not-exist: The nodes which should be moved do not exist. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-move-operation-nodes-do-not-exist


    at MoveOperation._validate (https://a2ee7d01.ngrok.io/ckeditor5/build/docs/ckeditor5/latest/snippets/features/ui-language/snippet.js:53117:10)
    at Model.on (https://a2ee7d01.ngrok.io/ckeditor5/build/docs/ckeditor5/latest/snippets/features/ui-language/snippet.js:50565:14)
    at Model.fire (https://a2ee7d01.ngrok.io/ckeditor5/build/docs/ckeditor5/latest/snippets/features/ui-language/snippet.js:109249:29)
    at Model.(anonymous function) [as applyOperation] (https://a2ee7d01.ngrok.io/ckeditor5/build/docs/ckeditor5/latest/snippets/features/ui-language/snippet.js:111194:16)
    at UndoCommand._undo (https://a2ee7d01.ngrok.io/ckeditor5/build/docs/ckeditor5/latest/snippets/features/ui-language/snippet.js:104349:11)
    at Object.editor.model.enqueueChange [as callback] (https://a2ee7d01.ngrok.io/ckeditor5/build/docs/ckeditor5/latest/snippets/features/ui-language/snippet.js:104636:9)
    at Model._runPendingChanges (https://a2ee7d01.ngrok.io/ckeditor5/build/docs/ckeditor5/latest/snippets/features/ui-language/snippet.js:51185:58)
    at Model.enqueueChange (https://a2ee7d01.ngrok.io/ckeditor5/build/docs/ckeditor5/latest/snippets/features/ui-language/snippet.js:50687:9)
    at UndoCommand.execute (https://a2ee7d01.ngrok.io/ckeditor5/build/docs/ckeditor5/latest/snippets/features/ui-language/snippet.js:104635:21)
    at UndoCommand.on (https://a2ee7d01.ngrok.io/ckeditor5/build/docs/ckeditor5/latest/snippets/features/ui-language/snippet.js:111190:32)
```

**Comment by scofalik** [comment]
I confirm the issue, it is still reproducible.

The steps can be streamlined:

1. Copy a list item (can be from the editor).
2. Remove all contents and paste the list item.
3. Paste the list item again inside the first one.
4. Undo, undo.

The same can be reproduced with headings, so it is not strictly related to lists. Probably some OT error. I am on it.

**Comment by scofalik** [comment]
I fixed the bug but when you redo, redo after the last step it still crashes, so I will take a look at that. Hopefully, I will find a solution in a reasonable time. If not, I will create a followup issue.

**Comment by Reinmar** [comment]
Does it crash due to https://github.com/ckeditor/ckeditor5-engine/pull/1678#issuecomment-464644835? Or maybe my TC will allow you to better understand the redo thing.
