### ISSUE TITLE
Typing in composite language in new line causes errors in console

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#13867]
## 📝 Provide detailed reproduction steps (if any)

1. Open nightly docs https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/examples/builds-custom/full-featured-editor.html or manual tests on `master` branch
2. Add a new paragraph/line in editor
3. Start typing in composite language (haragana/katakana/pinyin chinese...)

### ❌ Result

Console throws an error. Stack trace:
```javascript
Uncaught TypeError: Cannot read properties of null (reading 'start')
    at _l.toModelRange (snippet.js:4:176502)
    at listenTo.priority (snippet.js:4:219004)
    at Object.fire (snippet.js:4:5541)
    at hr (snippet.js:4:90856)
    at gr.fire (snippet.js:4:90263)
    at el.fire (snippet.js:4:132456)
    at el.onDomEvent (snippet.js:4:145325)
    at listenTo.useCapture (snippet.js:4:132326)
    at En.fire (snippet.js:4:5541)
    at HTMLDivElement.t (snippet.js:4:28950)
```

https://user-images.githubusercontent.com/66953380/231464409-cc2df06a-a3b1-44b3-a837-3b249a3d2713.mov

## 📃 Other details

* Browser: all
* OS: MacOS

**Comment by dufipl** [comment]
This is a regression compared to the `37.0.1` version.
