### ISSUE TITLE
Document Outline and Table of Contents plugin will crash if loaded with h5 or h6 with a default config

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#13919]
## 📝 Provide detailed reproduction steps (if any)

1.  Use an editor with Table of Contents or Document Outline feature with **the default `config.heading` value**.
    1.  As an example, use **second** editor in `ckeditor5-document-outline/tests/manual/tableofcontents/table-of-contents.html` manual test.
2.  Set editor with `<h5>foo</h5>` data.

### ✔️ Expected result

The editor loads up provided content.

### ❌ Actual result

An exception is thrown:

```
Uncaught TypeError: Cannot read properties of null (reading 'getContainedElement')
    at UpcastDispatcher.<anonymous> (headingid.ts:59:1)
    at UpcastDispatcher.fire (emittermixin.ts:241:1)
    at UpcastDispatcher._convertItem (upcastdispatcher.ts:264:1)
    at UpcastDispatcher._convertChildren (upcastdispatcher.ts:314:1)
    at Object.convertChildren (upcastdispatcher.ts:174:1)
    at UpcastDispatcher.<anonymous> (upcasthelpers.ts:503:1)
    at UpcastDispatcher.fire (emittermixin.ts:241:1)
    at UpcastDispatcher._convertItem (upcastdispatcher.ts:276:1)
    at UpcastDispatcher.convert (upcastdispatcher.ts:219:1)
    at datacontroller.ts:488:1
```

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

*   Browser: Any
*   OS: Any
*   First affected CKEditor version: 37.1.0
*   Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
A quick workaround if you want to have support for additional headings is just to add config, like so:

```javascript
ClassicEditor
	.create( document.querySelector( '#editor' ), {
		// ...
		heading: {
			options: [
				{ model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
				{ model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
				{ model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
				{ model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
				{ model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
				{ model: 'heading5', view: 'h5', title: 'Heading 5', class: 'ck-heading_heading5' },
				{ model: 'heading6', view: 'h6', title: 'Heading 6', class: 'ck-heading_heading6' }
			]
		},
		// ...
	} )
```
