### ISSUE TITLE
Editor crash after applying `thead` style on table without heading rows

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#14113]
## 📝 Provide detailed reproduction steps (if any)

1. Select some table cell
2. Apply style for `<thead>` element

![2023-05-11 17 30 34](https://github.com/ckeditor/ckeditor5/assets/1232187/36647b59-e3bb-40d5-bbfd-29a32a159a5f)

### ✔️ Expected result

The style for `<thead>` element should not be enabled for table without heading rows.

Also this should be secured to not crash if the target view element is not available.

### ❌ Actual result

```
Uncaught TypeError: Cannot read properties of undefined (reading '_addClass')
    at DowncastWriter.addClass (downcastwriter.ts:552:1)
    at setViewAttributes (utils.ts:67:1)
    at updateViewAttributes (utils.ts:44:1)
    at DowncastDispatcher.<anonymous> (table.ts:164:1)
    at DowncastDispatcher.fire (emittermixin.ts:241:1)
    at DowncastDispatcher._testAndFire (downcastdispatcher.ts:598:1)
    at DowncastDispatcher._convertAttribute (downcastdispatcher.ts:379:1)
    at DowncastDispatcher.convertChanges (downcastdispatcher.ts:186:1)
    at editingcontroller.ts:117:1
    at View.change (view.ts:513:1)
```

### ❓ Possible solution

_If you have ideas, you can list them here. Otherwise, you can delete this section._

## 📃 Other details

* Browser: …
* OS: …
* First affected CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
Resolved with #14140.
