### ISSUE TITLE
Table column resize does not work with multi-root editor

### ISSUE THREAD

**Issue by Acrophost** [ckeditor/ckeditor5#14132]
## 📝 Provide detailed reproduction steps (if any)

1. Make a build with multi-root editor and table column resize plugin (adding Table and TableColumnResize to [multi-root editor manual test](http://localhost:8125/ckeditor5-editor-multi-root/tests/manual/multirooteditor.html) does the trick)
2. Attempt to open it

### ✔️ Expected result

Build/manual test will open without errors and will be fully functional

### ❌ Actual result

We get an error in the console. It's impossible to use the editor
Stack trace:
```javascript
TypeError: Cannot read properties of null (reading '_addClass')
    at DowncastWriter.addClass (downcastwriter.ts:552:1)
    at tablecolumnresizeediting.ts:149:1
    at View.change (view.ts:513:1)
    at TableColumnResizeEditing.<anonymous> (tablecolumnresizeediting.ts:148:1)
    at TableColumnResizeEditing.fire (emittermixin.ts:241:1)
    at TableColumnResizeEditing.set [as _isResizingAllowed] (observablemixin.ts:139:1)
    at updateBoundObservableProperty (observablemixin.ts:735:1)
    at observablemixin.ts:522:1
    at Array.forEach (<anonymous>)
    at Object.bindTo [as to] (observablemixin.ts:521:1)
```

## 📃 Other details

* Browser: All
* OS: macOS (probably all)
* First affected CKEditor version: 
* Installed CKEditor plugins: MultiRootEditor, Table, TableColumnResize

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Acrophost** [comment]
Duplicate of https://github.com/ckeditor/ckeditor5/issues/13596
