### ISSUE TITLE
[Android][Webview] view-renderer-filler-was-lost error breaks CKEditor

### ISSUE THREAD

**Issue by ItsNoHax** [ckeditor/ckeditor5#1435]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Classic
11.2

## 📋 Steps to reproduce

Start typing a long word, start using bold halfway, type twice, it crashes the CKEditor.
![peek 2018-12-31 14-49](https://user-images.githubusercontent.com/4223434/50561455-41211800-0d0b-11e9-8002-de5261c5f388.gif)

## ❎ Actual result

Exact error:
```
ckeditor.js:5 Uncaught o: view-renderer-filler-was-lost: The inline filler node was lost. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-view-renderer-filler-was-lost


    at Go._removeInlineFiller (file:///android_asset/ckeditor/ckeditor.js:5:159926)
    at Go.render (file:///android_asset/ckeditor/ckeditor.js:5:157989)
    at Os._render (file:///android_asset/ckeditor/ckeditor.js:5:192297)
    at Os.on (file:///android_asset/ckeditor/ckeditor.js:5:189906)
    at Os.fire (file:///android_asset/ckeditor/ckeditor.js:5:91951)
    at Os.change (file:///android_asset/ckeditor/ckeditor.js:5:191782)
    at Os.render (file:///android_asset/ckeditor/ckeditor.js:5:191814)
    at Fc.listenTo (file:///android_asset/ckeditor/ckeditor.js:5:239378)
    at Fc.fire (file:///android_asset/ckeditor/ckeditor.js:5:91951)
    at Fc._runPendingChanges (file:///android_asset/ckeditor/ckeditor.js:5:317322)
```

## 📃 Other details that might be useful

React Native: 0.56
Android 8.0

**Comment by oleq** [comment]
cc @f1ames

**Comment by ItsNoHax** [comment]
@oleq I can confirm it also happens inside your own demo: https://ckeditor.com/ckeditor-5/demo/#classic

Open it inside an Android webview and you can reproduce it.
