### ISSUE TITLE
Editor crashes after toggling the read only mode while the selection is inside the editor

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#1530]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Open the article sample.
2. Paste the following code to the console:
```
document.addEventListener( 'keydown', evt => {
    if ( evt.keyCode == '16' ) {
      editor.isReadOnly == true ? editor.isReadOnly = false : editor.isReadOnly = true;
    } 
} );
```
3. Put the caret inside the editor.
4. Press <kbd>Shift</kbd> twice.

## ✅ Expected result
There's no error in the console.

## ❎ Actual result
The editor crashes.

## 📃 Other details that might be useful
**Error**

```
ckeditorerror.js:46 Uncaught CKEditorError: cannot-change-view-tree: Attempting to make changes to the view when it is in an incorrect state: rendering or post-fixers are in progress. This may cause some unexpected behavior and inconsistency between the DOM and the view. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-cannot-change-view-tree
    at View.change (http://192.168.1.48:8125/ckeditor5-core/tests/manual/article.js:78039:10)
    at InlineEditableUIView._updateIsFocusedClasses (http://192.168.1.48:8125/ckeditor5-core/tests/manual/article.js:97005:15)
    at InlineEditableUIView.on (http://192.168.1.48:8125/ckeditor5-core/tests/manual/article.js:96981:43)
    at InlineEditableUIView.fire (http://192.168.1.48:8125/ckeditor5-core/tests/manual/article.js:107797:29)
    at InlineEditableUIView.set [as isFocused] (http://192.168.1.48:8125/ckeditor5-core/tests/manual/article.js:109682:11)
    at updateBoundObservableProperty (http://192.168.1.48:8125/ckeditor5-core/tests/manual/article.js:110219:30)
    at bindings.forEach.binding (http://192.168.1.48:8125/ckeditor5-core/tests/manual/article.js:110246:7)
    at Set.forEach (<anonymous>)
    at FocusTracker.observable.listenTo (http://192.168.1.48:8125/ckeditor5-core/tests/manual/article.js:110245:15)
    at FocusTracker.fire (http://192.168.1.48:8125/ckeditor5-core/tests/manual/article.js:107797:29)
```

**Notes**

- It doesn't occur if the selection is outside of the editor.
- It's a regression.
- It could be easly reproduced with the collaboration. User is typing -> losing connection -> editor goes read only -> connection is restored -> editor leaves the read only mode -> crash.

**Comment by Mgsy** [comment]
cc @oskarwrobel

**Comment by oskarwrobel** [comment]
Looks like two async listeners try to change the view element at the same time:
- https://github.com/ckeditor/ckeditor5-ui/blob/b99450856def4f4ac567601bff7cdb3032cb93a9/src/editableui/editableuiview.js#L100
- https://github.com/ckeditor/ckeditor5-engine/blob/7815ab08a080dfb3387042aace1aa84473d2a473/src/view/view.js#L257

cc @oleq
