### ISSUE TITLE
Trying to drag and drop content in Document title demo results in errors 

### ISSUE THREAD

**Issue by charlttsie** [ckeditor/ckeditor5#15477]
## 📝 Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/docs/ckeditor5/latest/features/title.html
2. Try to drag and drop the block with content in the demo

### ✔️ Expected result

It's possible to change the placement of the block

### ❌ Actual result

The block doesn't move and the following console errors are thrown multiple times:
```
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Ff (dragdroptarget.js:318:26)
    at dragdroptarget.js:288:58
    at Array.filter (<anonymous>)
    at Df (dragdroptarget.js:288:18)
    at Bf.updateDropMarker (dragdroptarget.js:83:29)
    at listenTo.priority (dragdrop.js:245:28)
    at Object.fire (emittermixin.js:146:47)
    at fr (bubblingemittermixin.js:137:13)
    at br.fire (bubblingemittermixin.js:75:17)
    at Object.<anonymous> (clipboardobserver.js:47:30)
```
```
Uncaught TypeError: Cannot read properties of undefined (reading 'root')
    at Bf._getScrollableRect (dragdroptarget.js:233:38)
    at Bf._updateDropTargetLine (dragdroptarget.js:204:40)
    at view (dragdroptarget.js:147:30)
    at i.on.priority (downcasthelpers.js:1120:34)
    at Pl.fire (emittermixin.js:146:47)
    at Pl._convertMarkerAdd (downcastdispatcher.js:348:14)
    at Pl.convertChanges (downcastdispatcher.js:161:18)
    at editingcontroller.js:57:41
    at cl.change (view.js:409:24)
    at listenTo.priority (editingcontroller.js:56:23)
```
```
ckeditorerror.js:90 Uncaught TypeError: Cannot read properties of null (reading 'parent')
    at El.findMappedViewAncestor (mapper.js:363:29)
    at El.on.priority (mapper.js:98:36)
    at El.fire (emittermixin.js:146:47)
    at El.toModelPosition (mapper.js:273:14)
    at El.toModelRange (mapper.js:250:36)
    at Object.<anonymous> (upcasthelpers.js:506:32)
    at Object.fire (emittermixin.js:146:47)
    at fr (bubblingemittermixin.js:137:13)
    at br.fire (bubblingemittermixin.js:75:17)
    at tl._handleSelectionChange (selectionobserver.js:188:27)
```
```
ckeditorerror.js:90 Uncaught TypeError: Cannot read properties of null (reading 'is')
    at df (utils.js:26:15)
    at Uf (dragdrop.js:539:9)
    at Object.<anonymous> (dragdrop.js:345:36)
    at Object.fire (emittermixin.js:146:47)
    at fr (bubblingemittermixin.js:137:13)
    at br.fire (bubblingemittermixin.js:75:17)
    at hd.fire (domeventobserver.js:76:27)
    at hd.onDomEvent (mouseobserver.js:27:14)
    at listenTo.useCapture (domeventobserver.js:54:26)
    at xn.fire (emittermixin.js:146:47)
```

https://github.com/ckeditor/ckeditor5/assets/132071257/58672643-3c9b-4f1d-befd-f9b2dbbbfa60

## 📃 Other details

* Browser: Any
* First affected CKEditor version: `40.0.0`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
DUP #11656
