### ISSUE TITLE
LinkImage loaded before Image crashes the editor

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#15617]
## 📝 Provide detailed reproduction steps (if any)

Create an editor containing the `LinkImage` plugin (and Image, loaded later).

I prepared two demos:

* LinkImage, Image: https://jsfiddle.net/7q4ygwtu/ (error)
* Image, LinkImage: https://jsfiddle.net/7q4ygwtu/1/ (works)

### ✔️ Expected result

No error.

### ❌ Actual result

```
ckeditor5-dll.js:5 Uncaught (in promise) CKEditorError: schema-cannot-extend-missing-item {"itemName":"imageBlock"}
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-schema-cannot-extend-missing-item
    at li.extend (ckeditor5-dll.js:5:312284)
    at je.init (link.js:5:40837)
    at async Editor.tsx:26:19
    at async Editor.tsx:124:4
```

### ❓ Possible solution

The `LinkImageEditing` plugin requires the `imageBlock` element (schema), registered by the `ImageEditing` plugin in the past. At some point, it has changed, and now, it does not work. Replacing the soft requirement from `ImageEditing` to `ImageBlockEditing ` fixes the issue.

* https://github.com/ckeditor/ckeditor5/blob/a217db61f47e60c61a44ea1814d1fd08e08a4d0c/packages/ckeditor5-link/src/linkimage.ts#L27
	* https://github.com/ckeditor/ckeditor5/blob/a217db61f47e60c61a44ea1814d1fd08e08a4d0c/packages/ckeditor5-link/src/linkimageediting.ts#L43
* https://github.com/ckeditor/ckeditor5/blob/a217db61f47e60c61a44ea1814d1fd08e08a4d0c/packages/ckeditor5-image/src/image/imageblockediting.ts#L41

**Comment by pomek** [comment]
Replacing dependencies does not help, as `LinkImage` may work with inline images while block images are absent.

Hence, I suggest swapping hooks, from `init()`, to `afterInit()` to register converters and modify schema.
