### ISSUE TITLE
`ViewCollection#clear()` throws error if the collection includes a list item separator

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#15717]
## 📝 Provide detailed reproduction steps (if any)

*   Add the following plugin to the editor:

```
import Plugin from '@ckeditor/ckeditor5-core/src/plugin.js';
import { addListToDropdown, createDropdown } from '@ckeditor/ckeditor5-ui/src/dropdown/utils.js';
import Collection from '@ckeditor/ckeditor5-utils/src/collection.js';

export default class Issue extends Plugin {
	init() {
		const editor = this.editor;
		const t = editor.t;
		const doc = this.editor.model.document;

		this.editor.ui.componentFactory.add( 'issue', locale => {
			const dropdownView = createDropdown( locale );

			dropdownView.buttonView.set( {
				label: t( 'Issue' ),
				withText: 'Issue',
				tooltip: true
			} );

			dropdownView.on( 'change:isOpen', ( evt, propertyName, newValue, oldValue ) => {
				if ( newValue ) {
					addListToDropdown( dropdownView, getDropdownItemsDefinitions( doc, dropdownView ) );
				}
				else {
					dropdownView.listView.items.clear();
				}
			} );

			return dropdownView;
		} );
	}
}

function getDropdownItemsDefinitions( doc ) {
	const itemDefinitions = new Collection();

	itemDefinitions.add( { type: 'separator' } );

	return itemDefinitions;
}
```

*   Add `issue` item to the toolbar items
*   Run the editor
*   Open the "Issue" dropdown
*   Close the "Issue" dropdown

### ✔️ Expected result

The collection has been cleared.

### ❌ Actual result

The error is thrown.

```
collection.ts:742 Uncaught CKEditorError: collection-remove-404
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-collection-remove-404
    at ViewCollection._remove (collection.ts:742:1)
    at ViewCollection.remove (collection.ts:307:1)
    at ViewCollection.remove (viewcollection.ts:230:1)
    at ListView._deregisterFocusableListItem (listview.ts:221:1)
    at ViewCollection.<anonymous> (listview.ts:155:1)
    at ViewCollection.fire (emittermixin.ts:241:1)
    at ViewCollection.clear (collection.ts:392:1)
    at _DropdownView.<anonymous> (article.js:36:1)
    at _DropdownView.fire (emittermixin.ts:241:1)
    at _DropdownView.set [as isOpen] (observablemixin.ts:139:1)
```

## 📃 Other details

*   It's a regression introduced in v40.2.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by arkflpc** [comment]
Broken by this commit: https://github.com/ckeditor/ckeditor5/commit/9b11edd3568400116dad3b80205d5cff94db5f1e
