### ISSUE TITLE
`ImageResize` loaded before `ImageBlock` or `ImageInline` throws

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#15994]
## 📝 Provide detailed reproduction steps (if any)

As in the title, load the `ImageResize` plugin before `ImageBlock` or `ImageInline`.

### ✔️ Expected result

No error.

### ❌ Actual result

When loading `[ ImageResize, ImageBlock ]`

```
imageresize.js:49 CKEditorError: schema-cannot-extend-missing-item {"itemName":"imageBlock"}
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-schema-cannot-extend-missing-item
    at Schema.extend (schema.ts:146:1)
    at ImageResizeEditing._registerSchema (imageresizeediting.ts:86:1)
    at ImageResizeEditing.init (imageresizeediting.ts:75:1)
```

When loading `[ ImageResize, ImageInline ]`

```
imageresize.js:51 CKEditorError: schema-cannot-extend-missing-item {"itemName":"imageInline"}
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-schema-cannot-extend-missing-item
    at Schema.extend (schema.ts:146:1)
    at ImageResizeEditing._registerSchema (imageresizeediting.ts:90:1)
    at ImageResizeEditing.init (imageresizeediting.ts:75:1)
```

### ❓ Possible solution

Schema could be extended in the `afterInit()` part.

**Comment by pomek** [comment]
Below you can find a diff that allows reproducing the issue.

```diff
diff --git a/packages/ckeditor5-image/tests/manual/imageresize.js b/packages/ckeditor5-image/tests/manual/imageresize.js
index cc5c465b6d..d1d3b1503f 100644
--- a/packages/ckeditor5-image/tests/manual/imageresize.js
+++ b/packages/ckeditor5-image/tests/manual/imageresize.js
@@ -6,25 +6,30 @@
 /* global document, console, window */

 import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor.js';
-import ArticlePluginSet from '@ckeditor/ckeditor5-core/tests/_utils/articlepluginset.js';
-import Indent from '@ckeditor/ckeditor5-indent/src/indent.js';
-import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock.js';
-import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage.js';
-import CloudServices from '@ckeditor/ckeditor5-cloud-services/src/cloudservices.js';
+// import ArticlePluginSet from '@ckeditor/ckeditor5-core/tests/_utils/articlepluginset.js';
+// import Indent from '@ckeditor/ckeditor5-indent/src/indent.js';
+// import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock.js';
+// import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage.js';
+// import CloudServices from '@ckeditor/ckeditor5-cloud-services/src/cloudservices.js';
 import ImageResize from '../../src/imageresize.js';
-import ImageUpload from '../../src/imageupload.js';
-
+import ImageInline from '../../src/imageinline.js';
+import ImageBlock from '../../src/imageblock.js';
+// import ImageUpload from '../../src/imageupload.js';
+//
 import { CS_CONFIG } from '@ckeditor/ckeditor5-cloud-services/tests/_utils/cloud-services-config.js';

 const commonConfig = {
        plugins: [
-               ArticlePluginSet,
+               // ArticlePluginSet,
                ImageResize,
-               ImageUpload,
-               Indent,
-               IndentBlock,
-               CloudServices,
-               EasyImage
+               // ImageInline,
+               // ImageBlock
+
+               // ImageUpload,
+               // Indent,
+               // IndentBlock,
+               // CloudServices,
+               // EasyImage
        ],
        toolbar: [ 'heading', '|', 'bold', 'italic', 'link',
                'bulletedList', 'numberedList', 'blockQuote', 'insertTable', 'undo', 'redo', 'outdent', 'indent' ],
@@ -46,21 +51,21 @@ ClassicEditor
        .catch( err => {
                console.error( err.stack );
        } );
-
-ClassicEditor
-       .create( document.querySelector( '#fancy-editor' ), commonConfig )
-       .then( editor => {
-               window.fancyEditor = editor;
-       } )
-       .catch( err => {
-               console.error( err.stack );
-       } );
-
-ClassicEditor
-       .create( document.querySelector( '#editor-other-units' ), commonConfig )
-       .then( editor => {
-               window.editorOtherUnits = editor;
-       } )
-       .catch( err => {
-               console.error( err.stack );
-       } );
+//
+// ClassicEditor
+//     .create( document.querySelector( '#fancy-editor' ), commonConfig )
+//     .then( editor => {
+//             window.fancyEditor = editor;
+//     } )
+//     .catch( err => {
+//             console.error( err.stack );
+//     } );
+//
+// ClassicEditor
+//     .create( document.querySelector( '#editor-other-units' ), commonConfig )
+//     .then( editor => {
+//             window.editorOtherUnits = editor;
+//     } )
+//     .catch( err => {
+//             console.error( err.stack );
+//     } );
```

* `yarn run manual -f image`
* http://localhost:8125/ckeditor5-image/tests/manual/imageresize.html
