### ISSUE TITLE
[Docs] Multi-root editor crashes after focusing the image

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#1676]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Open the multi-root editor sample in the documentation page on the latest master.
2. Focus the image.

## ✅ Expected result
The image is focused properly.

## ❎ Actual result
The editor crashes.

## 📃 Other details that might be useful

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/55553896-bd980e00-56e1-11e9-9557-e5eba6925ba6.gif)

**Error**
```
ckeditorerror.js:46 Uncaught CKEditorError: cannot-change-view-tree: Attempting to make changes to the view when it is in an incorrect state: rendering or post-fixers are in progress. This may cause some unexpected behavior and inconsistency between the DOM and the view. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-cannot-change-view-tree

    at Fr.change (http://192.168.1.46:8080/build/docs/ckeditor5/latest/snippets/examples/multi-root-editor/snippet.js:4:122523)
    at e (http://192.168.1.46:8080/build/docs/ckeditor5/latest/snippets/examples/multi-root-editor/snippet.js:4:274322)
    at Fr.<anonymous> (http://192.168.1.46:8080/build/docs/ckeditor5/latest/snippets/examples/multi-root-editor/snippet.js:4:274543)
    at Fr.<anonymous> (http://192.168.1.46:8080/build/docs/ckeditor5/latest/snippets/examples/multi-root-editor/snippet.js:4:31867)
    at Fr.fire (http://192.168.1.46:8080/build/docs/ckeditor5/latest/snippets/examples/multi-root-editor/snippet.js:4:33261)
    at Fr.set [as isRenderingInProgress] (http://192.168.1.46:8080/build/docs/ckeditor5/latest/snippets/examples/multi-root-editor/snippet.js:4:46280)
    at Fr._render (http://192.168.1.46:8080/build/docs/ckeditor5/latest/snippets/examples/multi-root-editor/snippet.js:4:123677)
    at Fr.<anonymous> (http://192.168.1.46:8080/build/docs/ckeditor5/latest/snippets/examples/multi-root-editor/snippet.js:4:120223)
    at Fr.fire (http://192.168.1.46:8080/build/docs/ckeditor5/latest/snippets/examples/multi-root-editor/snippet.js:4:33261)
    at Fr.change (http://192.168.1.46:8080/build/docs/ckeditor5/latest/snippets/examples/multi-root-editor/snippet.js:4:123061)
```

It's a regression.

**Comment by mlewand** [comment]
First bad commit https://github.com/ckeditor/ckeditor5-utils/commit/5140c2cb8486fc65fce2af812f327b30b0ab6b67

**Comment by oleq** [comment]
Oooppsss... 😛
