### ISSUE TITLE
Editor throws error while pasting when the end of block element is selected

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#1683]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest master

## 📋 Steps to reproduce

1. Open http://localhost:8125/ckeditor5-build-classic/tests/manual/ckeditor.html
2. Select the whole heading.
3. CMD + C 
3. CMD + V

## ✅ Expected result

No error

## ❎ Actual result

```
ckeditor.js:5 Uncaught CKEditorError: insert-operation-position-invalid: Insertion position is invalid. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-insert-operation-position-invalid

    at cc._validate (http://localhost:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:100:281098)
    at Gc.on.priority (http://localhost:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:100:326837)
    at Gc.fire (http://localhost:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:100:104270)
    at Gc.(anonymous function) [as applyOperation] (http://localhost:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:100:118567)
    at pc.insert (http://localhost:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:100:290314)
    at Rc._insert (http://localhost:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:100:318551)
    at Rc._handleNode (http://localhost:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:100:317967)
    at Rc.handleNodes (http://localhost:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:100:317322)
    at Object.callback (http://localhost:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:100:327973)
    at Gc._runPendingChanges (http://localhost:8125/ckeditor5-build-classic/tests/manual/ckeditor.js:100:330066)
```

## 📃 Other details that might be useful

Chrome 73.

**Comment by ma2ciek** [comment]
It's a regression, I can't reproduce it on https://ckeditor5.github.io/ (v.12.0.0)

**Comment by Reinmar** [comment]
Confirmed.

**Comment by Reinmar** [comment]
Bisecting...

**Comment by Reinmar** [comment]
Bisecting...

**Comment by Reinmar** [comment]
```(detached:bisect/bad~1 8af68a3) p@m /workspace/ckeditor5> git bisect good
7ba19345b20bc423a7a24da7cbfe15759e202be8 is the first bad commit
commit 7ba19345b20bc423a7a24da7cbfe15759e202be8
Author: Travis CI User <travis@example.org>
Date:   Thu Mar 7 13:56:10 2019 +0000

    Revision: https://github.com/ckeditor/ckeditor5-engine/commit/f4e46447100335ec08d8d54b77215718b74724c5```

**Comment by Reinmar** [comment]
First bad commit: https://github.com/ckeditor/ckeditor5-
engine/commit/f4e46447100335ec08d8d54b77215718b74724c5

And makes a lot of sense.

**Comment by scofalik** [comment]
Closed by https://github.com/ckeditor/ckeditor5-engine/commit/093b214
