### ISSUE TITLE
The inline filler node was lost error when editing link with mention

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1780]
## Is this a bug report or feature request? (choose one)

🐞 Bug report 

## 💻 Version of CKEditor

latest master

## 📋 Steps to reproduce

1. Go to chat with mention feature sample
2. Insert link with mention marker (ie `#`)
3. Place selection after marker: `#`
4. In opened mention ui select some item
5. After item was inserted remove character one-by-one

## ✅ Expected result

- letters are removed as normal
- the mention is removed when it's modified

## ❎ Actual result

There's error in console and the editor stop functioning properly.

## 📃 Other details that might be useful

:popcorn: : ![Peek 2019-05-28 14-07](https://user-images.githubusercontent.com/247363/58476728-f4265e00-8151-11e9-80de-abfbd78f66d9.gif)

:chart_with_upwards_trend: :

```
Uncaught CKEditorError: view-renderer-filler-was-lost: The inline filler node was lost. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-view-renderer-filler-was-lost

    at Renderer._removeInlineFiller (http://192.168.1.156:63341/ckeditor5/build/docs/ckeditor5/12.1.0/snippets/examples/chat-with-mentions/snippet.js:77283:10)
    at Renderer.render (http://192.168.1.156:63341/ckeditor5/build/docs/ckeditor5/12.1.0/snippets/examples/chat-with-mentions/snippet.js:77076:9)
    at View._render (http://192.168.1.156:63341/ckeditor5/build/docs/ckeditor5/12.1.0/snippets/examples/chat-with-mentions/snippet.js:80943:18)
    at View.<anonymous> (http://192.168.1.156:63341/ckeditor5/build/docs/ckeditor5/12.1.0/snippets/examples/chat-with-mentions/snippet.js:80452:9)
    at View.fire (http://192.168.1.156:63341/ckeditor5/build/docs/ckeditor5/12.1.0/snippets/examples/chat-with-mentions/snippet.js:114594:29)
    at View.change (http://192.168.1.156:63341/ckeditor5/build/docs/ckeditor5/12.1.0/snippets/examples/chat-with-mentions/snippet.js:80745:9)
    at View.forceRender (http://192.168.1.156:63341/ckeditor5/build/docs/ckeditor5/12.1.0/snippets/examples/chat-with-mentions/snippet.js:80763:8)
    at MutationObserver._onMutations (http://192.168.1.156:63341/ckeditor5/build/docs/ckeditor5/12.1.0/snippets/examples/chat-with-mentions/snippet.js:75223:13)
```

**Comment by jodator** [comment]
The link in mention is enough to duplicate the error.

**Comment by Mgsy** [comment]
This issue is fixed.
