### ISSUE TITLE
CKEditor5 works in SharePoint Online webparts, but not in SharePoint 2016

### ISSUE THREAD

**Issue by HarshitGupta20** [ckeditor/ckeditor5#1855]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 💻 ckeditor5

I need to use CKeditor5 in SharePoint 2016 React webpart. Thats not working as expected. However, the same code works perfectly for SharePoint Online React webpart.

## 📋 Steps to reproduce

1. Code used for the functionality is 
```js
import * as React from 'react';
import styles from './CkeditorSp2016.module.scss';
import { ICkeditorSp2016Props } from './ICkeditorSp2016Props';
import { escape } from '@microsoft/sp-lodash-subset';
import CKEditor from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

export default class CkeditorSp2016 extends React.Component < ICkeditorSp2016Props, {} > {
  public render(): React.ReactElement<ICkeditorSp2016Props> {
    return(
      <div className = { styles.ckeditorSp2016 } >
          <CKEditor
                    editor={ ClassicEditor }
                    data="<p>Hello from CKEditor 5!</p>"
                    onInit={ editor => {
                        // You can store the "editor" and use when it is needed.
                        console.log( 'Editor is ready to use!', editor );
                    } }
                    onChange={ ( event, editor ) => {
                        const data = editor.getData();
                        console.log( { event, editor, data } );
                    } }
                    onBlur={ editor => {
                        console.log( 'Blur.', editor );
                    } }
                    onFocus={ editor => {
                        console.log( 'Focus.', editor );
                    } }
                />
      </div >
    );
  }
}
```
==================================================

2. The error receiving on webpart is:

***ERROR MESSAGE:
```
***Failed to load component "32d9a286-81cb-49e8-9a0c-142c40db3297" (CkeditorSp2016WebPart).
Original error: ***Failed to load entry point from component "32d9a286-81cb-49e8-9a0c-142c40db3297" (CkeditorSp2016WebPart).
Original error: Error loading https://component-id.invalid/32d9a286-81cb-49e8-9a0c-142c40db3297_0.0.1
	Module build failed: SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.module.exports (D:\Users\GUPTAH18\Desktop\ReactJSProject\ckeditor-sp-2016\node_modules\source-map-loader\index.js:30:20)
```

***CALLSTACK:
```
Error: ***Failed to load component "32d9a286-81cb-49e8-9a0c-142c40db3297" (CkeditorSp2016WebPart).
Original error: ***Failed to load entry point from component "32d9a286-81cb-49e8-9a0c-142c40db3297" (CkeditorSp2016WebPart).
Original error: Error loading https://component-id.invalid/32d9a286-81cb-49e8-9a0c-142c40db3297_0.0.1
	Module build failed: SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.module.exports (D:\Users\GUPTAH18\Desktop\ReactJSProject\ckeditor-sp-2016\node_modules\source-map-loader\index.js:30:20)
   at Anonymous function (http://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader_en-us.js:16234:9)
   at lib$es6$promise$$internal$$tryCatch (http://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader_en-us.js:21064:9)
   at lib$es6$promise$$internal$$invokeCallback (http://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader_en-us.js:21076:9)
   at lib$es6$promise$$internal$$publish (http://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader_en-us.js:21047:11)
   at lib$es6$promise$$internal$$publishRejection (http://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader_en-us.js:20997:7)
   at lib$es6$promise$asap$$flush (http://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader_en-us.js:20822:9)
```

**Comment by Mgsy** [comment]
Hello, we didn't test CKEditor 5 in SharePoint and don't have any knowledge about such integration. Unfortunately, we won't be able to help and you have to debug it on your own.
