### ISSUE TITLE
[@octokit/rest] octokit.authenticate() is deprecated

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1889]
![image](https://user-images.githubusercontent.com/156149/61224891-c6a46c80-a71f-11e9-9b18-04ee5fa573a9.png)

```
? Provide the GitHub token: [hidden]
{ Deprecation: [@octokit/rest] octokit.authenticate() is deprecated. Use "auth" constructor option instead.
    at authenticate (/workspace/misc/mgit2/node_modules/@octokit/rest/plugins/authentication-deprecated/authenticate.js:9:44)
    at saveReleaseOptions (/workspace/misc/mgit2/node_modules/@ckeditor/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js:201:11)
    at configureRelease.then._releaseOptions (/workspace/misc/mgit2/node_modules/@ckeditor/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js:133:29)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'Deprecation' }
```

**Comment by Reinmar** [comment]
See https://github.com/cksource/mgit2/issues/109#issuecomment-511715945
