### ISSUE TITLE
Error when copying text from Word

### ISSUE THREAD

**Issue by StanJansen** [ckeditor/ckeditor5#1971]
🐞 Bug report

## 💻 Version of CKEditor

Custom build using the following configuration (Comments showing the used version, latest versions at moment of creating the issue):

```js
import CkEditorBase from '@ckeditor/ckeditor5-editor-inline/src/inlineeditor'; // 12.2.1
import EssentialsPlugin from '@ckeditor/ckeditor5-essentials/src/essentials'; // 10.1.3
import AutoformatPlugin from '@ckeditor/ckeditor5-autoformat/src/autoformat'; // 10.0.4
import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold'; // 10.1.0
import ItalicPlugin from '@ckeditor/ckeditor5-basic-styles/src/italic'; // 10.1.0
import BlockquotePlugin from '@ckeditor/ckeditor5-block-quote/src/blockquote'; // 10.1.1
import HeadingPlugin from '@ckeditor/ckeditor5-heading/src/heading'; // 10.1.1
import LinkPlugin from '@ckeditor/ckeditor5-link/src/link'; // 10.1.0
import ListPlugin from '@ckeditor/ckeditor5-list/src/list'; // 11.0.3
import ParagraphPlugin from '@ckeditor/ckeditor5-paragraph/src/paragraph'; // 10.0.4
import AlignmentPlugin from '@ckeditor/ckeditor5-alignment/src/alignment'; // 10.0.4
import TablePlugin from '@ckeditor/ckeditor5-table/src/table'; // 10.1.0
import TabletoolbarPlugin from '@ckeditor/ckeditor5-table/src/tabletoolbar'; // 10.1.0
import BalloontoolbarPlugin from '@ckeditor/ckeditor5-ui/src/toolbar/balloon/balloontoolbar'; // 11.2.0

export default class CkEditor extends CkEditorBase {}

CkEditor.builtinPlugins = [
		EssentialsPlugin,
		AutoformatPlugin,
		BoldPlugin,
		ItalicPlugin,
		BlockquotePlugin,
		HeadingPlugin,
		LinkPlugin,
		ListPlugin,
		ParagraphPlugin,
		AlignmentPlugin,
		TablePlugin,
		TabletoolbarPlugin,
		BalloontoolbarPlugin
];

CkEditor.defaultConfig = {
	toolbar: {
		items: [
			'heading',
			'|',
			'bold',
			'italic',
			'link',
			'bulletedList',
			'numberedList',
			'blockQuote',
			'alignment',
			'insertTable',
			'undo',
			'redo'
		]
	},
	table: {
		toolbar: [
			'tableColumn',
			'tableRow',
			'mergeTableCells'
		]
	},
	language: 'nl'
};
```

## 📋 Steps to reproduce

1. Copy text from a Word or Google Docs document
2. Paste in CKEditor

## ✅ Expected result
Expect the text to be pasted without styling (This worked before, broke at a later version, can't pinpoint which one yet).

## ❎ Actual result
The editor bugs and locks. Page must be reloaded in order to enter text again.

## 📃 Other details that might be useful
Console error:
```
Uncaught CKEditorError: model-createPositionAt-offset-required: Model#createPositionAt() requires the offset when the first parameter is a model item. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-createPositionAt-offset-required

    at Function._createAt (webpack-internal:///./node_modules/ckeditor5-build-fwcms/build/ckeditor.js:5:411805)
    at new $d (webpack-internal:///./node_modules/ckeditor5-build-fwcms/build/ckeditor.js:5:412907)
    at za.eval (webpack-internal:///./node_modules/ckeditor5-build-fwcms/build/ckeditor.js:5:419406)
    at za.fire (webpack-internal:///./node_modules/ckeditor5-build-fwcms/build/ckeditor.js:5:89687)
    at za._convertItem (webpack-internal:///./node_modules/ckeditor5-build-fwcms/build/ckeditor.js:5:251896)
    at za._convertChildren (webpack-internal:///./node_modules/ckeditor5-build-fwcms/build/ckeditor.js:5:252360)
    at za.eval (webpack-internal:///./node_modules/ckeditor5-build-fwcms/build/ckeditor.js:5:233223)
    at za.fire (webpack-internal:///./node_modules/ckeditor5-build-fwcms/build/ckeditor.js:5:89687)
    at za._convertItem (webpack-internal:///./node_modules/ckeditor5-build-fwcms/build/ckeditor.js:5:251896)
    at za._convertChildren (webpack-internal:///./node_modules/ckeditor5-build-fwcms/build/ckeditor.js:5:252360)
```

**Comment by Mgsy** [comment]
Hi, I've built the editor with a config you provided and pasting from Word doesn't crash the editor. Please, make sure that you've built your editor properly and all your packages are updated (you can use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates).
