### ISSUE TITLE
Explosion when undoing after pasting multiple nodes to the Title

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#2022]
Requires: https://github.com/ckeditor/ckeditor5/issues/2003.

Looks like there is a quite easy way to make an explosion in the editor while using `Title` plugin and `Undo`.

### Steps to reproduce

- For the following model
```html
<title><title-content>[]Title</title-content></title>
<paragraph>Paragraph</paragraph>
```
- Insert the following model fragment using `Model#insertContent` (or just paste it - it's the same) at the beginning of the `title-content` element
```html
<paragraph>Inserted paragraph</paragraph>
<listItem listIndent="0" listType="bulleted">Inserted list item</listItem>
```
- The result should be as follow:
```html
<title><title-content>Inserted paragraph</title-content></title>
<listItem listIndent="0" listType="bulleted">Insetred list item[]</listItem>
<paragraph>Title</paragraph>
<paragraph>Paragraph</paragraph>
```
This is because `insertContent` inserts `paragraph` and `listItem` before the `title` element
```html
<paragraph>Inserted paragraph</paragraph>
<listItem listIndent="0" listType="bulleted">Inserted list otem</listItem>
<title><title-content>Title</title-content></title>
<paragraph>Paragraph</paragraph>
```
and then `Title` post-fixer does his job and:
1. Changes `paragraph` to a `title` element, because `paragraph` is a first child in the `root` and is allowed to be a `title`
2. Do nothing with `listItem`
3. Changes the old `title` element to a `paragraph` because it's not a first child in the `root` and cannot be a `title` anymore.

- Undo the last change.

### Result
```
ckeditorerror.js:66 Uncaught CKEditorError: model-createPositionAt-offset-required: Model#createPositionAt() requires the offset when the first parameter is a model item. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-createPositionAt-offset-required

    at Function._createAt (http://localhost:8125/ckeditor5-core/tests/manual/article.js:58075:11)
    at new Range (http://localhost:8125/ckeditor5-core/tests/manual/article.js:58275:66)
    at LiveRange._getTransformedByMove (http://localhost:8125/ckeditor5-core/tests/manual/article.js:59008:17)
    at LiveRange._getTransformedByMoveOperation (http://localhost:8125/ckeditor5-core/tests/manual/article.js:58790:15)
    at LiveRange.getTransformedByOperation (http://localhost:8125/ckeditor5-core/tests/manual/article.js:58684:17)
    at LiveRange.transform (http://localhost:8125/ckeditor5-core/tests/manual/article.js:50153:22)
    at Model.listenTo.priority (http://localhost:8125/ckeditor5-core/tests/manual/article.js:50141:14)
    at Model.fire (http://localhost:8125/ckeditor5-core/tests/manual/article.js:110432:29)
    at Model.<computed> [as applyOperation] (http://localhost:8125/ckeditor5-core/tests/manual/article.js:112561:16)
    at UndoCommand._undo (http://localhost:8125/ckeditor5-core/tests/manual/article.js:106259:11)
```

![Sep-03-2019 15-02-25](https://user-images.githubusercontent.com/1057056/64175528-c7be6400-ce5b-11e9-9fc7-5f154fb43fbd.gif)

It looks like selection live range transformation is a problem here.

**Comment by Reinmar** [comment]
I can't reproduce any issues anymore.
