### ISSUE TITLE
Unclear wiki, building CKEditor, documentation, set up.

### ISSUE THREAD

**Issue by adelura** [ckeditor/ckeditor5#439]
Hi guys! I was curious how new version of CKEditor works, so I tried to run it. There are few things I want to cover in one issue:

1. Even though building documentation went quite smooth it's unclear how to run it. There is no enought information [here](https://github.com/ckeditor/ckeditor5/wiki/Development-environment#generating-documentation). I tried to use `http-server` on directory where `index.html` is located (`ckeditor5/build/docs/ckeditor5/api`), but there is lack of `/assets` directory there. I tried [umberto](https://www.npmjs.com/package/umberto) readme but with no luck.
2. When I execute `npm run install-optional-dependencies` it throw an error on git bash on windows.
3. There is no information how to build CKEditor - I think it, might be in documentation but didn't get there yet :)

**Comment by Reinmar** [comment]
Thanks for the feedback, @adelura!

> Even though building documentation went quite smooth it's unclear how to run it.

Strange. It WFM. I'm able to generate this:

```
(master ea4dc26) p@m /workspace/ckeditor5> tree -L 2 build/docs
build/docs
├── assets
│   ├── css
│   ├── img
│   └── js
└── ckeditor5
    ├── api
    ├── assets
    ├── guides
    ├── index.html
    └── tutorials

9 directories, 1 file
```

And in the browser I get this:

![image](https://cloud.githubusercontent.com/assets/156149/26050402/c7ef0446-395e-11e7-975c-7a05b7818f1c.png)


> When I execute npm run install-optional-dependencies it throw an error on git bash on windows.

What kind of error?

> There is no information how to build CKEditor - I think it, might be in documentation but didn't get there yet :)

There's no such documentation yet except these three resources:

* https://github.com/ckeditor/ckeditor5-labs/tree/master/integrations
* https://github.com/ckeditor/ckeditor5/issues/139
* https://github.com/ckeditor/ckeditor5-build-classic#ckeditor-5-classic-build (how to build a concrete build)

We're starting to work on guides right now. There should be some real resources soon.

**Comment by adelura** [comment]
Thank you, I'll have a look at this again during weekend.

**Comment by adelura** [comment]
So once I execute `gulp build > res.txt` I have [following output](https://pastebin.com/raw/NgjQrmt6) in a file. And in console I have this:

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Page: ckeditor5/api/output.json has no title.
    at Hexo.hexo.extend.filter.register (C:\dev\ckeditor5\node_modules\umberto\hexo\scripts\filter\validate-front-matter.js:22:9)
    at Hexo.tryCatcher (C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\hexo\lib\extend\filter.js:68:35
    at tryCatcher (C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\bluebird\js\release\reduce.js:155:18)
    at Object.gotAccum (C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\dev\ckeditor5\node_modules\umberto\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

Tests are green `gulp test --files=core`

```
SUMMARY:
√ 138 tests completed
[22:04:27] Finished 'test' after 39 s
```

I'm using:

node 7.8.0
npm 4.2.0
windows 10
git 2.8.1

**Comment by Reinmar** [comment]
Regarding the docs – cc @m-turek. But, TBH, it won't be our priority now to work on the compatibility of such tasks with Windows. Since soon we'll have the docs online, this won't be a crucial task.

Regarding the tests – good to hear that they work on Windows :).

**Comment by adelura** [comment]
Okay, got the point. Probably I will find some time and investigate it.

**Comment by Reinmar** [comment]
I think that we significantly improved the docs. Could you check again if all's fine now? Of course, Windows may still not be supported as this is something separate.
