### ISSUE TITLE
Styling a first character of a marker removes entire word

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#476]
## Steps to reproduce
1. Open a sample with markers.
2. Apply a marker to some word.
3. Select a first character of the marker.
4. Press <kbd>CTRL</kbd> + <kbd>B</kbd> twice.

## Current result
- The word with the marker was removed, except it's first character
- Chrome, Firefox, Edge and Opera receives an error in a console.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/27332952-615e4c5a-55c4-11e7-9753-c0862d201fe3.gif)

## Error
`renderer.js?6f39:607 Uncaught TypeError: Cannot read property 'parent' of null
    at Renderer._updateDomSelection (http://192.168.20.69:8125/ckeditor5-engine/tests/manual/markers.js:36294:29)
    at Renderer._updateSelection (http://192.168.20.69:8125/ckeditor5-engine/tests/manual/markers.js:36214:9)
    at Renderer.render (http://192.168.20.69:8125/ckeditor5-engine/tests/manual/markers.js:35902:8)
    at Document.render (http://192.168.20.69:8125/ckeditor5-engine/tests/manual/markers.js:29805:17)
    at Document.on (http://192.168.20.69:8125/ckeditor5-engine/tests/manual/markers.js:6552:32)
    at Document.fire (http://192.168.20.69:8125/ckeditor5-engine/tests/manual/markers.js:2055:29)
    at Document.(anonymous function) [as render] (http://192.168.20.69:8125/ckeditor5-engine/tests/manual/markers.js:6556:16)
    at Document.EditingController._listener.listenTo (http://192.168.20.69:8125/ckeditor5-engine/tests/manual/markers.js:40965:14)
    at Document.fire (http://192.168.20.69:8125/ckeditor5-engine/tests/manual/markers.js:2055:29)
    at Document.enqueueChanges (http://192.168.20.69:8125/ckeditor5-engine/tests/manual/markers.js:38804:9)`

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Safari, Firefox, Edge, Opera
Release: 0.10.0

**Comment by Reinmar** [comment]
Fixed by https://github.com/ckeditor/ckeditor5-engine/issues/922.
