### ISSUE TITLE
Errors thrown when removing certain plugins

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5599]
## Issue 1

```js
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';

import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
import CKFinder from '@ckeditor/ckeditor5-ckfinder/src/ckfinder';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';

ClassicEditor.builtinPlugins = [
	Essentials,
	UploadAdapter,
	CKFinder,
	Image,
	ImageCaption,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Paragraph
];

ClassicEditor
	.create( document.querySelector( '#editor' ), {
		removePlugins: [
			'Image',
			'ImageCaption',
			'ImageStyle',
			'ImageToolbar',
			'ImageUpload'
		]
	} )
	.then( editor => {
		window.editor = editor;
	} )
	.catch( err => {
		console.error( err.stack );
	} );

```

```
CKEditorError: unexpected-error {"originalError":{"message":"Cannot read property 'isEnabled' of undefined","stack":"TypeError: Cannot read property 'isEnabled' of undefined\n    at CKFinderCommand.refresh (http://localhost:8125/ckeditor5/tests/manual/article.js:34486:39)\n    at Document.CKFinderCommand.listenTo.priority (http://localhost:8125/ckeditor5/tests/manual/article.js:34477:72)\n    at Document.fire (http://localhost:8125/ckeditor5/tests/manual/article.js:103202:30)\n    at Document._handleChangeBlock (http://localhost:8125/ckeditor5/tests/manual/article.js:46555:10)\n    at Model._runPendingChanges (http://localhost:8125/ckeditor5/tests/manual/article.js:50574:18)\n    at Model.enqueueChange (http://localhost:8125/ckeditor5/tests/manual/article.js:50041:10)\n    at DataController.init (http://localhost:8125/ckeditor5/tests/manual/article.js:38534:14)\n    at DataController.<anonymous> (http://localhost:8125/ckeditor5/tests/manual/article.js:105331:32)\n    at DataController.fire (http://localhost:8125/ckeditor5/tests/manual/article.js:103202:30)\n    at DataController.<computed> [as init] (http://localhost:8125/ckeditor5/tests/manual/article.js:105335:16)","name":"TypeError"}}
    at Function.rethrowUnexpectedError (http://localhost:8125/ckeditor5/tests/manual/article.js:99396:9)
    at Document.fire (http://localhost:8125/ckeditor5/tests/manual/article.js:103235:59)
    at Document._handleChangeBlock (http://localhost:8125/ckeditor5/tests/manual/article.js:46555:10)
    at Model._runPendingChanges (http://localhost:8125/ckeditor5/tests/manual/article.js:50574:18)
    at Model.enqueueChange (http://localhost:8125/ckeditor5/tests/manual/article.js:50041:10)
    at DataController.init (http://localhost:8125/ckeditor5/tests/manual/article.js:38534:14)
    at DataController.<anonymous> (http://localhost:8125/ckeditor5/tests/manual/article.js:105331:32)
    at DataController.fire (http://localhost:8125/ckeditor5/tests/manual/article.js:103202:30)
    at DataController.<computed> [as init] (http://localhost:8125/ckeditor5/tests/manual/article.js:105335:16)
    at http://localhost:8125/ckeditor5/tests/manual/article.js:37903:26
```

## Issue 2

Remove `ImageUpload` from the `config.removePlugins` list in the previous issue and your get this:

```
article.js:45 CKEditorError: schema-cannot-extend-missing-item: Cannot extend an item which was not registered yet. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-schema-cannot-extend-missing-item
 {"itemName":"image"}
    at Schema.extend (http://localhost:8125/ckeditor5/tests/manual/article.js:58520:10)
    at ImageUploadEditing.init (http://localhost:8125/ckeditor5/tests/manual/article.js:82979:16)
```

**Comment by Reinmar** [comment]
When checking the first issue I noticed that `CKFinderEditing` requires `Link` and `Image` which is incorrect. If anything, it should require `LinkEditing` and `ImageEditing`. 

When I did this change it fixed the above errors... but I don't get why actually.

Also, it seems that `removePlugins` work really bad. I remember implementing some warnings when trying to remove a plugin which is required by other plugin (e.g. when removing `ImageEditing`, which is required by `Image`), but I don't get these warnings now, which means that we broke something there ;/

**Comment by jodator** [comment]
> When I did this change it fixed the above errors... but I don't get why actually.

It's because you remove `Image` plugin - not the `ImageEditing` so the `ImageEditing` plugins will be loaded as a dependency of the `CKFinderEditing`. In other words `removePlugins= ['Image']` only prevents loading of an `Image` not the "child" plugins.

Also if the plugin loaded from plugins list we do not check if it was required by other plugins (which may be defined later on).

Second finding: You cannot write: `removePlugins: [ 'ImageEditing' ]` because this plugin does not define `pluginName` :man_shrugging:. If I remove the plugin by a constructor then I get the error you mentioned (when the CKFinder.requires returns ImageEditing).

> article.js:45 CKEditorError: schema-cannot-extend-missing-item: C

`ImageUploadEditing` does not require `ImageEditing` plugins - so if someone remove `Image` but leave `ImageUpload` then this error will be thrown since no-one defined `image` schema item.

---

So:
1. The CKFinderUpload should require `ImageEditng` as it extends Editing part of Image.
2. All plugins should have `pluginName` define.
3. The required plugins check should be smarter. At first, we should check if current `plugins`, `extraPlugins` and `removedPlugins` are going to work and then proceed with plugins initialization in proper order.

**Comment by jodator** [comment]
I've created a follow-up for the issues I found: https://github.com/ckeditor/ckeditor5/issues/5602.

**Comment by Reinmar** [comment]
> Second finding: You cannot write: `removePlugins: [ 'ImageEditing' ]` because this plugin does not define `pluginName` 🤷‍♂. If I remove the plugin by a constructor then I get the error you mentioned (when the CKFinder.requires returns ImageEditing).

![image](https://user-images.githubusercontent.com/156149/66948091-5249d400-f054-11e9-83d2-0195a1f87f63.png)
