### ISSUE TITLE
CI fails for ckeditor/ckeditor5-build-balloon-block package

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#5856]
## Provide a description of the task

There's a single build that fails: https://travis-ci.org/ckeditor/ckeditor5-build-balloon-block

Error:

```
yarn run v1.19.2
$ stylelint --quiet --allow-empty-input 'theme/**/*.css' 'docs/**/*.css'
Error: Could not find "stylelint-config-ckeditor5". Do you need a `configBasedir`?
    at module.exports (/home/travis/build/ckeditor/ckeditor5-build-balloon-block/node_modules/stylelint/lib/utils/configurationError.js:8:27)
    at getModulePath (/home/travis/build/ckeditor/ckeditor5-build-balloon-block/node_modules/stylelint/lib/utils/getModulePath.js:23:9)
    at loadExtendedConfig (/home/travis/build/ckeditor/ckeditor5-build-balloon-block/node_modules/stylelint/lib/augmentConfig.js:181:21)
    at resultPromise.then (/home/travis/build/ckeditor/ckeditor5-build-balloon-block/node_modules/stylelint/lib/augmentConfig.js:160:11)
    at <anonymous>
error Command failed with exit code 78.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by pomek** [comment]
All 5 builds are missing `stylelint-config-ckeditor5` in dev-deps so (TBH) I am not surprised that it fails. I'll handle it.

**Comment by pomek** [comment]
![image](https://user-images.githubusercontent.com/2270764/69793622-20866a00-11c9-11ea-8e94-c45a0e7b6ab5.png)
