### ISSUE TITLE
Builder (with a watcher) crashes when a file is removed

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#62]
After #59 is finished this will happen:

```
[14:28:17] Processing '/www/ckeditor5/ckeditor5/tests/ckeditor5/path/getmodulepath.js'...
/www/ckeditor5/ckeditor5/dev/tasks/gulp/build/utils.js:149
			file.contents = new Buffer( file.contents.toString() + utils.benderLauncherCode );
			                                         ^

TypeError: Cannot read property 'toString' of null
    at DestroyableTransform._transform (/www/ckeditor5/ckeditor5/dev/tasks/gulp/build/utils.js:149:45)
    at DestroyableTransform.Transform._read (/www/ckeditor5/ckeditor5/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/www/ckeditor5/ckeditor5/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/www/ckeditor5/ckeditor5/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:335:12)
```

However, the issue is somewhere in the old code – I think that the watchers should be configured to care only about new files and changes in existing ones.

**Comment by Reinmar** [comment]
If we have too much time we can also implement removing a proper file from the dist if the watcher is notified about removing one.
