### ISSUE TITLE
editor behaves strange

### ISSUE THREAD

**Issue by danyal14** [ckeditor/ckeditor5#6215]
## 📝 Editor behaves strange, some time it doesn't allow to press backspace button, on some machines space doesn't work. And sometimes it just shuffles the text.  

````
domconverter.js:280 Uncaught DOMException: Failed to execute 'setStart' on 'Range': The offset 158 is larger than the node's length (157).
    at rr.viewRangeToDom (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:168912)
    at js.scrollToTheSelection (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:194120)
    at ro.<anonymous> (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:368982)
    at ro.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:104559)
    at ro.<anonymous> (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:367750)
    at ro.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:104559)
    at es.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:182838)
    at es.onDomEvent (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:182970)
    at dr.listenTo.useCapture (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:182749)
    at dr.fire (https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js:5:104559)
````
1. start writing press space, editor removes the space
2. while writing back space is blocked, it doesn't allow

### ✔️ Expected result

Should allow to add space and to remove using backspace.

### ❌ Actual result

you should not be able to add space when writing articles, and will not allow you to remove text.

## 📃 Other details

* Browser: Chrome Version 80.0.3987.87 (Official Build) (64-bit)
* OS: Mac Catalina & Windows 10
* CKEditor version: 5 V12
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I wasn't able to reproduce this issue with pressing space/backspace. Could you please provide more detailed information about the editor you use: how did you build it, which plugins do you use ( their versions ), what configuration do you have, do you use it with some other front-end framework? It would be also helpful if you provided more detailed steps to reproduce this issue.

**Comment by Reinmar** [comment]
It could be https://github.com/ckeditor/ckeditor5/issues/6222 related.
