### ISSUE TITLE
Editor crashes after undoing styles on a table

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#6265]
## 📝 Provide detailed reproduction steps (if any)

1. Add a table.
2. Open the table properties balloon.
3. Add a background color.
4. Put the caret in a cell.
5. Open the cell properties balloon.
6. Add a background color.
7. Undo twice.

### ✔️ Expected result

Styles are removed.

### ❌ Actual result

The editor crashes.

## 📃 Other details

**Error**
```js
ckeditorerror.js:66 Uncaught CKEditorError: attribute-operation-range-not-flat: The range to change is not flat. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-attribute-operation-range-not-flat

    at l._validate (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:54557)
    at kn.on.priority (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:380379)
    at kn.fire (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:22217)
    at kn.<computed> [as applyOperation] (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:29799)
    at E._undo (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:428562)
    at Object.callback (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:429060)
    at kn._runPendingChanges (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:384143)
    at kn.enqueueChange (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:381201)
    at E.execute (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:429034)
    at E.<anonymous> (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:29748)
```

**GIF**
![bug_cke5](https://user-images.githubusercontent.com/20988892/74519426-f31ea200-4f15-11ea-98e7-10c2103f35dc.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
If we'll add styling in a different order (starting from a table cell) there will be a different error:

```js
ckeditorerror.js:66 Uncaught CKEditorError: attribute-operation-attribute-exists: The attribute with given key already exists. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-attribute-operation-attribute-exists
 {"node":{"attributes":{"borderStyle":"solid","borderWidth":"12px"},"name":"tableCell","children":[{"name":"paragraph","children":[{"data":"yes"}]}]},"key":"borderWidth"}
    at l._validate (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:55020)
    at kn.on.priority (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:380379)
    at kn.fire (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:22217)
    at kn.<computed> [as applyOperation] (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:29799)
    at E._undo (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:428562)
    at Object.callback (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:429060)
    at kn._runPendingChanges (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:384143)
    at kn.enqueueChange (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:381201)
    at E.execute (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:429034)
    at E.<anonymous> (http://192.168.1.81:8080/build/docs/ckeditor5/latest/snippets/features/build-table-source/snippet.js:4:29748)
```
