### ISSUE TITLE
CKEditorError: ckeditor-duplicated-modules: SimpleUploadAdapter (Vuejs)

### ISSUE THREAD

**Issue by thamibn** [ckeditor/ckeditor5#6296]
## 📝 Provide detailed reproduction steps (if any)

1. I have installed ckeditor for vuejs project using this comamand 
``` npm install --save @ckeditor/ckeditor5-vue @ckeditor/ckeditor5-build-classic ```

2. Now i want to integrate simpleupload for image upload. this is what i did on the editor config of ckeditor
```
import SimpleUploadAdapter from '@ckeditor/ckeditor5-upload/src/adapters/simpleuploadadapter';

plugins: [SimpleUploadAdapter],
simpleUpload: {
            // The URL that the images are uploaded to.
            uploadUrl: 'http://tol.test/api/upload/image',

            // Headers sent along with the XMLHttpRequest to the upload server.
            headers: {}
        }
```
3. when i test it it gives me the below error
```
vue-router.esm.js?8c4f:2079 CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

    at Module.eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/version.js:146:8)
    at eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/version.js:154:30)
    at Module../node_modules/@ckeditor/ckeditor5-utils/src/version.js (http://localhost:8080/1.js:214:1)
    at __webpack_require__ (http://localhost:8080/app.js:770:30)
    at fn (http://localhost:8080/app.js:130:20)
    at eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/emittermixin.js:8:66)
    at Module../node_modules/@ckeditor/ckeditor5-utils/src/emittermixin.js (http://localhost:8080/1.js:130:1)
    at __webpack_require__ (http://localhost:8080/app.js:770:30)
    at fn (http://localhost:8080/app.js:130:20)
    at eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/observablemixin.js:2:71)
abort @ vue-router.esm.js?8c4f:2079
eval @ vue-router.esm.js?8c4f:2124
eval @ vue-router.esm.js?8c4f:1897
eval @ vue-router.esm.js?8c4f:1962
Promise.then (async)
eval @ vue-router.esm.js?8c4f:1909
eval @ vue-router.esm.js?8c4f:1930
eval @ vue-router.esm.js?8c4f:1930
flatMapComponents @ vue-router.esm.js?8c4f:1929
eval @ vue-router.esm.js?8c4f:1865
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
step @ vue-router.esm.js?8c4f:1850
step @ vue-router.esm.js?8c4f:1850
eval @ vue-router.esm.js?8c4f:1847
eval @ vue-router.esm.js?8c4f:2139
eval @ progressbar.js?d3ef:18
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
eval @ vue-router.esm.js?8c4f:1847
eval @ vue-router.esm.js?8c4f:2139
eval @ main.js?56d7:77
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
runQueue @ vue-router.esm.js?8c4f:1854
confirmTransition @ vue-router.esm.js?8c4f:2147
transitionTo @ vue-router.esm.js?8c4f:2034
init @ vue-router.esm.js?8c4f:2734
beforeCreate @ vue-router.esm.js?8c4f:1203
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
callHook @ vue.runtime.esm.js?2b0e:4213
Vue._init @ vue.runtime.esm.js?2b0e:4998
Vue @ vue.runtime.esm.js?2b0e:5079
eval @ main.js?56d7:90
./src/main.js @ app.js:7183
__webpack_require__ @ app.js:770
fn @ app.js:130
1 @ app.js:7364
__webpack_require__ @ app.js:770
(anonymous) @ app.js:908
(anonymous) @ app.js:911
Show 10 more frames

```

### ✔️ Expected result

simpleupload to be added as plugin to ckeditor.

### ❌ Actual result

```
vue-router.esm.js?8c4f:2079 CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

    at Module.eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/version.js:146:8)
    at eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/version.js:154:30)
    at Module../node_modules/@ckeditor/ckeditor5-utils/src/version.js (http://localhost:8080/1.js:214:1)
    at __webpack_require__ (http://localhost:8080/app.js:770:30)
    at fn (http://localhost:8080/app.js:130:20)
    at eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/emittermixin.js:8:66)
    at Module../node_modules/@ckeditor/ckeditor5-utils/src/emittermixin.js (http://localhost:8080/1.js:130:1)
    at __webpack_require__ (http://localhost:8080/app.js:770:30)
    at fn (http://localhost:8080/app.js:130:20)
    at eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-utils/src/observablemixin.js:2:71)
abort @ vue-router.esm.js?8c4f:2079
eval @ vue-router.esm.js?8c4f:2124
eval @ vue-router.esm.js?8c4f:1897
eval @ vue-router.esm.js?8c4f:1962
Promise.then (async)
eval @ vue-router.esm.js?8c4f:1909
eval @ vue-router.esm.js?8c4f:1930
eval @ vue-router.esm.js?8c4f:1930
flatMapComponents @ vue-router.esm.js?8c4f:1929
eval @ vue-router.esm.js?8c4f:1865
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
step @ vue-router.esm.js?8c4f:1850
step @ vue-router.esm.js?8c4f:1850
eval @ vue-router.esm.js?8c4f:1847
eval @ vue-router.esm.js?8c4f:2139
eval @ progressbar.js?d3ef:18
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
eval @ vue-router.esm.js?8c4f:1847
eval @ vue-router.esm.js?8c4f:2139
eval @ main.js?56d7:77
iterator @ vue-router.esm.js?8c4f:2120
step @ vue-router.esm.js?8c4f:1846
runQueue @ vue-router.esm.js?8c4f:1854
confirmTransition @ vue-router.esm.js?8c4f:2147
transitionTo @ vue-router.esm.js?8c4f:2034
init @ vue-router.esm.js?8c4f:2734
beforeCreate @ vue-router.esm.js?8c4f:1203
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
callHook @ vue.runtime.esm.js?2b0e:4213
Vue._init @ vue.runtime.esm.js?2b0e:4998
Vue @ vue.runtime.esm.js?2b0e:5079
eval @ main.js?56d7:90
./src/main.js @ app.js:7183
__webpack_require__ @ app.js:770
fn @ app.js:130
1 @ app.js:7364
__webpack_require__ @ app.js:770
(anonymous) @ app.js:908
(anonymous) @ app.js:911
Show 10 more frames
```

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
You cannot add a plugin to an existing build. You need to customize this build or integrate CKEditor 5 from source. See  https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html.

**Comment by thamibn** [comment]
Hi, I have followed this guide https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-the-editor-from-source

and copy exatly what the docs say,

but still i get the same error,
here is my vue.config.js
```
const path = require('path');
const webpack = require('webpack');

// added by thamie for ckeditor
const CKEditorWebpackPlugin = require('@ckeditor/ckeditor5-dev-webpack-plugin');
const { styles } = require('@ckeditor/ckeditor5-dev-utils');

function resolveSrc(_path) {
  return path.join(__dirname, _path)
}

module.exports = {
  transpileDependencies: [
    /ckeditor5-[^/\\]+[/\\]src[/\\].+\.js$/,
  ],
  configureWebpack: {
    // Set up all the aliases we use in our app.
    resolve: {
      alias: {
        'src': resolveSrc('src'),
        'chart.js': 'chart.js/dist/Chart.js'
      }
    },
    plugins: [
      new webpack.optimize.LimitChunkCountPlugin({
        maxChunks: 6
      }),
      // CKEditor needs its own plugin to be built using webpack.
      new CKEditorWebpackPlugin({
        // See https://ckeditor.com/docs/ckeditor5/latest/features/ui-language.html
        language: 'en'
      })
    ]
  },
  pwa: {
    name: 'Vue Paper Dashboard PRO',
    themeColor: '#66615B',
    msTileColor: '#66615B',
    appleMobileWebAppCapable: 'yes',
    appleMobileWebAppStatusBarStyle: '#66615B'
  },
  css: {
    // Enable CSS source maps.
    sourceMap: process.env.NODE_ENV !== 'production'
  },

  //added for ckeditor by thamie
  // Vue CLI would normally use its own loader to load .svg and .css files, however:
  //	1. The icons used by CKEditor must be loaded using raw-loader,
  //	2. The CSS used by CKEditor must be transpiled using PostCSS to load properly.
  chainWebpack: config => {
    // (1.) To handle editor icons, get the default rule for *.svg files first:
    const svgRule = config.module.rule('svg');

    // Then you can either:
    //
    // * clear all loaders for existing 'svg' rule:
    //
    //		svgRule.uses.clear();
    //
    // * or exclude ckeditor directory from node_modules:
    svgRule.exclude.add(path.join(__dirname, 'node_modules', '@ckeditor'));

    // Add an entry for *.svg files belonging to CKEditor. You can either:
    //
    // * modify the existing 'svg' rule:
    //
    //		svgRule.use( 'raw-loader' ).loader( 'raw-loader' );
    //
    // * or add a new one:
    config.module
      .rule('cke-svg')
      .test(/ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/)
      .use('raw-loader')
      .loader('raw-loader');

    // (2.) Transpile the .css files imported by the editor using PostCSS.
    // Make sure only the CSS belonging to ckeditor5-* packages is processed this way.
    config.module
      .rule('cke-css')
      .test(/ckeditor5-[^/\\]+[/\\].+\.css$/)
      .use('postcss-loader')
      .loader('postcss-loader')
      .tap(() => {
        return styles.getPostCssConfig({
          themeImporter: {
            themePath: require.resolve('@ckeditor/ckeditor5-theme-lark'),
          },
          minify: true
        });
      });
  }
};
```

here is where i test it
```

<template>
  <div class="form-group">
    <label for="ckeditor">{{ (data.label) ? data.label : '' }}</label>
    <ckeditor
      id="ckeditor"
      :class="(data.customClass) ? data.customClass : ''"
      :editor="editor"
      v-model="inputValue"
      :config="editorConfig"
    ></ckeditor>
  </div>
</template>
<script>
// ⚠️ NOTE: We don't use @ckeditor/ckeditor5-build-classic any more!
// Since we're building CKEditor from source, we use the source version of ClassicEditor.
import ClassicEditor from "@ckeditor/ckeditor5-editor-classic/src/classiceditor";

import EssentialsPlugin from "@ckeditor/ckeditor5-essentials/src/essentials";
import BoldPlugin from "@ckeditor/ckeditor5-basic-styles/src/bold";
import ItalicPlugin from "@ckeditor/ckeditor5-basic-styles/src/italic";
import LinkPlugin from "@ckeditor/ckeditor5-link/src/link";
import ParagraphPlugin from "@ckeditor/ckeditor5-paragraph/src/paragraph";

export default {
  name: "CKeditor",
  props: {
    data: Object,
    uniqueId: Number
  },
  computed: {
    inputValue: {
      get() {
        return this.value;
      },
      set(val) {
        this.$emit("input", val);
      }
    }
  },
  data() {
    return {
      editor: ClassicEditor,
      editorConfig: {
        // The configuration of the editor.
        placeholder: this.placeholder ? this.placeholder : "",
        plugins: [
          EssentialsPlugin,
          BoldPlugin,
          ItalicPlugin,
          LinkPlugin,
          ParagraphPlugin
        ],

        toolbar: {
          items: ["bold", "italic", "link", "undo", "redo"]
        }
      }
    };
  },
  methods: {}
};
</script>
<style>
</style>
```

this is the error.
```
Uncaught (in promise) CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

    at Module.eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-essentials/node_modules/@ckeditor/ckeditor5-utils/src/version.js:144:9)
    at eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-essentials/node_modules/@ckeditor/ckeditor5-utils/src/version.js:148:30)
    at Module../node_modules/@ckeditor/ckeditor5-essentials/node_modules/@ckeditor/ckeditor5-utils/src/version.js (http://localhost:8080/1.js:3792:1)
    at __webpack_require__ (http://localhost:8080/app.js:770:30)
    at fn (http://localhost:8080/app.js:130:20)
    at eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-essentials/node_modules/@ckeditor/ckeditor5-utils/src/emittermixin.js:8:66)
    at Module../node_modules/@ckeditor/ckeditor5-essentials/node_modules/@ckeditor/ckeditor5-utils/src/emittermixin.js (http://localhost:8080/1.js:3708:1)
    at __webpack_require__ (http://localhost:8080/app.js:770:30)
    at fn (http://localhost:8080/app.js:130:20)
    at eval (webpack-internal:///./node_modules/@ckeditor/ckeditor5-essentials/node_modules/@ckeditor/ckeditor5-utils/src/observablemixin.js:2:71)
```

**Comment by Mgsy** [comment]
Can you share your `package.json`? Yesterday we had a release, so maybe some of your packages are outdated.

**Comment by thamibn** [comment]
my package.json
```
{
  "name": "vue-paper-dashboard-pro",
  "version": "2.0.0",
  "private": true,
  "description": "A premium Vue.js admin dashboard for bootstrap. Coded by BinarCode, designed by Creative Tim.",
  "author": "cristi.jora <joracristi@gmail.com>",
  "scripts": {
    "build": "vue-cli-service build",
    "dev": "vue-cli-service serve --open"
  },
  "dependencies": {
    "@ckeditor/ckeditor5-alignment": "^16.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^17.0.0",
    "@ckeditor/ckeditor5-build-classic": "^16.0.0",
    "@ckeditor/ckeditor5-ckfinder": "^16.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^12.0.8",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^8.0.8",
    "@ckeditor/ckeditor5-editor-classic": "^17.0.0",
    "@ckeditor/ckeditor5-essentials": "^17.0.0",
    "@ckeditor/ckeditor5-link": "^17.0.0",
    "@ckeditor/ckeditor5-page-break": "^16.0.0",
    "@ckeditor/ckeditor5-paragraph": "^17.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^17.0.0",
    "@ckeditor/ckeditor5-upload": "^16.0.0",
    "@ckeditor/ckeditor5-vue": "^1.0.1",
    "ace-builds": "^1.4.8",
    "axios": "^0.19.1",
    "bootstrap": "^4.3.1",
    "camelcase": "^5.3.1",
    "chart.js": "^2.7.2",
    "d3": "^5.7.0",
    "datamaps": "^0.5.9",
    "element-ui": "^2.5.4",
    "fullcalendar": "^4.0.0-alpha.3",
    "google-maps": "^3.2.1",
    "js-cookie": "^2.2.1",
    "nprogress": "^0.2.0",
    "perfect-scrollbar": "0.7.1",
    "popper.js": "^1.14.7",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^0.5.1",
    "register-service-worker": "^1.5.2",
    "survey-creator": "^1.5.1",
    "survey-jquery": "^1.5.2",
    "survey-vue": "^1.5.2",
    "surveyjs-widgets": "^1.5.1",
    "sweetalert2": "^6.11.4",
    "topojson": "^3.0.2",
    "vee-validate": "^3.2.1",
    "vue": "^2.6.6",
    "vue-chartjs": "^3.3.2",
    "vue-clickaway": "^2.2.2",
    "vue-notifyjs": "^0.4.3",
    "vue-router": "^3.0.2",
    "vue-router-prefetch": "^1.4.0",
    "vue-select": "^3.4.0",
    "vue2-transitions": "^0.2.3",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.4.0",
    "@vue/cli-plugin-pwa": "^3.4.0",
    "@vue/cli-service": "^3.4.0",
    "babel-plugin-component": "^1.1.1",
    "node-sass": "^4.11.0",
    "sass-loader": "^7.1.0",
    "vue-template-compiler": "^2.6.6"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "engines": {
    "node": ">= 8.9.0",
    "npm": ">= 5.0.0"
  }
}
```

**Comment by Mgsy** [comment]
Some of your packages are at version `16.0.0`, while others are updated (`17.0.0`). Updating your packages from `16.0.0` to `17.0.0` should fix your issue.

**Comment by thamibn** [comment]
update package.json
I have just intstalled a new fresh vuejs project using vue create command and vue CLI 3, everthing works perfect.

But on the tmeplate i bought it gives me that error, even after updating the package.json

**Comment by thamibn** [comment]
It is working now, what i did i removed the `node_modules` folder and `package-lock.json` file,
i have also removed all `@ckeditor/...` package on `package.json` then followed the guide https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs.html#using-the-editor-from-source again to re-install everything again.

**Comment by Mgsy** [comment]
Great to hear that you've managed to fix it :)

**Comment by thamibn** [comment]
How can i access the uploaded image on the server the docs does not mention on which attribute i can access the image on the server, i am able to send the image to the server but i dont know how can i access it please help,
 

cannot open new issue not sure.

**Comment by ivan006** [comment]
If all ur other plugins are a certain versions e.g. ""^32.0.0" then the new plugin must also be that version
