### ISSUE TITLE
Editor crashes after inserting two mediaEmbed items to the toolbar

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#6333]
## 📝 Provide detailed reproduction steps (if any)

1. Open the editor with two `mediaEmbed` items in the toolbar (or 1 in the main toolbar + 1 in the balloon toolbar).

### ✔️ Expected result

Items are added properly.

### ❌ Actual result

The editor crashes.

## 📃 Other details
**Error**
```js
article.js:50 CKEditorError: observable-bind-rebind: Cannot bind the same property more than once. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-observable-bind-rebind
    at http://localhost:8125/ckeditor5/tests/manual/article.js:116888:11
    at Array.forEach (<anonymous>)
    at LabeledInputView.bind (http://localhost:8125/ckeditor5/tests/manual/article.js:116881:18)
    at MediaEmbedUI._setUpForm (http://localhost:8125/ckeditor5/tests/manual/article.js:91774:27)
    at Object.callback (http://localhost:8125/ckeditor5/tests/manual/article.js:91731:18)
    at ComponentFactory.create (http://localhost:8125/ckeditor5/tests/manual/article.js:100589:56)
    at http://localhost:8125/ckeditor5/tests/manual/article.js:108003:40
    at Array.map (<anonymous>)
    at ToolbarView.fillFromConfig (http://localhost:8125/ckeditor5/tests/manual/article.js:107999:16)
    at ClassicEditorUI._initToolbar (http://localhost:8125/ckeditor5/tests/manual/article.js:39720:16)
```

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Reinmar** [comment]
I guess it's a big issue if you want to have media embed buttons in the main toolbar and the block toolbar?

**Comment by Mgsy** [comment]
>I guess it's a big issue if you want to have media embed buttons in the main toolbar and the block toolbar?

That's correct.

**Comment by tomalec** [comment]
The fix is ready at https://github.com/ckeditor/ckeditor5-media-embed/pull/98
