### ISSUE TITLE
Editor crashes when pressing backspace on multiple cell selection

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#6339]
### Steps:
- open [table selection test](http://localhost:8125/ckeditor5-table/tests/manual/tableselection.html)
- select a few cells ( but more than 3-4 )
- press `backspace`

#### Actual: selection ranges also whole content below the table, editor crashes

![table_selection1](https://user-images.githubusercontent.com/34380544/75422218-5c51dc80-593c-11ea-955e-319ca6efff9d.gif)

### Errors:
```js
Uncaught CKEditorError: model-selection-range-intersects: Trying to add a range that intersects with another range in the selection. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-selection-range-intersects
 {"addedRange":{"start":{"root":"main","path":[1,0,0],"stickiness":"toNext"},"end":{"root":"main","path":[1,0,1],"stickiness":"toPrevious"}},"intersectingRange":{"start":{"root":"main","path":[1,0,0],"stickiness":"toNext"},"end":{"root":"main","path":[1,0,1],"stickiness":"toPrevious"}}}
    at LiveSelection._checkRange (http://localhost:8125/ckeditor5-table/tests/manual/tableselection.js:64799:11)
    at LiveSelection._prepareRange (http://localhost:8125/ckeditor5-table/tests/manual/tableselection.js:51647:8)
    at LiveSelection._fixGraveyardSelection (http://localhost:8125/ckeditor5-table/tests/manual/tableselection.js:51969:26)
    at Model.LiveSelection.listenTo.priority (http://localhost:8125/ckeditor5-table/tests/manual/tableselection.js:51461:10)
    at Model.fire (http://localhost:8125/ckeditor5-table/tests/manual/tableselection.js:124313:30)
    at Model.<computed> [as applyOperation] (http://localhost:8125/ckeditor5-table/tests/manual/tableselection.js:126450:16)
    at applyRemoveOperation (http://localhost:8125/ckeditor5-table/tests/manual/tableselection.js:69026:8)
    at Writer.remove (http://localhost:8125/ckeditor5-table/tests/manual/tableselection.js:68011:4)
    at http://localhost:8125/ckeditor5-table/tests/manual/tableselection.js:65923:11
    at Model.change (http://localhost:8125/ckeditor5-table/tests/manual/tableselection.js:53796:12)
```

After the initial crash, this error appears over and over again, reaching from several to even more than 100 times:
```js
Uncaught TypeError: Cannot read property 'getChildIndex' of null
    at TableUtils.getCellLocation (tableutils.js:59)
    at TableSelection.getSelectedTableCells (tableselection.js:210)
    at getSelectedTableCells.next (<anonymous>)
    at TableSelection._updateModelSelection (tableselection.js:261)
    at TableSelection.stopSelection (tableselection.js:177)
    at MouseSelectionHandler._handleMouseMove (mouseselectionhandler.js:99)
    at Document.<anonymous> (mouseselectionhandler.js:63)
    at Document.fire (emittermixin.js:209)
    at MouseEventsObserver.fire (domeventobserver.js:96)
    at MouseEventsObserver.onDomEvent (mouseeventsobserver.js:42)
```

**Comment by FilipTokarski** [comment]
My bad I didn't notice the [discussion here](https://github.com/ckeditor/ckeditor5/issues/6328). I'll close this for now as a duplicate.
