### ISSUE TITLE
Classic build throwing ckeditor-duplicated-modules on dynamic loading

### ISSUE THREAD

**Issue by 0x416c69** [ckeditor/ckeditor5#6558]
When I use <script> tag to load ckeditor.js it works correctly but when I retrieve the ckeditor.js and try to "eval" the data received, I'm getting this:

```
VM168105:5 Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

    at Object.eval (eval at ExecuteJSCode (http://localhost/Interface/JS/agc.js:4094:5), <anonymous>:5:7418)
    at Object.eval (eval at ExecuteJSCode (http://localhost/Interface/JS/agc.js:4094:5), <anonymous>:5:7533)
    at i (eval at ExecuteJSCode (http://localhost/Interface/JS/agc.js:4094:5), <anonymous>:5:2564)
    at Module.eval (eval at ExecuteJSCode (http://localhost/Interface/JS/agc.js:4094:5), <anonymous>:5:108269)
    at i (eval at ExecuteJSCode (http://localhost/Interface/JS/agc.js:4094:5), <anonymous>:5:2564)
    at eval (eval at ExecuteJSCode (http://localhost/Interface/JS/agc.js:4094:5), <anonymous>:5:3363)
    at eval (eval at ExecuteJSCode (http://localhost/Interface/JS/agc.js:4094:5), <anonymous>:5:3374)
    at eval (eval at ExecuteJSCode (http://localhost/Interface/JS/agc.js:4094:5), <anonymous>:5:2425)
    at eval (eval at ExecuteJSCode (http://localhost/Interface/JS/agc.js:4094:5), <anonymous>:5:2429)
    at ExecuteJSCode (http://localhost/Interface/JS/agc.js:4094:5)
```

Every other .js library I have, I dynamically load it with my method and they have no problems.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I'm not sure what you mean here. Could you provide your editor configuration and step by step path to reproduce this issue?
BTW, you can also check if all the CKEditor plugins you have installed, are of the same version.

**Comment by 0x416c69** [comment]
> BTW, you can also check if all the CKEditor plugins you have installed, are of the same version.

If there was a problem with the build, it wouldn't get loaded successfully using <script> tag.

I'm trying to load ckeditor.js by downloading its code using ajax and then loading ckeditor to my page using "eval()" function.

I think an easy reproduce would be
```js
$.getScript("/Path/To/ckeditor.js", function () { // do things });
``` (Using jquery)

**Comment by FilipTokarski** [comment]
Is there any particular reason you wan to use `eval()` here? It would be easier to look into this issue, if you provided some more context of how you use CKEditor.

**Comment by 0x416c69** [comment]
I have a website which I use ckeditor in some of the pages (not all) and I use $.getScript to load ckeditor if it's not already loaded and it's required.

$.getScript internally uses eval, it's really fine with every other javascript libraries except ckeditor and it's kind of weird, I don't really know node js and it's really hard for me to debug it even more.

**Comment by FilipTokarski** [comment]
Ok, then please try using it like this:
```js
$.getScript( "../path/to/ckeditor.js", function () {
    ClassicEditor.create( document.querySelector( '#editor' ) )
    .then( editor => {
        window.editor = editor;
    } )
    .catch( error => {
        console.error( 'There was a problem initializing the editor.', error );
    } );
} );
```

**Comment by 0x416c69** [comment]
Yeah, right, it was my bad.

I'm sorry, I had to debug it for some time to finally find out.
