### ISSUE TITLE
CKEditor 5 doesn't work in Edge

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#657]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

1.0.0-alpha1

## 📋 Steps to reproduce

1. Open CKEditor 5 in Edge.

## ✅ Expected result
The editor loads properly.

## ❎ Actual result
The editor doesn't load and there is the error in the console.

## 📃 Other details that might be useful
Error from the console:
```
TypeError: Object doesn't support property or method 'Symbol.iterator'
   at search (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:21177:5)
   at Generator.prototype.next (native code)
   at search (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:21181:7)
   at Generator.prototype.next (native code)
   at Template.prototype.getViews (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:21187:3)
   at Generator.prototype.next (native code)
   at View.prototype.registerChildren (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:3467:9)
   at View.prototype.render (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:3592:4)
   at StickyPanelView.prototype.render (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:53968:3)
   at Anonymous function (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:23341:5)
article.js (67106,3)
```

Browser: Edge 15

**Comment by szymonkups** [comment]
> It occurs because NodeList still does not support Symbol.iterator. The same errors occur when I test BrowserStack.

And ofcourse we fixed it but it's still work in progress.

**Comment by oleq** [comment]
@Mgsy Can you confirm the things get back to normal after the fix?

**Comment by Mgsy** [comment]
>@Mgsy Can you confirm the things get back to normal after the fix?

Editor loads properly and everything is fine 👌
