### ISSUE TITLE
mobile problem

### ISSUE THREAD

**Issue by maxbilisim** [ckeditor/ckeditor5#6580]
Buttons don't work after some time on Android

**Comment by Mgsy** [comment]
Hi, can you share more details about the issue? We didn't observe such behaviour, so some screencast and step-by-step instruction to reproduce would be useful.

**Comment by maxbilisim** [comment]
Hi,
The editor does not work after a while while using the toolbar

Youtube link :
https://www.youtube.com/watch?v=7TctT-6gwaI

Redmi Note 8
Android 9

Browsers tested
Firefox, Chrome, Mi Default browser

Thank you

**Comment by FilipTokarski** [comment]
I can confirm this (Redmi Note 8T, Android 9, MIUI 11, Gboard keyboard)
  
Steps to reproduce:
1. Click bold on toolbar
2. Type something
3. Click bold once again to turn it off
4. Type
- previously typed text jumps and repeats itself
5. Click bold again

```js
Uncaught CKEditorError: view-renderer-filler-was-lost: The inline filler node was lost. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-view-renderer-filler-was-lost

    at Qn._removeInlineFiller (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:228837)
    at Qn.render (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:226900)
    at hs._render (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:263526)
    at hs.<anonymous> (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:260059)
    at hs.fire (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:159513)
    at hs.change (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:262821)
    at hs._disableRendering (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:263432)
    at _c.Ks.listenTo.priority (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:319252)
    at _c.fire (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:159513)
    at _c._runPendingChanges (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:399955)
```

![9_android1](https://user-images.githubusercontent.com/34380544/78893931-74089e80-7a6c-11ea-9a57-003d8b9ffbff.gif)

**Comment by Mgsy** [comment]
Thanks @FilipTokarski for confirmation 👍 

@maxbilisim, unfortunately, this is a known issue related to GBoard. We're aware of issues related to Android, but frankly speaking, those are not trivial to solve and will require some huge effort from our side. 

You'll find more information about the problem in this ticket - https://github.com/ckeditor/ckeditor5/issues/1786. For now, I can only recommend you use a different keyboard, i.e. SwiftKeyboard.
