### ISSUE TITLE
Editor crashes after pressing Enter in a to-do list item with soft-break

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#6585]
## 📝 Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/ckeditor-5/demo/
2. Put the caret at the end of the paragraph
3. Press <kbd>Shift</kbd> + <kbd>Enter</kbd>
4. Transform the block into the to-do list
5. Move the selection to the end of the previous line
6. Press <kbd>Enter</kbd>

### ❌ Actual result

The editor crashes.

## 📃 Other details
**Error**

```js
Uncaught CKEditorError: view-writer-cannot-break-empty-element
    at Cn._breakAttributes (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:221317)
    at Cn.breakAttributes (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:213368)
    at Cs.Ks.downcastDispatcher.on.priority (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:321063)
    at Cs.fire (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:159513)
    at Cs.convertSelection (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:293257)
    at https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:319424
    at hs.change (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:262600)
    at Za.Ks.listenTo.priority (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:319336)
    at Za.fire (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:159513)
    at Za._handleChangeBlock (https://ckeditor.com/assets/libs/ckeditor5/18.0.0/ckeditor.js:5:381807)
```

It seems to not be a regression, as I can reproduce it in v15.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by wwalc** [comment]
Sounds similar to #5866 ?

**Comment by Reinmar** [comment]
For 99% that's a DUP, but only resolving the original "todo lists's mapping is completly broken" will tell us that for 100%.
