### ISSUE TITLE
Media embed does not clear its LiveRange

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#6806]
Found by @FilipTokarski in table paste scenario.

### Steps to reproduce:

1. Go to table test
2. Copy `Table with 2 tbody` or `Table with no tbody`
3. Paste it into the big table
4. Select the big table and press `delete`

Expected: big table is deleted

Actual:
```js
Uncaught CKEditorError: model-createPositionAt-offset-required: Model#createPositionAt() requires the offset when the first parameter is a model item. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-createPositionAt-offset-required

    at Function._createAt (http://localhost:8125/ckeditor5-table/tests/manual/table.js:61264:11)
    at new Range (http://localhost:8125/ckeditor5-table/tests/manual/table.js:61560:66)
    at LiveRange._getTransformedByMove (http://localhost:8125/ckeditor5-table/tests/manual/table.js:62314:17)
    at LiveRange._getTransformedByMoveOperation (http://localhost:8125/ckeditor5-table/tests/manual/table.js:62096:15)
    at LiveRange.getTransformedByOperation (http://localhost:8125/ckeditor5-table/tests/manual/table.js:61968:17)
    at LiveRange.transform (http://localhost:8125/ckeditor5-table/tests/manual/table.js:53137:22)
    at Model.listenTo.priority (http://localhost:8125/ckeditor5-table/tests/manual/table.js:53125:14)
    at Model.fire (http://localhost:8125/ckeditor5-table/tests/manual/table.js:128091:30)
    at Model.<computed> [as applyOperation] (http://localhost:8125/ckeditor5-table/tests/manual/table.js:130254:16)
    at applyRemoveOperation (http://localhost:8125/ckeditor5-table/tests/manual/table.js:69302:8)
```

![12_table_4](https://user-images.githubusercontent.com/34380544/81668314-c9a5e180-9444-11ea-9aba-d86f50c5c165.gif)

_Originally posted by @FilipTokarski in https://github.com/ckeditor/ckeditor5/pull/6786#issuecomment-627230047_

**Comment by jodator** [comment]
My findings.

I've logged every `LiveRange` creation by assigning and unique id in its contructor. Then I've logged when it was detached and when the problem might occur in `boundWithDocumnet()` listener.

The media embed range is created somewhere here:

![](https://user-images.githubusercontent.com/247363/81799003-ff180100-9510-11ea-9eee-6a3d50d78a67.png)

And it never gets cleared (here is after many selection changes):

![](https://user-images.githubusercontent.com/247363/81799213-4ef6c800-9511-11ea-8878-b780464e7b5c.png)

Probably adding a detach to setTimeout will remove this error. But this might be a problem with using `LiveRanges`. Another clue is to finally use markers for this and properly mange them in Media Embedd.
