### ISSUE TITLE
Travis is failing after "restart build"

### ISSUE THREAD

**Issue by niegowski** [ckeditor/ckeditor5#7244]
After "restart build" following happens on https://travis-ci.org/github/ckeditor/ckeditor5/builds/688837664:

```
Uploading combined code coverage report…
/home/travis/build/ckeditor/ckeditor5/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 422 {"message":"service_job_id (688837665) must be unique for Travis Jobs not supplying a Coveralls Repo Token","error":true}
child_process.js:669
    throw err;
    ^
Error: Command failed: npx coveralls < .out/combined_lcov.info
/home/travis/build/ckeditor/ckeditor5/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Bad response: 422 {"message":"service_job_id (688837665) must be unique for Travis Jobs not supplying a Coveralls Repo Token","error":true}
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.<anonymous> (/home/travis/build/ckeditor/ckeditor5/scripts/continuous-integration-script.js:94:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by mlewand** [comment]
Interestingly the id after restarting no longer matches the build number anymore - this should mean it is unique. Unless another build already used this job id? Needs further investigation.

**Comment by mlewand** [comment]
Ok I just used `i/7244-travis-is-failing-after-restart-build` branch to test this case and the first build was fine. After restarting it it failed with the exact same error - so it looks like we have the root cause nailed.

https://travis-ci.org/github/ckeditor/ckeditor5/builds/689555227

I'll check if providing coveralls token will solve it (as the message suggests) - might be that then it has an ability to override given jobid.

**Comment by mlewand** [comment]
Unfortunately adding Coverall tokens doesn't solve the problem.

**Comment by mlewand** [comment]
I added a summary of the struggle in [main comment of the PR](https://github.com/ckeditor/ckeditor5/pull/7260#issue-421365190).
