### ISSUE TITLE
Update coverage library in `ckeditor5-dev`

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5#7396]
## Provide a description of the task

`ckeditor5-dev` uses `istanbul` at `0.4.5` version which is no longer maintained - see https://github.com/gotwarlost/istanbul.

The new package is named `nyc` - https://istanbul.js.org/.

The current package doesn't allow to use `async/await` syntax in tests.

```
istanbul cover _mocha packages/*/tests -- --recursive --timeout 5000
 dev-env/index
   releaseSubRepositories()
Failed to parse file: /Users/maciejbukowski/workspace/ckeditor5-dev/packages/ckeditor5-dev-env/lib/index.js
Transformation error; return original code
Error: Line 39: Unexpected identifier
   at constructError (/Users/maciejbukowski/workspace/ckeditor5-dev/node_modules/esprima/esprima.js:2407:21)
   at createError (/Users/maciejbukowski/workspace/ckeditor5-dev/node_modules/esprima/esprima.js:2426:17)
   at unexpectedTokenError (/Users/maciejbukowski/workspace/ckeditor5-dev/node_modules/esprima/esprima.js:2500:13)
   at throwUnexpectedToken (/Users/maciejbukowski/workspace/ckeditor5-dev/node_modules/esprima/esprima.js:2505:15)
   at expect (/Users/maciejbukowski/workspace/ckeditor5-dev/node_modules/esprima/esprima.js:2523:13)
   at expectCommaSeparator (/Users/maciejbukowski/workspace/ckeditor5-dev/node_modules/esprima/esprima.js:2547:13)
   at parseObjectInitializer (/Users/maciejbukowski/workspace/ckeditor5-dev/node_modules/esprima/esprima.js:3053:17)
   at inheritCoverGrammar (/Users/maciejbukowski/workspace/ckeditor5-dev/node_modules/esprima/esprima.js:2681:18)
   at parsePrimaryExpression (/Users/maciejbukowski/workspace/ckeditor5-dev/node_modules/esprima/esprima.js:3247:20)
   at inheritCoverGrammar (/Users/maciejbukowski/workspace/ckeditor5-dev/node_modules/esprima/esprima.js:2681:18)
```

cc @pomek.

**Comment by ma2ciek** [comment]
I just tested `./node_modules/.bin/nyc yarn test` after installing `nyc` and it works fine with our codebase including `async/await`.

**Comment by pomek** [comment]
If it works, PR will be appreciated.

**Comment by pomek** [comment]
> The current package doesn't allow to use async/await syntax in tests.

To be more precise: it just ends with an ugly error that makes the build green. So for now, we have broken CI in the ckeditor5-dev repository.
