### ISSUE TITLE
Crash when adding special character on latest `release` docs

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#7464]
## 📝 Provide detailed reproduction steps (if any)

1. On latest `release` branch build docs and go to `features/special-characters.html`
2. Try to add a special character

### ✔️ Expected result

Special character is added
  
### ❌ Actual result

Editor crashes:
  
```js
Uncaught CKEditorError: model-position-parent-incorrect: Position parent have to be a element or document fragment. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-position-parent-incorrect

    at Function._createAt (http://localhost:8080/build/docs/ckeditor5/latest/snippets/features/special-characters-source/snippet.js:4:14756)
    at Function._createIn (http://localhost:8080/build/docs/ckeditor5/latest/snippets/features/special-characters-source/snippet.js:4:7804)
    at kn.createRangeIn (http://localhost:8080/build/docs/ckeditor5/latest/snippets/features/special-characters-source/snippet.js:4:421383)
    at http://localhost:8080/build/docs/ckeditor5/latest/snippets/features/special-characters-source/snippet.js:4:508219
    at y._onInsertContent (http://localhost:8080/build/docs/ckeditor5/latest/snippets/features/special-characters-source/snippet.js:4:508512)
    at kn.listenTo.priority (http://localhost:8080/build/docs/ckeditor5/latest/snippets/features/special-characters-source/snippet.js:4:507587)
    at kn.fire (http://localhost:8080/build/docs/ckeditor5/latest/snippets/features/special-characters-source/snippet.js:4:26312)
    at kn.<computed> [as insertContent] (http://localhost:8080/build/docs/ckeditor5/latest/snippets/features/special-characters-source/snippet.js:4:35030)
    at Object.callback (http://localhost:8080/build/docs/ckeditor5/latest/snippets/features/special-characters-source/snippet.js:4:425452)
    at kn._runPendingChanges (http://localhost:8080/build/docs/ckeditor5/latest/snippets/features/special-characters-source/snippet.js:4:421896)
```

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by Mgsy** [comment]
It's not docs-specific. I can reproduce it also in manual tests.

**Comment by pomek** [comment]
Bisect result: https://github.com/ckeditor/ckeditor5/commit/c0c0d74513b95cf7c1447d6309a1c2c3ef5a4602
