### ISSUE TITLE
Manual tests script does not work

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#7769]
## 📝 Provide detailed reproduction steps (if any)

`yarn run manual -f ckeditor5` ends with errors.

```
Module build failed (from ./node_modules/@ckeditor/ckeditor5-dev-webpack-plugin/lib/translatesourceloader.js):
SyntaxError: Assigning to rvalue (75:4)
    at Parser.pp$4.raise (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/@ckeditor/ckeditor5-dev-utils/node_modules/acorn/dist/acorn.js:2825:15)
    at Parser.pp$2.toAssignable (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/@ckeditor/ckeditor5-dev-utils/node_modules/acorn/dist/acorn.js:1693:14)
    at Parser.pp$3.parseMaybeAssign (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/@ckeditor/ckeditor5-dev-utils/node_modules/acorn/dist/acorn.js:1973:49)
    at Parser.pp$3.parseExpression (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/@ckeditor/ckeditor5-dev-utils/node_modules/acorn/dist/acorn.js:1933:21)
    at Parser.pp$1.parseStatement (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/@ckeditor/ckeditor5-dev-utils/node_modules/acorn/dist/acorn.js:877:47)
    at Parser.pp$1.parseBlock (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/@ckeditor/ckeditor5-dev-utils/node_modules/acorn/dist/acorn.js:1161:23)
    at Parser.pp$3.parseFunctionBody (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/@ckeditor/ckeditor5-dev-utils/node_modules/acorn/dist/acorn.js:2671:24)
    at Parser.pp$3.parseArrowExpression (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/@ckeditor/ckeditor5-dev-utils/node_modules/acorn/dist/acorn.js:2634:10)
    at Parser.pp$3.parseParenArrowList (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/@ckeditor/ckeditor5-dev-utils/node_modules/acorn/dist/acorn.js:2366:17)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/pomek/Projects/ckeditor/ckeditor5/node_modules/@ckeditor/ckeditor5-dev-utils/node_modules/acorn/dist/acorn.js:2332:21)
```

![image](https://user-images.githubusercontent.com/2270764/89267198-317c5a80-d637-11ea-8d6c-4b1005316b35.png)

Worked fine before merging https://github.com/ckeditor/ckeditor5-dev/pull/662.

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment]
It's working while installing deps without removing `yarn.lock`. However, after removing the file then executing `yarn install`, it fails and produces the error.

**Comment by ma2ciek** [comment]
I don't feel that this change is in any way connected with the [ckeditor/ckeditor5-dev#662](https://github.com/ckeditor/ckeditor5-dev/pull/662). It seems that the parser has some problem while parsing a file, but it's hard to guess what is the root of the problem as the error message is quite short.

**Comment by pomek** [comment]
My bad. Sorry.

I made a syntax error in one of the source files. I also added a `console.log()` a few lines later and assumes that my change must be ok.

![image](https://user-images.githubusercontent.com/2270764/89274926-e287f280-d641-11ea-820a-da3d7e37317d.png)
