### ISSUE TITLE
Editor crashes after deleting 'empty link'

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#788]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor

Latest master.

## 📋 Steps to reproduce

1. Go to http://localhost:8125/ckeditor5-core/tests/manual/article.html.
2. Put the caret at the end of the `Paragraph`.
3. Open link balloon and press `Save`.
4. Press <kbd>Backspace</kbd>.

## ✅ Expected result

Text deletes properly.

## ❎ Actual result

Editor crashes.

## 📃 Other details that might be useful

**Errors**

```
ckeditorerror.js:46 Uncaught CKEditorError: model-textproxy-wrong-offsetintext: Given offsetInText value is incorrect. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#model-textproxy-wrong-offsetintext
    at new TextProxy (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:9128:10)
    at TreeWalker._previous (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:11952:17)
    at TreeWalker.next (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:11814:16)
    at modifySelection (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:53663:26)
    at Model.modifySelection (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:41398:83)
    at Model.on (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:3977:32)
    at Model.fire (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:2341:29)
    at Model.(anonymous function) [as modifySelection] (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:3981:16)
    at Widget._getObjectElementNextToSelection (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:63812:9)
    at Widget._handleDelete (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:63666:30)

ckeditorerror.js:46 Uncaught CKEditorError: view-renderer-filler-was-lost: The inline filler node was lost. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#view-renderer-filler-was-lost
    at Renderer._removeInlineFiller (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:38649:10)
    at Renderer.render (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:38486:9)
    at Document.render (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:35060:17)
    at Document.on (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:3977:32)
    at Document.fire (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:2341:29)
    at Document.(anonymous function) [as render] (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:3981:16)
    at MutationObserver._onMutations (http://192.168.20.71:8125/ckeditor5-core/tests/manual/article.js:27692:17)
```

**GIF**

![bug_cke5](https://user-images.githubusercontent.com/20988892/35388155-eb66c296-01d2-11e8-9660-a9091a43fd4e.gif)

**Notes**
- After step 3, `editor.getData()` returns just `"<p>Paragraph</p>"`
- If you put the selection at the end of the `Paragraph`, link balloon will open
- Probably related - https://github.com/ckeditor/ckeditor5/issues/787

**Other information**
OS: All platforms
Browser: All browsers

**Comment by Reinmar** [comment]
Could you try to bisect it?

**Comment by Mgsy** [comment]
>Could you try to bisect it?

I've started from checking previous CKE5 versions and it looks like this bug exists since... [v0.3.0](https://ckeditor5.github.io/releases/v0.3.0/)

**Comment by scofalik** [comment]
Will be fixed by https://github.com/ckeditor/ckeditor5-link/issues/169

**Comment by oleq** [comment]
☝️

**Comment by Mgsy** [comment]
Fixed by https://github.com/ckeditor/ckeditor5-link/issues/169.
