### ISSUE TITLE
Running `gulp update --npm-update` steals some packages from subpackages

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#79]
I've executed `gulp update --npm-update` in the main repo. Then I got this in the core repo:

```
(t/52b 797101d) p@m /www/ckeditor5/ckeditor5-core> gulp
module.js:341
    throw err;
    ^

Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/www/ckeditor5/ckeditor5-core/node_modules/gulp-util/lib/PluginError.js:5:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)


(master 8495e07) p@m /www/ckeditor5/ckeditor5-core> npm install
npm WARN skippingAction Module is inside a symlinked module: not running update ckeditor5-core@0.0.1-0.dev node_modules/ckeditor5/node_modules/ckeditor5-core
ckeditor5-core@0.0.1-0.dev /www/ckeditor5/ckeditor5-core
├─┬ gulp@3.9.0
│ └── semver@4.3.6
├─┬ gulp-jscs@3.0.2
│ └─┬ jscs@2.9.0
│   └─┬ prompt@0.2.14
│     └─┬ winston@0.8.3
│       └── colors@0.6.2
├─┬ gulp-util@3.0.7
│ └── object-assign@3.0.0
└─┬ jshint@2.9.1
  └─┬ htmlparser2@3.8.3
    └─┬ domutils@1.5.1
      └─┬ dom-serializer@0.1.0
        └── entities@1.1.1

npm WARN EPACKAGEJSON ckeditor5-core@0.0.1-0.dev license should be a valid SPDX license expression
(master 8495e07) p@m /www/ckeditor5/ckeditor5-core>
```

**(You can't see colors here, but the modules which were missing are: semver, colors, object-assign and entities.)**

I'm 100% sure that I've got all the packages there before running `gulp update`, so something went wrong. This is actually very weird because npm was supposed to not touch symlinked packages ;/ And it's even more weird that only some of the packages were stolen from the core repo ;/

**Comment by szymonkups** [comment]
I was trying to reproduce the issue but without a success. My NPM version is `3.7.2`.

**Comment by Reinmar** [comment]
Still the same on npm 3.7.3 ;/. I'm checking this by simply running `gulp update --npm-update` and then trying `gulp lint` in ckeditor5-core.

**Comment by Reinmar** [comment]
This time I got:

```
(master e44c7bf) p@m /www/ckeditor5/ckeditor5-core> gulp lint
module.js:341
    throw err;
    ^

Error: Cannot find module 'orchestrator'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/www/ckeditor5/ckeditor5-core/node_modules/gulp/index.js:4:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by Reinmar** [comment]
I tested it again and now it was fine ;/ It seems to be a npm issue :(.

**Comment by Reinmar** [comment]
I'm having this issue from time to time when I run `gulp update` or `npm install` (not sure which of them) in `ckeditor5`. Super irritating because npm is not able to instal missing deps in sub repos and I have to reinstall everything from scratch. This is very weird ;/

**Comment by pjasiun** [comment]
Same here. Yesterday I got random errors when I run, `gulp update`, but I assume it was because I had `gulp build --watch` run in the separate tab.

**Comment by Reinmar** [comment]
Eee... not sure how's that related. Sounds like a separate issue, if an issue at all.

**Comment by Reinmar** [comment]
This will not be applicable soon (after we switch to mgit2), so I'm closing it.
