### ISSUE TITLE
Schema error thrown when running the "Inline editor" example

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#7905]
## 📝 Provide detailed reproduction steps (if any)

1.  Build docs for production
2.  Go to http://fake.ckeditor.com/ck/5/ckeditor5/build/docs/ckeditor5/latest/examples/builds/inline-editor.html

### ✔️ Expected result

No errors thrown.

### ❌ Actual result

```
CKEditorError: schema-cannot-extend-missing-item: Cannot extend an item which was not registered yet. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-schema-cannot-extend-missing-item
 {"itemName":"image"}
    at Ut.extend (http://fake.ckeditor.com/ck/5/ckeditor5/build/docs/ckeditor5/latest/snippets/examples/inline-editor/snippet.js:4:384128)
    at c._registerSchema (http://fake.ckeditor.com/ck/5/ckeditor5/build/docs/ckeditor5/latest/snippets/examples/inline-editor/snippet.js:4:609166)
    at c.init (http://fake.ckeditor.com/ck/5/ckeditor5/build/docs/ckeditor5/latest/snippets/examples/inline-editor/snippet.js:4:609046)
(anonymous) @ snippet.js:4
Promise.catch (async)
(anonymous) @ snippet.js:4
(anonymous) @ snippet.js:4
n @ snippet.js:4
(anonymous) @ snippet.js:4
(anonymous) @ snippet.js:4
```

## 📃 Other details

*   Browser: Any
*   OS: Mac
*   CKEditor version: release (3928dab)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by jodator** [comment]
Closed in the `release` branch.
