### ISSUE TITLE
Failed on runing 'npm run docs'

### ISSUE THREAD

**Issue by Calvin-he** [ckeditor/ckeditor5#794]
## 🐞 Is this a bug report or feature request? (choose one)

- Bug report

## 💻 Version of CKEditor
v1.0.0-alpha.2

## 📋 Steps to reproduce

1. npm run install-optional-dependencies
2. npm run docs

## ❎ Actual result
 Error log shows on console

## 📃 Other details that might be useful
ERROR in ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/build-classic-source.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-build-classic/src/ckeditor' in '/home/dev/ckeditor5/node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets'
 @ ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/build-classic-source.js 8:0-75
    at webpack (/home/dev/ckeditor5/scripts/docs/snippet-adapter/snippetadapter.js:166:13)
    at emitRecords.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:265:13)
    at Compiler.emitRecords (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:350:15)
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:1050:13)
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:958:16
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/dev/ckeditor5/node_modules/umberto/hexo/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/dev/ckeditor5/node_modules/graceful-fs/graceful-fs.js:43:10
Live snippet <p>{@snippet build-classic-source}</p> generation error in ckeditor5/1.0.0-alpha.2/examples/builds/classic-editor.md: Error: Hash: 3c4e0edb13edb8f1cc43
Version: webpack 3.10.0
Time: 377ms
         Asset     Size  Chunks             Chunk Names
    snippet.js  3.12 kB       0  [emitted]  main
snippet.js.map  3.08 kB       0  [emitted]  main
   [0] ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/build-classic-source.js 268 bytes {0} [built]

ERROR in ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/build-classic-source.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-build-classic/src/ckeditor' in '/home/dev/ckeditor5/node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets'
 @ ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/build-classic-source.js 8:0-75
    at webpack (/home/dev/ckeditor5/scripts/docs/snippet-adapter/snippetadapter.js:166:13)
    at emitRecords.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:265:13)
    at Compiler.emitRecords (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:350:15)
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:1050:13)
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:958:16
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/dev/ckeditor5/node_modules/umberto/hexo/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/dev/ckeditor5/node_modules/graceful-fs/graceful-fs.js:43:10
Live snippet <p>{@snippet features/ui-language}</p> generation error in ckeditor5/1.0.0-alpha.2/features/ui-language.md: Error: Hash: 39b9a83a5c1c563c4de8
Version: webpack 3.10.0
Time: 402ms
         Asset     Size  Chunks             Chunk Names
    snippet.js  3.36 kB       0  [emitted]  main
snippet.js.map  3.45 kB       0  [emitted]  main
   [0] ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/features/ui-language.js 512 bytes {0} [built]

ERROR in ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/features/ui-language.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-build-classic/src/ckeditor' in '/home/dev/ckeditor5/node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/features'
 @ ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/features/ui-language.js 10:0-75
    at webpack (/home/dev/ckeditor5/scripts/docs/snippet-adapter/snippetadapter.js:166:13)
    at emitRecords.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:265:13)
    at Compiler.emitRecords (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:350:15)
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:1050:13)
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:958:16
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/dev/ckeditor5/node_modules/umberto/hexo/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/dev/ckeditor5/node_modules/graceful-fs/graceful-fs.js:43:10
Live snippet <p>{@snippet examples/balloon-editor}</p> generation error in ckeditor5/1.0.0-alpha.2/examples/builds/balloon-editor.md: Error: Hash: 54f0344c04ae2d920589
Version: webpack 3.10.0
Time: 356ms
         Asset     Size  Chunks             Chunk Names
    snippet.js  3.54 kB       0  [emitted]  main
snippet.js.map   3.5 kB       0  [emitted]  main
   [0] ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples/balloon-editor.js 576 bytes {0} [built]

ERROR in ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples/balloon-editor.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-build-balloon/src/ckeditor' in '/home/dev/ckeditor5/node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples'
 @ ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples/balloon-editor.js 8:0-75

ERROR in ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples/balloon-editor.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-cloudservices/tests/_utils/cloudservices-config' in '/home/dev/ckeditor5/node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples'
 @ ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples/balloon-editor.js 10:0-96
    at webpack (/home/dev/ckeditor5/scripts/docs/snippet-adapter/snippetadapter.js:166:13)
    at emitRecords.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:265:13)
    at Compiler.emitRecords (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:350:15)
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:1050:13)
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:958:16
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/dev/ckeditor5/node_modules/umberto/hexo/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/dev/ckeditor5/node_modules/graceful-fs/graceful-fs.js:43:10
Live snippet <p>{@snippet examples/inline-editor}</p> generation error in ckeditor5/1.0.0-alpha.2/examples/builds/inline-editor.md: Error: Hash: 7bee35f002a5f2a26590
Version: webpack 3.10.0
Time: 325ms
         Asset     Size  Chunks             Chunk Names
    snippet.js  4.27 kB       0  [emitted]  main
snippet.js.map  4.46 kB       0  [emitted]  main
   [0] ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples/inline-editor.js 1.31 kB {0} [built]

ERROR in ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples/inline-editor.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-build-inline/src/ckeditor' in '/home/dev/ckeditor5/node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples'
 @ ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples/inline-editor.js 8:0-73

ERROR in ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples/inline-editor.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-cloudservices/tests/_utils/cloudservices-config' in '/home/dev/ckeditor5/node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples'
 @ ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples/inline-editor.js 9:0-96
    at webpack (/home/dev/ckeditor5/scripts/docs/snippet-adapter/snippetadapter.js:166:13)
    at emitRecords.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:265:13)
    at Compiler.emitRecords (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:350:15)
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:1050:13)
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:958:16
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/dev/ckeditor5/node_modules/umberto/hexo/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/dev/ckeditor5/node_modules/graceful-fs/graceful-fs.js:43:10
Failed to convert {@link features/image#Image-styles image styles} tag in ckeditor5/1.0.0-alpha.2/examples/builds/inline-editor.md
Live snippet <p>{@snippet examples/classic-editor}</p> generation error in ckeditor5/1.0.0-alpha.2/examples/builds/classic-editor.md: Error: Hash: a8ad46714b52af38d878
Version: webpack 3.10.0
Time: 106ms
         Asset     Size  Chunks             Chunk Names
    snippet.js  3.43 kB       0  [emitted]  main
snippet.js.map   3.5 kB       0  [emitted]  main
   [0] ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples/classic-editor.js 557 bytes {0} [built]

ERROR in ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples/classic-editor.js
Module not found: Error: Can't resolve '@ckeditor/ckeditor5-cloudservices/tests/_utils/cloudservices-config' in '/home/dev/ckeditor5/node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples'
 @ ./node_modules/umberto/hexo/source/ckeditor5/1.0.0-alpha.2/_snippets/examples/classic-editor.js 8:0-96
    at webpack (/home/dev/ckeditor5/scripts/docs/snippet-adapter/snippetadapter.js:166:13)
    at emitRecords.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:265:13)
    at Compiler.emitRecords (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/webpack/lib/Compiler.js:350:15)
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:1050:13)
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/async/dist/async.js:958:16
    at /home/dev/ckeditor5/scripts/docs/snippet-adapter/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/dev/ckeditor5/node_modules/umberto/hexo/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/dev/ckeditor5/node_modules/graceful-fs/graceful-fs.js:43:10

**Comment by AnnaTomanek** [comment]
Hi, thanks for reporting this issue. We've recently changed the way that the documentation is built, removing the `npm run install-optional-dependencies` step. However, the [stable version of the documentation](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/contributing/development-environment.html#generating-documentation) (which is based on the latest official release) hasn't been updated yet.

You can find the up-to-date instructions in the nightly documentation that is based on the latest dev version: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/contributing/development-environment.html#generating-documentation

Sorry for the confusion! Until we reach a stable stage, it's a bit tricky to maintain both...
