### ISSUE TITLE
SellectAll does not select all with blockquote and table

### ISSUE THREAD

**Issue by dkrahn** [ckeditor/ckeditor5#7978]
## 📝 Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html
2. In the console run `editor.setData('<blockquote><p>blockquote</p><figure class="table"><table><tbody><tr><td>Table</td></tr></tbody></table></figure></blockquote>')`
3. Select all with `Ctrl + A`

### ✔️ Expected result

Expected to select all content in the editor.

### ❌ Actual result

Only selects first part os the text outside the table.

## 📃 Other details

If first and last elements of the editor are tables, it doesn't sellect all elements.

* Browser: Chrome
* OS: Windows
* CKEditor version: 22.0.0
* Installed CKEditor plugins: [Clipboard, Enter, SelectAllEditing, SelectAllUI, SelectAll, ShiftEnter, Input, Delete, Typing, UndoEditing, Undo, Essentials, AlignmentEditing, AlignmentUI, Alignment, FontSizeEditing, FontSize, FontFamilyEditing, FontFamily, FontColorEditing, FontColorUI, FontColor, FontBackgroundColorEditing, FontBackgroundColorUI, FontBackgroundColor, PendingActions, FileRepository, CKFinderUploadAdapter, Autoformat, BoldEditing, Bold, ItalicEditing, Italic, StrikethroughEditing, Strikethrough, UnderlineEditing, Underline, BlockQuoteEditing, BlockQuote, Notification, ImageEditing, TwoStepCaretMovement, LinkEditing, CKFinderEditing, CKFinderUI, CKFinder, CloudServices, WidgetTypeAround, Widget, ImageTextAlternativeEditing, ContextualBalloon, ImageTextAlternativeUI, ImageTextAlternative, Image, ImageUploadEditing, ImageUploadUI, ImageUpload, EasyImage, Paragraph, HeadingEditing, Heading, ImageCaptionEditing, ImageCaption, ImageStyleEditing, ImageStyleUI, ImageStyle, WidgetToolbarRepository, ImageToolbar, IndentEditing, IndentUI, Indent, IndentBlock, LinkUI, Link, ListEditing, List, MediaEmbedEditing, MediaEmbedUI, AutoMediaEmbed, MediaEmbed, PasteFromOffice, TableUtils, TableEditing, TableSelection, TableMouse, TableKeyboard, TableClipboard, Table, TableToolbar, TextTransformation]

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I confirm this bug. What is worse here, if after `Ctrl+A` you press `Backspace`, editor crashes:  
  
```js
Uncaught CKEditorError: move-operation-node-into-itself: Trying to move a range of nodes into one of nodes from that range. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-move-operation-node-into-itself

    at l._validate (https://ckeditor.com/docs/ckeditor5/19.0.0/snippets/examples/document-editor/snippet.js:4:43269)
    at tn.on.priority (https://ckeditor.com/docs/ckeditor5/19.0.0/snippets/examples/document-editor/snippet.js:4:405896)
    at tn.fire (https://ckeditor.com/docs/ckeditor5/19.0.0/snippets/examples/document-editor/snippet.js:4:24585)
    at tn.<computed> [as applyOperation] (https://ckeditor.com/docs/ckeditor5/19.0.0/snippets/examples/document-editor/snippet.js:4:33303)
    at ve.move (https://ckeditor.com/docs/ckeditor5/19.0.0/snippets/examples/document-editor/snippet.js:4:371561)
    at ve.insert (https://ckeditor.com/docs/ckeditor5/19.0.0/snippets/examples/document-editor/snippet.js:4:369042)
    at t (https://ckeditor.com/docs/ckeditor5/19.0.0/snippets/examples/document-editor/snippet.js:4:401781)
    at https://ckeditor.com/docs/ckeditor5/19.0.0/snippets/examples/document-editor/snippet.js:4:401894
    at tn.change (https://ckeditor.com/docs/ckeditor5/19.0.0/snippets/examples/document-editor/snippet.js:4:406474)
    at He (https://ckeditor.com/docs/ckeditor5/19.0.0/snippets/examples/document-editor/snippet.js:4:400970)
```

-  Chrome and Safari crash since 19.0.0 ( on previous versions `Backspace` does nothing )
-  Firefox crashes even on 15.0.0
