### ISSUE TITLE
Editor crashes after inserting a link with the same href just after the link

### ISSUE THREAD

**Issue by jerini** [ckeditor/ckeditor5#8210]
## 📝 Provide detailed reproduction steps (if any)

1.Add link with example link
2. Add second link after it in the same line with same url

### ✔️ Expected result

Shuld add second link with same link url

### ❌ Actual result

error in the console "Uncaught CKEditorError: model-position-after-root" and can't add no more links 

## 📃 Other details

* Browser: Google Chrome
* OS: windows 10
* CKEditor version: error on page https://ckeditor.com/docs/ckeditor5/latest/features/link.html

**Comment by Mgsy** [comment]
Hi, thanks for the report. I can reproduce it and it seems that this is a really old issue (reproducible even on version 17). The key here is to insert a new link with the same `href` just after the link.

1.  Open https://ckeditor.com/docs/ckeditor5/latest/features/link.html.
2.  Put the caret in the editable.
3.  Press Ctrl/Cmd + K, type something.
4.  Press Enter.
5.  Repeat steps 3 and 4.

The editor crashes:

```
snippet.js:4 Uncaught CKEditorError: model-position-after-root Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-position-after-root
 {"root":{"attributes":{"linkHref":"test"},"data":"test"}}
    at Function._createAfter (https://ckeditor.com/docs/ckeditor5/latest/snippets/features/build-link-source/snippet.js:4:15025)
    at cn.createPositionAfter (https://ckeditor.com/docs/ckeditor5/latest/snippets/features/build-link-source/snippet.js:4:430352)
    at Oe.createPositionAfter (https://ckeditor.com/docs/ckeditor5/latest/snippets/features/build-link-source/snippet.js:4:393357)
    at Object.callback (https://ckeditor.com/docs/ckeditor5/latest/snippets/features/build-link-source/snippet.js:4:297584)
    at cn._runPendingChanges (https://ckeditor.com/docs/ckeditor5/latest/snippets/features/build-link-source/snippet.js:4:430940)
    at cn.change (https://ckeditor.com/docs/ckeditor5/latest/snippets/features/build-link-source/snippet.js:4:427766)
    at p.execute (https://ckeditor.com/docs/ckeditor5/latest/snippets/features/build-link-source/snippet.js:4:297100)
    at p.<anonymous> (https://ckeditor.com/docs/ckeditor5/latest/snippets/features/build-link-source/snippet.js:4:33953)
    at p.fire (https://ckeditor.com/docs/ckeditor5/latest/snippets/features/build-link-source/snippet.js:4:25493)
    at p.<computed> [as execute] (https://ckeditor.com/docs/ckeditor5/latest/snippets/features/build-link-source/snippet.js:4:34004)
```
