### ISSUE TITLE
ckeditor build error

### ISSUE THREAD

**Issue by zackhalil** [ckeditor/ckeditor5#8287]
## 📝 Provide detailed reproduction steps (if any)

git clone -b stable https://github.com/ckeditor/ckeditor5-build-decoupled-document
cd ckeditor5-build-decoupled-document
npm install -g npm-check-updates
npm install --save @ckeditor/ckeditor5-remove-format
npm install --save @ckeditor/ckeditor5-word-count

ncu -u
npm install

yarn run build

### ✔️ Expected result

a compile version but I get an error

### ❌ Actual result

```
yarn run v1.22.5
$ webpack --mode production
[webpack-cli] ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema
.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, parallel?, minify?, terserOptions?, extractComments? }
    at validate (E:\boss\reference\ckeditor5\ckeditor5-build-decoupled-document\node_modules\schema-utils\dist\validate.js:104:11)
    at new TerserPlugin (E:\boss\reference\ckeditor5\ckeditor5-build-decoupled-document\node_modules\terser-webpack-plugin\dist\index.js:32:31)     
    at Object.<anonymous> (E:\boss\reference\ckeditor5\ckeditor5-build-decoupled-document\webpack.config.js:34:4)
    at Module._compile (E:\boss\reference\ckeditor5\ckeditor5-build-decoupled-document\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)    
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (E:\boss\reference\ckeditor5\ckeditor5-build-decoupled-document\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at requireConfig (E:\boss\reference\ckeditor5\ckeditor5-build-decoupled-document\node_modules\webpack-cli\lib\groups\ConfigGroup.js:73:18) {    
  errors: [
    {
      keyword: 'additionalProperties',
      dataPath: '',
      schemaPath: '#/additionalProperties',
      params: [Object],
      message: 'should NOT have additional properties',
      schema: false,
      parentSchema: [Object],
      data: [Object]
    }
  ],
  schema: {
    definitions: { Rule: [Object], Rules: [Object] },
    title: 'TerserPluginOptions',
    type: 'object',
    additionalProperties: false,
    properties: {
      test: [Object],
      include: [Object],
      exclude: [Object],
      parallel: [Object],
      minify: [Object],
      terserOptions: [Object],
      extractComments: [Object]
    }
  },
  headerName: 'Terser Plugin',
  baseDataPath: 'options',
  postFormatter: null
}
```

## 📃 Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by zackhalil** [comment]
I updated my software to

node -v
v12.19.0

npm -v
6.14.8

yarn  -v
1.22.5

**Comment by zackhalil** [comment]
If I omit the line in the install below

ncu -u 

I can get a successful build however when I deploy the build in the browser I get the following JS Errors
```

Error: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules
  ckeditor.js:5:11655
ReferenceError: DecoupledEditor is not defined
```

**Comment by zackhalil** [comment]
I found a workaround... I used the package.json built by https://ckeditor.com/ckeditor-5/online-builder/ and download the packages according the package.json 

jq -r '.devDependencies' ./package.json  | grep ":" | sed 's/": "/@/g' | sed 's/,//g' | xargs npm install       

I can now get a build... not sure why 

git clone -b stable https://github.com/ckeditor/ckeditor5-build-decoupled-document
ncu -u
npm install

is so difficult?

**Comment by Mgsy** [comment]
@zackhalil, https://github.com/ckeditor/ckeditor5-build-decoupled-document repository is not maintained anymore. As we switched to a monorepo, all packages could be found in the main [CKEditor 5 repository](https://github.com/ckeditor/ckeditor5) and this is the one you should clone.
