### ISSUE TITLE
ReferenceError in webpack when translation files are located outside of current working directory while using CKEditorWebpackPlugin

### ISSUE THREAD

**Issue by mise0815** [ckeditor/ckeditor5#8450]
## 📝 Provide detailed reproduction steps (if any)

1. Create a webpack build as described [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-2-building-from-source) where the output is located outside of the project space _(in our case this happens when starting webpack with --watch, since we copy the build resources into another folder that is outside of the source project folder)_
2. Add CKEditorWebpackPlugin (checked for versions 23.6 and 23.6.1)
3. Run webpack

### ✔️ Expected result

Webpack build does succeed, even when throwing errors, since option _strict_ for CKEditorWebpackPlugin is set to false by default.

### ❌ Actual result

The webpack build crashes with: _ReferenceError: Cannot access 'uniqueMessages' before initialization_.
This happens because in the case of the output of webpack being outside the current working directory the else branch with `emitError()` in the file servetranslations.js gets called.  
```
// Remove old translation files.
// Assert whether the translation output directory exists inside the cwd.
const pathToLanguages = path.join( compiler.options.output.path, options.outputDirectory );

if ( fs.existsSync( pathToLanguages ) ) {
	if ( pathToLanguages.includes( cwd ) && cwd !== pathToLanguages ) {
		rimraf.sync( pathToLanguages );
	} else {
		emitError(
			`Can't remove path to translation files directory (${ pathToLanguages }). Assert whether you specified a correct path.`
		);
	}
}
```
 `emitError()` uses a constant `uniqueMessages` which is defined later in the same file.

```
// A set of unique messages that prevents message duplications.
const uniqueMessages = new Set();

function emitError( error ) {
	if ( uniqueMessages.has( error ) ) {
		return;
	}

	uniqueMessages.add( error );

	if ( options.strict ) {
		throw new Error( chalk.red( error ) );
	}

	console.error( chalk.red( `[CKEditorWebpackPlugin] Error: ${ error }` ) );
}
```
To fix this issue it would be enough to just define the constant 'uniqueMessages' before the first call of `emitError`. But I would like to ask if its actually necessary to check if translation files are being located outside of the current working directory?

**Comment by Mgsy** [comment]
@ma2ciek, can you take a look at it?

**Comment by robjbrain** [comment]
Also having this issue. Just to add my situation to the list incase it offers any more helpful information.

I have a application with the following structure:

root/
-- resources/
---- assets/
------ ckeditor/
------ webpack.config.js
-------- src/
---------- ckeditor.js
-- public/
---- themes/
------ ckeditor/
-------- js/
---------- ckeditor.js
---------- translations/

In my webpack.config.js I have the following:

```
         output: {
		// The name under which the editor will be exported.
		library: 'ClassicEditor',

		//path: path.resolve( __dirname, 'build' ),
        path: path.resolve( __dirname, '../../../public/themes/ckeditor/js/' ),
		filename: 'ckeditor.js',
		libraryTarget: 'umd',
		libraryExport: 'default'
	},
```

So my build is being resolved to my `public` directory rather than the `build` directory.

But leads to the same error as above:

```
:rootpath:resources/assets/ckeditor/node_modules/webpack-cli/bin/cli.js:281
				throw err;
				^

ReferenceError: Cannot access 'uniqueMessages' before initialization
    at emitError (:rootpath:resources/assets/ckeditor/node_modules/@ckeditor/ckeditor5-dev-webpack-plugin/lib/servetranslations.js:125:3)
    at serveTranslations (:rootpath:resources/assets/ckeditor/node_modules/@ckeditor/ckeditor5-dev-webpack-plugin/lib/servetranslations.js:49:4)
    at CKEditorWebpackPlugin.apply (:rootpath:resources/assets/ckeditor/node_modules/@ckeditor/ckeditor5-dev-webpack-plugin/lib/index.js:106:3)
    at webpack (:rootpath:resources/assets/ckeditor/node_modules/webpack/lib/webpack.js:51:13)
    at processOptions (:rootpath:resources/assets/ckeditor/node_modules/webpack-cli/bin/cli.js:272:16)
    at :rootpath:resources/assets/ckeditor/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (:rootpath:resources/assets/ckeditor/node_modules/yargs/yargs.js:576:18)
    at :rootpath:resources/assets/ckeditor/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (:rootpath:resources/assets/ckeditor/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (:rootpath:resources/assets/ckeditor/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

I am running `yarn build`. It is okay the first time (when the files do not exist) but fails afterwards.

My rubbish short term solution is just to run:

`rm -rf ../../../public/themes/ckeditor/js/translations; yarn build`

Whenever I want to build.

**Comment by leevigraham** [comment]
@pomek https://github.com/ckeditor/ckeditor5-dev/pull/849 fixes the issue.
