### ISSUE TITLE
Executing tests for the entire repository fail

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#8571]
## 📝 Provide detailed reproduction steps (if any)

1. `yarn test --reporter=dots --repositories=ckeditor5`

### ✔️ Expected result

Green results.

### ❌ Actual result

```
Chrome 86.0.4240.198 (Mac OS 10.15.7) ImageResizeHandles command disables the resizer if the command is disabled FAILED
	TypeError: Cannot read property 'isEnabled' of undefined
	    at Context.eval (webpack:///./packages/ckeditor5-image/tests/imageresize/imageresizehandles.js?:117:20)

Chrome 86.0.4240.198 (Mac OS 10.15.7) ImageResizeHandles command the resizer is disabled from the beginning when the command is disabled when the image is inserted FAILED
	TypeError: Cannot read property 'isEnabled' of undefined
	    at Context.eval (webpack:///./packages/ckeditor5-image/tests/imageresize/imageresizehandles.js?:142:20)

Chrome 86.0.4240.198 (Mac OS 10.15.7) ImageResizeHandles undo integration has correct border size after undo FAILED
	AssertionError: expected '' to equal '120px'
	    at Context.eval (webpack:///./packages/ckeditor5-image/tests/imageresize/imageresizehandles.js?:210:45)

Chrome 86.0.4240.198 (Mac OS 10.15.7) ImageResizeHandles widget toolbar integration visibility after the resize was canceled FAILED
	TypeError: Cannot read property 'cancel' of undefined
	    at Context.eval (webpack:///./packages/ckeditor5-image/tests/imageresize/imageresizehandles.js?:447:12)

Chrome 86.0.4240.198 (Mac OS 10.15.7) MentionUI typing integration asynchronous list with custom trigger should fire requestFeed:response when request feed return a response FAILED
	AssertError: expected spy to be called once but was called 0 times
	    at Object.fail (node_modules/sinon/pkg/sinon.js:158:25)
	    at failAssertion (node_modules/sinon/pkg/sinon.js:115:20)
	    at Object.assert.<computed> [as calledOnce] (node_modules/sinon/pkg/sinon.js:141:17)
	    at eval (webpack:///./packages/ckeditor5-mention/tests/mentionui.js?:990:20)
```

```
Chrome 86.0.4240.198 (Mac OS 10.15.7): Executed 15549 of 15572 (5 FAILED) (skipped 23) (4 mins 2.65 secs / 1 min 23.992 secs)
```

## 📃 Other details

* Browser: Chrome 86.0.4240.198
* OS: MacOS
* CKEditor version: Latest [`#release`](https://github.com/ckeditor/ckeditor5/commit/e2f43e167033b9cee81dcc63abca5caa164a3ba5) branch

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by oleq** [comment]
AFAIR this is related to editor focus. When you run tests and don't touch the computer they pass. If you do something at that time – they will fail. That's why they pass on CI.

There's probably some editing root focus call missing in tests.
