### ISSUE TITLE
Error when merging paragraphs and undo

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#8976]
## 📝 Provide detailed reproduction steps (if any)

1. Open any editor
2. Create two paragraphs with text content
3. Merge them by putting cursor at the beginning of the second one and pressing `backspace`
4. Delete the whole new paragraph
5. `undo` 4 times

### ✔️ Expected result

Undo works without errors. Content looks like in step 2

### ❌ Actual result

Console error:
```js
Uncaught CKEditorError: merge-operation-target-position-invalid
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-merge-operation-target-position-invalid
    at MergeOperation._validate (http://localhost:8125/ckeditor5/tests/manual/all-features.js:61573:10)
    at Model.on.priority (http://localhost:8125/ckeditor5/tests/manual/all-features.js:59082:14)
    at Model.fire (http://localhost:8125/ckeditor5/tests/manual/all-features.js:156788:30)
    at Model.<computed> [as applyOperation] (http://localhost:8125/ckeditor5/tests/manual/all-features.js:159187:16)
    at UndoCommand._undo (http://localhost:8125/ckeditor5/tests/manual/all-features.js:150692:11)
    at Object.callback (http://localhost:8125/ckeditor5/tests/manual/all-features.js:151010:9)
    at Model._runPendingChanges (http://localhost:8125/ckeditor5/tests/manual/all-features.js:59821:58)
    at Model.enqueueChange (http://localhost:8125/ckeditor5/tests/manual/all-features.js:59227:10)
    at UndoCommand.execute (http://localhost:8125/ckeditor5/tests/manual/all-features.js:151009:21)
    at UndoCommand.<anonymous> (http://localhost:8125/ckeditor5/tests/manual/all-features.js:159183:32)
```

## Screencast

https://user-images.githubusercontent.com/34380544/106609468-e00d4380-6565-11eb-8782-1a605d47aa79.mp4

## 📃 Other details

* Browser: any
* First affected CKEditor version: very old, even on version 15

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by scofalik** [comment]
Could you check if it works on `i/8870`?

**Comment by FilipTokarski** [comment]
Actually, I found it when testing `i/8870`
