### ISSUE TITLE
Dev tasks: gulp update fails to pull changes

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#90]
Check the branch "ui" in this repo. Check it out and run `gulp update`. I get:

```sh
(ui 3b99f9b) p@macintosh /www/ckeditor5> gulp update
[16:07:24] Using gulpfile /www/ckeditor5/gulpfile.js
[16:07:24] Starting 'update'...
Checking out ckeditor5-core to t/209...
Pulling changes to ckeditor5-core...
[16:07:26] 'update' errored after 1.8 s
[16:07:26] Error: Error while executing `cd /www/ckeditor5-core && git pull origin t/209`:


    at Object.shExec (/www/ckeditor5/dev/tasks/dev/utils/tools.js:20:10)
    at Object.pull (/www/ckeditor5/dev/tasks/dev/utils/git.js:95:9)
    at module.exports (/www/ckeditor5/dev/tasks/dev/tasks/update.js:45:10)
    at Gulp.<anonymous> (/www/ckeditor5/dev/tasks/dev/tasks.js:36:3)
    at module.exports (/www/ckeditor5/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/www/ckeditor5/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/www/ckeditor5/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/www/ckeditor5/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:46:20
    at nextTickCallbackWith0Args (node.js:433:9)
```

**Comment by Reinmar** [comment]
Turns out I had a problem inside that repository:

```
(t/209 9a4406b) p@macintosh /www/ckeditor5-core> git pull origin t/209
From github.com:ckeditor/ckeditor5-core
 * branch            t/209      -> FETCH_HEAD

It seems that there is already a rebase-apply directory, and
I wonder if you are in the middle of another rebase.  If that is the
case, please try
	git rebase (--continue | --abort | --skip)
If that is not the case, please
	rm -fr "/www/ckeditor5-core/.git/rebase-apply"
and run me again.  I am stopping in case you still have something
valuable there.
```

So the problem is that the gulp task doesn't print the error to the console. I'll report a separate ticket for this.

**Comment by Reinmar** [comment]
Actually, let's solve this in #78.
