### ISSUE TITLE
Undo after splitting elements crashes the editor.

### ISSUE THREAD

**Issue by magda-chrzescian** [ckeditor/ckeditor5#9296]
### Scenario 1: ###

1. Open any editor instance.
2. Type a few letters.
3. Set the caret between the letters and press `enter` 4 times.
4. Press `backspace` 4 times.
5. Press `Ctrl+Z` 5 times -> **The action is not executed properly**.
6. Press `Ctrl+Shift+Z` -> **The editor crashes, no action possible except of typing**.

This is the error thrown in the 6th point:
```Uncaught CKEditorError: split-operation-how-many-invalid
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-split-operation-how-many-invalid
    at l._validate (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:101751)
    at ft.on.priority (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:405830)
    at ft.fire (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:56829)
    at ft.<computed> [as applyOperation] (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:59799)
    at u._undo (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:462589)
    at Object.callback (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:463626)
    at ft._runPendingChanges (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:409575)
    at ft.enqueueChange (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:406706)
    at u.execute (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:463408)
    at u.<anonymous> (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:59748)
```

This is the error thrown while trying to do anything else with the editor:
```snippet.js:4 Uncaught CKEditorError: model-nodelist-offset-out-of-bounds {"offset":4,"nodeList":[{"data":"aaa"}]}
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-nodelist-offset-out-of-bounds
    at offsetToIndex (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:191156)
    at c.offsetToIndex (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:94211)
    at a (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:29321)
    at r.get textNode [as textNode] (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:23466)
    at W (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:390188)
    at H._validateSelectionRange (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:390027)
    at m.<anonymous> (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:135889)
    at m.fire (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:56829)
    at m._setRanges (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:193998)
    at m.setTo (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:193027)
```

### Scenario 2: ###

1. Open any editor instance.
2. Create content with a `header` and `paragraph`.
3. Set the caret at the beginning of the `header` and press `enter` 2 times, then `backspace` 2 times.
4. Set the caret between the letters of the header and press `enter` 2 times, then `backspace` 2 times.
5. Keep pressing `Ctrl-Z` until you get a console error and the editor crashes.

This is the error thrown in the 5th point:
```snippet.js:4 Uncaught CKEditorError: rename-operation-wrong-name
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-rename-operation-wrong-name
    at a._validate (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:174102)
    at ft.on.priority (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:405830)
    at ft.fire (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:56829)
    at ft.<computed> [as applyOperation] (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:59799)
    at l._undo (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:462589)
    at Object.callback (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:463078)
    at ft._runPendingChanges (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:409575)
    at ft.enqueueChange (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:406706)
    at l.execute (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:463052)
    at l.<anonymous> (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:59748)
```

This is the error thrown while trying to do anything else with the editor:
```snippet.js:4 Uncaught CKEditorError: model-nodelist-offset-out-of-bounds {"offset":4,"nodeList":[{"data":"AAA"}]}
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-nodelist-offset-out-of-bounds
    at offsetToIndex (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:191156)
    at c.offsetToIndex (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:94211)
    at a (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:29321)
    at r.get textNode [as textNode] (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:23466)
    at W (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:390188)
    at H._validateSelectionRange (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:390027)
    at m.<anonymous> (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:135889)
    at m.fire (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:56829)
    at m._setRanges (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:193998)
    at m.setTo (https://ckeditor.com/docs/ckeditor5/latest/snippets/build-classic-source/snippet.js:4:193027)
```

![2021-03-22 09 04 13](https://user-images.githubusercontent.com/14334820/111958867-0bd09280-8aee-11eb-89c5-adf3f9d31814.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by urbanspr1nter** [comment]
I was able to hit this pretty easily by just splitting a text node with some attributes (like bold, italic, etc) and pasting in plain text in the following order:
1. end of the text node
2. middle of the text node (causing the text node to split)
3. beginning of the text node
Then perform the undo operations... The editor crashes.

**Comment by mabryl** [comment]
Can confirm that issue still persists in our online demos.

**Comment by scofalik** [comment]
I can reproduce scenario 1 without typing letters, just make two enters, then two backspace, then undo all and do one redo. I get: `split-operation-how-many-invalid`. I also can see that undos are not done properly.

I can reproduce second scenario too but only if I start re-doing. I get the same error as above.

**Comment by scofalik** [comment]
Fixed by https://github.com/ckeditor/ckeditor5/pull/17071

**Comment by scofalik** [comment]
It appeared that the second scenario can be still reproduced, only I didn't follow the steps precisely. Also, I managed to narrow down this case. I created a new issue for it.
